=== mars-sim/mars-sim/mars-sim-core/src/main/resources/xml/authority/authority.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema"
           elementFormDefault="qualified">

    <!-- Root element definition for authority -->
    <xs:element name="authority" type="authorityType"/>

    <!-- Complex type definition for authority -->
    <xs:complexType name="authorityType">
        <xs:sequence>
            <!-- At least one country is required -->
            <xs:element name="country" type="countryType" maxOccurs="unbounded"/>
            
            <!-- Settlement names are optional but can have multiple entries -->
            <xs:element name="settlement-name" type="settlementNameType" minOccurs="0" maxOccurs="unbounded"/>
            
            <!-- Rover names are optional but can have multiple entries -->
            <xs:element name="rover-name" type="roverNameType" minOccurs="0" maxOccurs="unbounded"/>
        </xs:sequence>
        
        <!-- Required attributes for authority -->
        <xs:attribute name="code" type="xs:string" use="required"/>
        <xs:attribute name="name" type="xs:string" use="required"/>
        <xs:attribute name="corporation" type="xs:boolean" use="required"/>
        <xs:attribute name="agenda" type="xs:string" use="required"/>
        <xs:attribute name="gender-ratio" type="genderRatioType" use="required"/>
    </xs:complexType>

    <!-- Complex type for country elements -->
    <xs:complexType name="countryType">
        <xs:attribute name="name" type="xs:string" use="required"/>
    </xs:complexType>

    <!-- Complex type for settlement-name elements -->
    <xs:complexType name="settlementNameType">
        <xs:attribute name="name" type="xs:string" use="required"/>
    </xs:complexType>

    <!-- Complex type for rover-name elements -->
    <xs:complexType name="roverNameType">
        <xs:attribute name="name" type="xs:string" use="required"/>
    </xs:complexType>

    <!-- Simple type for gender-ratio with decimal constraint -->
    <xs:simpleType name="genderRatioType">
        <xs:restriction base="xs:decimal">
            <xs:minInclusive value="0.0"/>
            <xs:maxInclusive value="1.0"/>
            <xs:fractionDigits value="3"/>
        </xs:restriction>
    </xs:simpleType>

</xs:schema>

=== mars-sim/mars-sim/mars-sim-core/src/main/resources/xml/authority/authority_csa.xml
<?xml version="1.0" encoding="UTF-8"?>
<authority xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="authority.xsd"
		code="CSA" name="Canadian Space Agency" corporation="false"
					agenda="Communication Network"  gender-ratio="0.5">
			<country name="Canada"/>
			<settlement-name name="New Quebec" />
			<settlement-name name="New Yukon" />
			<settlement-name name="Sherbrooke" />
			<settlement-name name="Fredericton" />
			<settlement-name name="Navi" />
			<settlement-name name="SpaceRyde" />
			<settlement-name name="Nunavut" />
			<settlement-name name="New Saint John" />
			<settlement-name name="New Banff" />		
			<settlement-name name="New Jasper" />
			<settlement-name name="New Saint Albert" />
			<settlement-name name="New Delta" />
			<settlement-name name="Caelestis" />
			
			<rover-name name="Yellowknife" />
			<rover-name name="Halifax" />
			<rover-name name="Kingston" />
			<rover-name name="Waterloo" />
			<rover-name name="Windsor" />
			<rover-name name="Dawson" />
			<rover-name name="Whitehorse" />	
			<rover-name name="Ottawa" />
			<rover-name name="Nova Scotia" />
			<rover-name name="Notre Dame" />
			<rover-name name="Buffalo Jump" />
			<rover-name name="Toronto" />
			
		</authority>

=== mars-sim/mars-sim/mars-sim-core/src/main/resources/xml/authority/authority_cnsa.xml
<?xml version="1.0" encoding="UTF-8"?>
<authority xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="authority.xsd"
		code="CNSA" name="China National Space Administration" corporation="false"
					agenda="Mineral Prospecting" gender-ratio="0.75">
			<country name="China"/>
			<settlement-name name="Tian Cheng" />
			<settlement-name name="Xin Cheng" />
			<settlement-name name="Huoxing Cheng" />
			<settlement-name name="Chang-e Cheng" />
			<settlement-name name="Xin Shenzhen" />
			<settlement-name name="Xin Tianjin" />
			<settlement-name name="Xin Shanghai" />
			<settlement-name name="Xin Beijing" />
			<settlement-name name="New Macau" />
			<settlement-name name="Xin Chongqing" />
			<settlement-name name="New Manchuria" />
			<settlement-name name="Xin Xianggang" />
			<settlement-name name="Luzhou" />
			<settlement-name name="Huoxing Cheng" />
			
			<rover-name name="Shenzhou" />  <!-- Chinese for divine craft -->
			<rover-name name="Zhanshen" />  <!-- Chinese for god of war -->
			<rover-name name="Zidan" />    <!-- Chinese for bullet -->
			<rover-name name="Huojian" />  <!-- Chinese for rocket -->
			<rover-name name="Bolang" />   <!-- Chinese for wave front -->
			<rover-name name="Lingxian" /> <!-- Chinese for leading the way -->
			<rover-name name="GuoLu" />    <!-- Chinese for passing through -->
			<rover-name name="Youli" />    <!-- Chinese for traveling -->
			<rover-name name="Changtu" />   <!-- Chinese for long journey" -->
			<rover-name name="Hangcheng" /> <!-- Chinese for voyage -->
			<rover-name name="Youke" />     <!-- Chinese for traveler -->
			<rover-name name="YouShan" />   <!-- Chinese for treking mountain -->
			<rover-name name="Aoxiang" />   <!-- Chinese for soaring -->
			<rover-name name="Piaofu" />    <!-- Chinese for hovering -->
			<rover-name name="Gaofei" />    <!-- Chinese for flying up -->
		</authority>

=== mars-sim/mars-sim/mars-sim-core/src/main/resources/xml/authority/authority_BO.xml
<?xml version="1.0" encoding="UTF-8"?>
<authority xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="authority.xsd"
		code="BO" name="Blue Origin" corporation="true"
					agenda="Colony Construction" gender-ratio="0.5">
			<country name="United States"/>
			<settlement-name name="Aurora" />
			<settlement-name name="Astro City" />
			<settlement-name name="Amazone" />
			<settlement-name name="Borealis" />
			<settlement-name name="Ender" />
			<settlement-name name="Eos" />
			<settlement-name name="Liberty" />
			<settlement-name name="Terminus" />
			<settlement-name name="Nox" />
			<settlement-name name="Hera" />
			<settlement-name name="Chrono" />
												
			<rover-name name="Desert Pearl" />
			<rover-name name="Desert Rose" />
			<rover-name name="Deimos Tide" />
			<rover-name name="Desert Star" />
			<rover-name name="Drift Wood" />
			<rover-name name="Desertfarer" />
			<rover-name name="Dream Chaser" />
			<rover-name name="Dune Drifter" />
			<rover-name name="Dune Runner" />
			<rover-name name="Niagara" />
			<rover-name name="Blue Bird" />
			<rover-name name="Vulture" />
			<rover-name name="Froggie" />
			<rover-name name="Croc" />
			<rover-name name="Phoenix" />
			<rover-name name="Sunrise" />
			<rover-name name="Avatar" />		
			<rover-name name="Solas" />
			<rover-name name="Rebus" />
		</authority>

=== mars-sim/mars-sim/mars-sim-core/src/main/resources/xml/authority/authority_uaesa.xml
<?xml version="1.0" encoding="UTF-8"?>
<authority xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="authority.xsd"
		code="UAESA" name="United Arab Emirates Space Agency" corporation="false"
					agenda="Space Economy" gender-ratio="0.9">
			<country name="United Arab Emirates"/>
			<settlement-name name="New Salem" />
			<settlement-name name="New Dubai" />
			<settlement-name name="New Rashid" />
			<settlement-name name="New Sultan" />
			<settlement-name name="New Khalifa" />
			<settlement-name name="New Qubaisi" />
			<settlement-name name="New Amiri" />
			<settlement-name name="New Maktoum" />
			<settlement-name name="New Nahyan" />
			<settlement-name name="New Bateen" />
			<settlement-name name="New Ajman" />
												
			<rover-name name="Tunb" />
			<rover-name name="Ruwais" />
			<rover-name name="Masfut" />
			<rover-name name="Manama" />
			<rover-name name="Qidfa" />
			<rover-name name="Kalba" />
			<rover-name name="Baynunah" />
			<rover-name name="Abu Musa" />
			<rover-name name="Muzayrah" />
			<rover-name name="Mleiha" />
			<rover-name name="Hatta" />
			<rover-name name="Dibba" />
			<rover-name name="Siji" />
			<rover-name name="Sharjah" />
			<rover-name name="Sharm" />
			<rover-name name="Bu Hasa" />
			<rover-name name="Hili" />		
			<rover-name name="Hamim" />
			<rover-name name="Dhaid" />
			<rover-name name="Aldar" />
			<rover-name name="Aramex" />
			<rover-name name="Emaar" />
			<rover-name name="Etihad" />		
			<rover-name name="Etisalat" />
			<rover-name name="Jumeirah" />
		</authority>

=== mars-sim/mars-sim/mars-sim-core/src/main/resources/xml/authority/authority_asi.xml
<?xml version="1.0" encoding="UTF-8"?>
<authority xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="authority.xsd"
		code="ASI" name="Agenzia Spaziale Italiana" corporation="false"
					agenda="Space Collaboration" gender-ratio="0.694">
			<!-- For engineering master's graduates in 2023, the overall percentage of 
			women was 30.6%, with specific fields showing stark imbalances: Biomedical 
			Engineering had 63.0% women, while fields like Electric Engineering (14.0% women), 
			Mechanic Engineering (13.3% women), and Computer Engineering (18.1% women) 
			had much lower female representation.-->		
			<country name="Italy"/>
			<settlement-name name="New Rome" />
			<settlement-name name="Costellazione" />
			<settlement-name name="Sole" />
			<settlement-name name="Cosmos" />
			<settlement-name name="Galassia" />
			<settlement-name name="Solare" />		
			<settlement-name name="Eclissi" />
			<settlement-name name="Osservatorio" />	

			<rover-name name="Basilio" />  
			<rover-name name="Malindi" />  
			<rover-name name="Matera" />    
			<rover-name name="Bianca" />  
			<rover-name name="Asteroide" />  
			<rover-name name="Stella" />  
			<rover-name name="Luna" /> 
			<rover-name name="Cielo" /> 
			<rover-name name="Celeste" /> 
			<rover-name name="Stella" /> 
			<rover-name name="Telescopio" /> 
			<rover-name name="Buco Nero" /> 			
			<rover-name name="Universo" /> 	
			<rover-name name="Pianeta" /> 	
						
			<rover-name name="Fiat" /> 
			<rover-name name="Ferrari" /> 
			<rover-name name="Lamborghini" /> 
			<rover-name name="Lancia" /> 
			<rover-name name="Maserati" /> 			
			<rover-name name="Abarth" /> 	
			<rover-name name="Pagani" /> 							
	
			<rover-name name="Pininfarina" /> 
			<rover-name name="Alfa Romeo" /> 
			<rover-name name="Bizzarrini" /> 
			<rover-name name="Casalini" /> 
			<rover-name name="Cecomp" /> 			
			<rover-name name="Cirelli" /> 	
			<rover-name name="Corbellati" /> 
																					
		</authority>

=== mars-sim/mars-sim/mars-sim-core/src/main/resources/xml/authority/authority_hso.xml
<?xml version="1.0" encoding="UTF-8"?>
<authority xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="authority.xsd"
		code="HSO" name="Hungarian Space Research Office" corporation="false"
					agenda="Economic Integration" gender-ratio="0.746">
		<!-- Recent data from 2023 indicates that women account for only 25.4% of tertiary 
			STEM students, the lowest share in the European Union.  Consequently, men comprise the remaining 74.6% -->
			<country name="Hungry"/>
			<settlement-name name="Von Neumann" />
			<settlement-name name="Szilard" />
			<settlement-name name="Wigner" />
			<settlement-name name="Gabor" />
			<settlement-name name="Szent-Gyorgyi" />
			<settlement-name name="Jedlik" />		
			<settlement-name name="Eotvos" />
			<settlement-name name="Semmelweis" />
			<settlement-name name="Balaton" />

			<rover-name name="Giotto" />  
			<rover-name name="Philae" />  
			<rover-name name="Hera" />    
			<rover-name name="Ramses" />  
			<rover-name name="Argonaut" />  
			<rover-name name="Karman" /> 
			<rover-name name="Irinyi" />  
			<rover-name name="Puskas" /> 
			<rover-name name="Erdos" /> 
			<rover-name name="Koda" /> 
			<rover-name name="Vodochody" /> 
			<rover-name name="Dunai" /> 
			<rover-name name="Delfin" /> 			
			<rover-name name="Ikarus" /> 	
			<rover-name name="Csepel" /> 	

			<rover-name name="Ganz" /> 			
			<rover-name name="Pauger" /> 																			
		</authority>

=== mars-sim/mars-sim/mars-sim-core/src/main/resources/xml/authority/authority_SPACEX.xml
<?xml version="1.0" encoding="UTF-8"?>
<authority xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="authority.xsd"
		code="SPACEX" name="Space Exploration Technologies Corporation" corporation="true"
					agenda="Planet Life" gender-ratio="0.5">
			<country name="United States"/>
			<settlement-name name="Muskville" />
			<settlement-name name="Falcon Station" />
			<settlement-name name="Nicolas Town" />
			<settlement-name name="Elonia" />
			<settlement-name name="Solarian" />
			<settlement-name name="New Eden" />
			<settlement-name name="Teslapolis" />		
			<settlement-name name="IronVille" />
			<settlement-name name="Boringburg" />
			<settlement-name name="Hawthorne" />
			<settlement-name name="XAE" />
			<settlement-name name="New Vegas" />
			<settlement-name name="Brownsville" />			
			<rover-name name="Genesis" />
			<rover-name name="Vega" />
			<rover-name name="Raptor" />
			<rover-name name="Merlin" />
			<rover-name name="Roadster" />
			<rover-name name="Gypsea" />
			<rover-name name="Nomad" />
			<rover-name name="Oasis" />
			<rover-name name="Odyssey" />
			<rover-name name="Osprey" />
			<rover-name name="Drifter" />
			<rover-name name="Princess" />
			<rover-name name="Serenity" />
			<rover-name name="Ironman" />
			<rover-name name="Mariner" />			
		</authority>

=== mars-sim/mars-sim/mars-sim-core/src/main/resources/xml/authority/authority_cnes.xml
<?xml version="1.0" encoding="UTF-8"?>
<authority xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="authority.xsd"
		code="CNES" name="National Centre for Space Studies" corporation="false"
					agenda="Space Accessibility" gender-ratio="0.78">
		<!-- France has a share of female graduates in STEM fields 22%. 
		On the other hand, the European Union (EU) overall has women 
		comprising 52% of the STEM workforce, which is higher than the US (28%) and India (27%).
		Globally, women constitute 35% of STEM graduates.
		-->
			<country name="France"/>
			<settlement-name name="Laplace" />
			<settlement-name name="Galileo" />
			<settlement-name name="Coulomb" />
			<settlement-name name="Berenice" />
			<settlement-name name="Curie" />
			<settlement-name name="Herschel" />		
			<settlement-name name="Pasteur" />
			<settlement-name name="Copernicus" />	
			<settlement-name name="Jules Verne" />	
			<settlement-name name="Ampere" />				
			<settlement-name name="Poincare" />
			<settlement-name name="Fourier" />			
						
			<rover-name name="Veronique" />  
			<rover-name name="Jean-Francois" />  
			<rover-name name="Jacques-Louis" />    
			<rover-name name="Picard" />  
			<rover-name name="Auger" />  
			<rover-name name="Denisse" />  
			<rover-name name="Gobelins" /> 
			<rover-name name="Melies" /> 
			<rover-name name="Charles" /> 
			<rover-name name="Rozier" /> 
			<rover-name name="Gay-Lussac" /> 
			<rover-name name="Colbert" /> 			
			<rover-name name="Diamant" /> 	
			<rover-name name="Asterix" /> 	
			<rover-name name="Astrium" /> 	
			<rover-name name="Safran" /> 
			<rover-name name="Ariane" /> 
			<rover-name name="Dassault" /> 
			<rover-name name="Aerospatiale" /> 
			<rover-name name="Arago" /> 			
			<rover-name name="Baptiste" /> 	
			<rover-name name="Thales" /> 
			<rover-name name="Airbus" /> 																	
		</authority>
