=== mars-sim/mars-sim/mars-sim-core/src/main/resources/conf/dtd/people.dtd
<!ELEMENT people-configuration (oxygen-consumption-rate, water-consumption-rate,
dessert-consumption-rate, food-consumption-rate, oxygen-deprivation-time, water-deprivation-time,
food-deprivation-time, starvation-start-time, min-air-pressure, decompression-time,
min-temperature, max-temperature, freezing-time, stress-breakdown-chance,
gender-male-percentage, personality-types, person-name-list, person-list)>
<!ELEMENT oxygen-consumption-rate EMPTY>
<!ATTLIST oxygen-consumption-rate value CDATA #REQUIRED>
<!ELEMENT water-consumption-rate EMPTY>
<!ATTLIST water-consumption-rate value CDATA #REQUIRED>
<!ELEMENT dessert-consumption-rate EMPTY>
<!ATTLIST dessert-consumption-rate value CDATA #REQUIRED>
<!ELEMENT food-consumption-rate EMPTY>
<!ATTLIST food-consumption-rate value CDATA #REQUIRED>
<!ELEMENT oxygen-deprivation-time EMPTY>
<!ATTLIST oxygen-deprivation-time value CDATA #REQUIRED>
<!ELEMENT water-deprivation-time EMPTY>
<!ATTLIST water-deprivation-time value CDATA #REQUIRED>
<!ELEMENT food-deprivation-time EMPTY>
<!ATTLIST food-deprivation-time value CDATA #REQUIRED>
<!ELEMENT starvation-start-time EMPTY>
<!ATTLIST starvation-start-time value CDATA #REQUIRED>
<!ELEMENT min-air-pressure EMPTY>
<!ATTLIST min-air-pressure value CDATA #REQUIRED>
<!ELEMENT decompression-time EMPTY>
<!ATTLIST decompression-time value CDATA #REQUIRED>
<!ELEMENT min-temperature EMPTY>
<!ATTLIST min-temperature value CDATA #REQUIRED>
<!ELEMENT max-temperature EMPTY>
<!ATTLIST max-temperature value CDATA #REQUIRED>
<!ELEMENT freezing-time EMPTY>
<!ATTLIST freezing-time value CDATA #REQUIRED>
<!ELEMENT stress-breakdown-chance EMPTY>
<!ATTLIST stress-breakdown-chance value CDATA #REQUIRED>
<!ELEMENT gender-male-percentage EMPTY>
<!ATTLIST gender-male-percentage value CDATA #REQUIRED>
<!ELEMENT personality-types (mbti*)>
<!ELEMENT mbti EMPTY>
<!ATTLIST mbti type CDATA #REQUIRED>
<!ATTLIST mbti percentage CDATA #REQUIRED>
<!ELEMENT person-name-list (person-name*)>
<!ELEMENT person-name EMPTY>
<!ATTLIST person-name value CDATA #REQUIRED>
<!ATTLIST person-name gender (male|female) #REQUIRED>
<!ELEMENT person-list (person*)>
<!ELEMENT person (personality-trait-list?, natural-attribute-list?, skill-list?, relationship-list?)>
<!ATTLIST person name CDATA #REQUIRED>
<!ATTLIST person gender (male|female) #IMPLIED>
<!ATTLIST person personality-type CDATA #IMPLIED>
<!ATTLIST person settlement CDATA #IMPLIED>
<!ATTLIST person job CDATA #IMPLIED>
<!ATTLIST person favorite-main-dish CDATA #IMPLIED>
<!ATTLIST person favorite-side-dish CDATA #IMPLIED>
<!ATTLIST person favorite-dessert CDATA #IMPLIED>
<!ATTLIST person favorite-activity CDATA #IMPLIED>
<!ELEMENT personality-trait-list (personality-trait*)>
<!ELEMENT personality-trait EMPTY>
<!ATTLIST personality-trait name CDATA #REQUIRED>
<!ATTLIST personality-trait value CDATA #REQUIRED>
<!ELEMENT natural-attribute-list (natural-attribute*)>
<!ELEMENT natural-attribute EMPTY>
<!ATTLIST natural-attribute name CDATA #REQUIRED>
<!ATTLIST natural-attribute value CDATA #REQUIRED>
<!ELEMENT skill-list (skill*)>
<!ELEMENT skill EMPTY>
<!ATTLIST skill name CDATA #REQUIRED>
<!ATTLIST skill level CDATA #REQUIRED>
<!ELEMENT relationship-list (relationship*)>
<!ELEMENT relationship EMPTY>
<!ATTLIST relationship person-name CDATA #REQUIRED>
<!ATTLIST relationship opinion CDATA #REQUIRED>

=== mars-sim/mars-sim/mars-sim-core/src/main/resources/conf/people.xml
<?xml version="1.0" encoding="UTF-8"?>

<!DOCTYPE people-configuration SYSTEM "conf/dtd/people.dtd">
<!--
1. EMU: Extravehicular Activity Suit Systems Design How to Walk, Talk, and Breathe on Mars
http://www.lpi.usra.edu/publications/reports/CB-979/cornell.pdf
 -->

<people-configuration>

	<!-- The average amount of oxygen (kg) breathed by a person each Martian Sol -->
	<!-- Default: 1.0 -->
	<oxygen-consumption-rate value="1.0" />

	<!-- The average amount of water (kg) drank by a person each Martian Sol -->
	<!-- Default: 4.0 -->
	<water-consumption-rate value="4.0" />

	<!-- The average amount of dessert (kg) in dry weight eaten by a person each Martian Sol -->
	<!-- Default: 0.3 dry Weight (arbitrary), note that beverage has arbitrary predefined weight-->
	<dessert-consumption-rate value="0.3" />

	<!-- The average amount of food (kg) in dry weight eaten by a person each Martian Sol -->
	<!-- Default: 0.62 dry Weight -->
	<food-consumption-rate value="0.62" />

	<!-- TODO: account for carbohydrates & protein content
	(1). http://settlement.arc.nasa.gov/75SummerStudy/Chapt3.html#Food
		A heavy workload requires about 3000 Cal/day...consist of 2000 g of water, 470 g dry weight of various carbohydrates and fats,
		60 to 70 g dry weight of proteins, and adequate quantities of various minerals and vitamins
	(2). http://settlement.arc.nasa.gov/Contest/Results/96/winner/seis.html#HUMAN
			Food solids: 0.62Kg ,  Water in food: 1.15Kg
	(3). Food energy per mass: http://en.wiki2.org/wiki/Food_energy
		a. Fats and ethanol have 37 and 29 kJ/g (8.8 and 6.9 kcal/g)
	    b. Proteins and most carbohydrates have about 17 kJ/g (4.1 kcal/g)
		c. Notes:
		1. Each meal is 0.62kg / 4
		2. Assume a daily intake of:
			0.1 kg of fats,
			0.4 kg of proteins and carbo,
			0.12 of fibers and others,

			Daily intake :	.1 * 1000 * 33 kJ + .4 * 1000 * 17 kJ + ... = 10100 kJ or 2415.2 kcal

			Each meal has 0.1550 kg or  2525 kJ
			1 kg ==> 16290.323 kJ

		FOOD_COMPOSITION_ENERGY_RATIO = 16290.323


	(4). A standard conversion in the Systeme Internation de'Unites is that one calorie equals 4.186 joules,
		 which is how much energy is given off in heat to raise 1 kg of water 1 degree Celsius.

			4.186 J = 1 cal		OR 4.186 kJ = 1 Cal or 1 kcal

		a). 1 small kilocalorie (kcal) is equal to 1 large food calorie (Cal):
			1 kcal = 1 Cal
		b). 1 small kilocalorie (kcal) is equal to 1000 small calories (cal):
			1 kcal = 1000 cal

	-->

	<!-- Number of millisols a person can survive without oxygen -->
	<!-- Note: 1 millisol = 88.77 seconds -->
	<!-- Default: 3.38 -->
	<oxygen-deprivation-time value="3.38" />

	<!-- Number of sols a person can survive without water -->
	<!-- Default: 6.0 -->
	<water-deprivation-time value="6.0" />

	<!-- Number of sols a person can survive without food -->
	<!-- Default: 21.0 -->
	<food-deprivation-time value="21.0" />

	<!-- Number of sols a person can go without food before starvation sets in -->
	<!-- Default: 3.0 -->
	<starvation-start-time value="3.0" />

	<!-- Minimum air pressure (Pa) a person can withstand without harm -->
	<!-- Default: 25331.25 -->
	<min-air-pressure value="25331.25" />

	<!-- Number of millisols a person can survive in decompression -->
	<!-- Note: 1 millisol = 88.77 seconds -->
	<!-- Default: 1.0 -->
	<decompression-time value="1.0" />

	<!-- Minimum temperature (degrees celsius) a person can withstand without harm -->
	<!-- Default: 0 degrees celsius -->
	<min-temperature value="0.0" />

	<!-- Maximum temperature (degrees celsius) a person can withstand without harm -->
	<!-- Default: 48 degrees celsius -->
	<max-temperature value="48.0" />

	<!-- Number of millisols a person can survive below minimum temperature -->
	<!-- Note: 1 millisol = 88.77 seconds -->
	<!-- Default: 160.0 -->
	<freezing-time value="160.0" />

	<!-- Base percent chance per millisol that a person at maximum stress will have an anxiety attack. -->
	<!-- See medical complaint: "Anxiety Attack" in medical.xml. -->
	<!-- Note: 1 millisol = 88.77 seconds -->
	<!-- Default: .01 -->
	<stress-breakdown-chance value=".01" />

	<!-- The average percentage of males to total population in the simulation. -->
	<!-- Default 50 (equal numbers of males and females) -->
	<gender-male-percentage value="50.0" />

	<!-- The average percentages of the 16 MBTI (Myers-Briggs Type Indicator) personality types among settlers. -->
	<!-- Myers-Briggs Type Indicator: http://www.wikipedia.org/wiki/MBTI -->
	<!-- Note: The total percentage for all personality types must equal 100%. -->
	<!-- TODO: Find percentage statistics appropriate for Martian settlers, perhaps statistics studies of scientists, -->
	<!-- engineers or computer programmers. -->
	<personality-types>
		<mbti type="ISTP" percentage="3.0" />
		<mbti type="ISTJ" percentage="19.0" />
		<mbti type="ISFP" percentage="2.0" />
		<mbti type="ISFJ" percentage="8.0" />
		<mbti type="INTP" percentage="6.0" />
		<mbti type="INTJ" percentage="7.0" />
		<mbti type="INFP" percentage="6.0" />
		<mbti type="INFJ" percentage="5.0" />
		<mbti type="ESTP" percentage="2.0" />
		<mbti type="ESTJ" percentage="13.0" />
		<mbti type="ESFP" percentage="2.0" />
		<mbti type="ESFJ" percentage="8.0" />
		<mbti type="ENTP" percentage="4.0" />
		<mbti type="ENTJ" percentage="3.0" />
		<mbti type="ENFP" percentage="7.0" />
		<mbti type="ENFJ" percentage="5.0" />
	</personality-types>

	<!-- List of person names -->
	<person-name-list>

		<person-name value="Aaron Wolfe" gender="male" />
		<person-name value="Adelina Shaneyfelt" gender="female" />
		<person-name value="Adrian Chan" gender="male" />
		<person-name value="Aki Sashava" gender="female" />
		<person-name value="Al Haldemann" gender="male" />
		<person-name value="Alene Spagnola" gender="female" />
		<person-name value="Alessandra Kucharski" gender="female" />
		<person-name value="Alex Krol" gender="male" />
		<person-name value="Alexandria Luciano" gender="female" />
		<person-name value="Alison Tom" gender="female" />
		<person-name value="Allan Schwister" gender="male" />
		<person-name value="Allison Nowakowski" gender="female" />
		<person-name value="Alvina Hosack" gender="female" />
		<person-name value="Amy Lentz" gender="female" />
		<person-name value="Anna Harmon" gender="female" />
		<person-name value="Anson Nichols" gender="male" />
		<person-name value="Anthony Holmgren" gender="male" />
		<person-name value="Barb Follman" gender="female" />
		<person-name value="Barry Evans" gender="male" />
		<person-name value="Bella Rollie" gender="female" />
		<person-name value="Beth Miller" gender="female" />
		<person-name value="Beth Wilkins" gender="female" />
		<person-name value="Bill Hensley" gender="male" />
		<person-name value="Bill Krushas" gender="male" />
		<person-name value="Boris Debic" gender="male" />
		<person-name value="Brian Cody" gender="male" />
		<person-name value="Brian Donovan" gender="male" />
		<person-name value="Bruce Franke" gender="male" />
		<person-name value="Candida Brandner" gender="female" />
		<person-name value="Carla Deprey" gender="female" />
		<person-name value="Carlita Voytek" gender="female" />
		<person-name value="Cathrine Boria" gender="female" />
		<person-name value="Cathrine Crafford" gender="female" />
		<person-name value="Cathrine Troop" gender="female" />
		<person-name value="Chamal Perera" gender="male" />
		<person-name value="Charla Padmore" gender="female" />
		<person-name value="Charles Emery" gender="male" />
		<person-name value="Charles Kwiatkowski" gender="male" />
		<person-name value="Charlie Elston" gender="male" />
		<person-name value="Cheryl Halvorson" gender="female" />
		<person-name value="Chris Sundberg" gender="male" />
		<person-name value="Clair Steele" gender="female" />
		<person-name value="Colleen Lane" gender="female" />
		<person-name value="Connie Carrol" gender="female" />
		<person-name value="Craig Jeffords" gender="male" />
		<person-name value="Criselda Kendzierski" gender="female" />
		<person-name value="Dale Morrell" gender="male" />
		<person-name value="Dalen Kruse" gender="male" />
		<person-name value="Dalia Huddleson" gender="female" />
		<person-name value="Dan Folker" gender="male" />
		<person-name value="Daniel Frankowiak" gender="male" />
		<person-name value="Daniel Thomas" gender="male" />
		<person-name value="Daniela Eisenbeisz" gender="female" />
		<person-name value="David Blundon" gender="male" />
		<person-name value="David Coen" gender="male" />
		<person-name value="David Kern" gender="male" />
		<person-name value="David Ksiciski" gender="male" />
		<person-name value="Dawn Tucker" gender="female" />
		<person-name value="Dean Gluege" gender="male" />
		<person-name value="Denise Gregory" gender="female" />
		<person-name value="Dima Stepanchuk" gender="male" />
		<person-name value="Don Allen" gender="male" />
		<person-name value="Donna Hanson" gender="female" />
		<person-name value="Dorothy Piatek" gender="female" />
		<person-name value="Doug Armstrong" gender="male" />
		<person-name value="Douglas McMartin" gender="male" />
		<person-name value="Dushan Novakovich" gender="male" />
		<person-name value="Eddie Hintz" gender="male" />
		<person-name value="Edgar Crisostomo" gender="male" />
		<person-name value="Edward Bliese" gender="male" />
		<person-name value="Elizabeth Marshell" gender="female" />
		<person-name value="Ellan Schadegg" gender="female" />
		<person-name value="Ellie Rochel" gender="female" />
		<person-name value="Elmer Brow" gender="male" />
		<person-name value="Enrique Deorbeta" gender="male" />
		<person-name value="Eric McGuire" gender="male" />
		<person-name value="Erinn Thayne" gender="female" />
		<person-name value="Ernest Coletti" gender="male" />
		<person-name value="Evelyn Clinton" gender="female" />
		<person-name value="Evelyn Garcia" gender="female" />
		<person-name value="Fae Glaza" gender="female" />
		<person-name value="Frank Alioto" gender="male" />
