=== mars-sim/mars-sim/mars-sim-core/src/main/resources/conf/dtd/resources.dtd
<!ELEMENT resource-list (resource*)>
<!ELEMENT resource (#PCDATA)>
<!ATTLIST resource name CDATA #REQUIRED>
<!ATTLIST resource phase (solid|liquid|gas) #REQUIRED>
<!ATTLIST resource life-support (true|false) #REQUIRED>

=== mars-sim/mars-sim/mars-sim-core/src/main/resources/conf/resources.xml
<?xml version="1.0" encoding="UTF-8"?>

<!DOCTYPE resource-list SYSTEM "conf/dtd/resources.dtd">

<!-- List of all amount resources in the simulation. -->
<resource-list>

	<!-- Potable water -->
	<!-- name - the name of the resource. -->
	<!-- phase - the normal phase of the resource as used. -->
	<!--         Possible values: "solid", "liquid" or "gas" -->
	<!-- life-support - Is the resource used for life support? -->
	<!-- edible - Is the resource edible? -->

	<resource name="Food" phase="solid" life-support="true" edible="true">Represents general freeze dried food.</resource>
	<resource name="Ice" phase="solid">Ice-rich permafrost soil</resource>
	<resource name="Water" phase="liquid" life-support="true">potable water</resource>

	<resource name="Soil" phase="solid" life-support="true">Soil is the mixture of minerals, organic matter, gases, liquids, and the myriad of organisms that together support plant life.</resource>

<!-- Wastes -->
	<resource name="Compost" phase="solid" life-support="true">Organic waste consists of decaying food waste and crop remains. </resource>
	<resource name="Crop Waste" phase="solid" life-support="true">Organic waste from a dead crop or inedible biomass after harvest. </resource>

	<resource name="E-Waste" phase="solid" life-support="true">Electronic waste comprises discarded electronic devices, circuit boards and scrap components.</resource>
	<resource name="Food Waste" phase="solid" life-support="true">Organic waste from leftover or expired food. </resource>
	<resource name="Manure" phase="solid" life-support="true">Human feces</resource>

	<resource name="Solid Waste" phase="solid" life-support="true">Solid waste predominantly is any garbage, refuse or rubbish generated in settlement. It can be converted into other wastes.</resource>
	<resource name="Toxic Waste" phase="solid" life-support="true">Toxic waste consists of biomedical waste, radioactive waste, hazardous material that require special handling </resource>

	<resource name="Waste Water" phase="liquid">Sewage water can be used as crop fertilizer.</resource>

<!--	<resource name="Non-recyclable Waste" phase="solid" life-support="true">The "compacted" waste that cannot be recycled or broken down into other resources, as limited by the level of technology available to the settlement. </resource>
-->

<!-- Gas Resources -->
	<resource name="Carbon Dioxide" phase="gas" />
	<resource name="Carbon Monoxide" phase="gas" />
	<resource name="Ethylene" phase="gas" />
	<resource name="Hydrogen" phase="gas" />
	<resource name="Methane" phase="gas" />
	<resource name="Nitrogen" phase="gas"> N2 is an odorless gas </resource>
	<resource name="Oxygen" phase="gas" life-support="true" />	
	<resource name="Chlorine" phase="gas"/>

<!-- Cooking Condiment -->
	<resource name="Baking Powder" phase="solid" edible="true">Baking powder contains sodium bicarbonate as well as the acidifying agent (cream of tartar), and also a drying agent (usually starch). </resource>	
	<resource name="Epsom Salt" phase="solid" edible="true">Magnesium Sulfate as bath salt to soothe sore muscles or for gardeners to improve crops. </resource>
	<resource name="Sodium Hypochlorite" phase="solid" >For sanitization of Soybean.</resource>
	<resource name="Table Salt" phase="solid" edible="true">Food Grade Salt, is the common name for the substance sodium chloride (NaCI), which occurs in the form of transparent cubic crystals. </resource>
	<resource name="Yeast" phase="solid" edible="true">For making bread.</resource>
	
<!-- Soybean-derived food items -->
	<resource name="Okara" phase="solid" edible="true">The Soy Pulp consisting of insoluble parts of the soybean which
		 after pureed Soybean are filtered in the production of soymilk and tofu.</resource>
	<resource name="Soybean Ash" phase="solid" edible="true">Soybean extract composed of mainly Potassium, Phosphorus, Magnesium, and Calcium.</resource>
	<resource name="Soybean Oil" phase="liquid" edible="true">Oil derived from Soybean.</resource>
	<resource name="Soymilk" phase="liquid" edible="true">Plant milk produced by soaking dry Soybean and grinding them with water.</resource>
	<resource name="Soy Fiber" phase="solid" edible="true">Light yellow, silky protein Soybean fiber .</resource>
	<resource name="Soy Flour" phase="solid" edible="true">Flour made from ground Soybean.</resource>
	<resource name="Soy Protein" phase="solid">Protein extract derived from Soybean.</resource>
	<resource name="Soy Sprout" phase="solid" edible="true">Sprouted Soybean.</resource>
	<resource name="Tofu" phase="solid" edible="true">Tofu made of Okara from Soybean.</resource>
	
	
<!-- Food items derived from crop harvest -->
	<resource name="Blueberry Muffin" phase="solid" edible="true"></resource>	
	<resource name="Brown Rice" phase="solid" edible="true"></resource>
	<resource name="Cane Fiber" phase="solid" edible="true">Fiber processed from Sugarcane.</resource>
	<resource name="Cranberry Juice" phase="solid" edible="true">Baking powder contains sodium bicarbonate as well as the acidifying agent (cream of tartar), and also a drying agent (usually starch). </resource>	
	<resource name="Cranberry Sauce" phase="solid" edible="true">Sauce or relish made from Cranberries</resource>	
	<resource name="Fiber Cloth" phase="solid" >Cloth made from Soy Fiber and Cane Fiber.</resource>
	<resource name="French Fries" phase="solid" edible="true">French fries made from potatoes.</resource>
	<resource name="Garlic Oil" phase="liquid" edible="true">Oil pressed from Garlic.</resource>
	<resource name="Granola Bar" phase="solid" edible="true">A popular breakfast food and snack food consisting of puffed grain, rolled oats, nuts, honey, dried fruits</resource>
	<resource name="Honey" phase="liquid" edible="true">Honey extracted from bee hives</resource>	
	<resource name="Peanut Butter" phase="solid" edible="true"></resource>
	<resource name="Peanut Oil" phase="liquid" edible="true"></resource>
	<resource name="Quinoa Sprout" phase="solid" edible="true">Sprouts from Quinoa</resource>
	<resource name="Rice Noodle" phase="solid" edible="true">Noodle made of Rice Flour.</resource>
	<resource name="Rice Flour" phase="solid" edible="true">Flour made from White Rice. </resource>
	<resource name="Rice Vinegar" phase="liquid" edible="true">Rice vinegar is more popular in the cuisines of East and Southeast Asia. It is available in "white" (light yellow), red, and black varieties.</resource>
	<resource name="Roasted Peanut" phase="solid" edible="true"></resource>
	<resource name="Sesame Oil" phase="liquid" edible="true">Oil pressed from Sesame Seeds.</resource>
	<resource name="Soy Sauce" phase="liquid" edible="true">Made from fermented soybeans</resource>
	<resource name="Sugarcane Juice" phase="liquid" edible="true">Juice made from Sugarcane</resource>
	<resource name="Sugar" phase="solid" edible="true">Sugar processed from Sugarcane.</resource>
	<resource name="Veggie Patty" phase="solid" edible="true">Made of textured vegetable protein (like soy), legumes (beans), tofu, nuts, mushrooms, or grains or seeds, like wheat and flax. </resource>
	<resource name="Wheat Noodle" phase="solid" edible="true">Noodle made of Wheat Flour.</resource>
	<resource name="Wheat Flour" phase="solid" edible="true">Flour made from wheat kernel.</resource>
	<resource name="Wheat Bun" phase="solid" edible="true">fluffy Buns for holding Veggie Patty.</resource>
	<resource name="Wheat Bread" phase="solid" edible="true">Loaves of Bread for making sandwiches. </resource>
	<resource name="White Bread" phase="solid" edible="true">French bread or loaves of bread made from flour. </resource>
	<resource name="White Bun" phase="solid" edible="true">French bread or loaves of bread made from flour. </resource>	
	<resource name="White Rice" phase="solid" edible="true"></resource>

<!-- Crop Produce -->
	<resource name="Blueberry" phase="solid" edible="true"></resource>
	<resource name="Cabbage" phase="solid" edible="true"></resource>
	<resource name="Carrot" phase="solid" edible="true"></resource>
	<resource name="Celery" phase="solid" edible="true"></resource>
	<resource name="Cranberry" phase="solid" edible="true"></resource>	
	<resource name="Garlic" phase="solid" edible="true"></resource>
	<resource name="Ginger" phase="solid" edible="true"></resource>
	<resource name="Green Onion" phase="solid" edible="true"></resource>
	<resource name="Kidney Bean" phase="solid" edible="true"></resource>
	<resource name="Lettuce" phase="solid" edible="true"></resource>
	<resource name="Peas" phase="solid" edible="true"></resource>
	<resource name="Peanut" phase="solid" edible="true"></resource>
	<resource name="Potato" phase="solid" edible="true"></resource>
	<resource name="Quinoa" phase="solid" edible="true">A nutritious grain having most amino acids</resource>
	<resource name="Rice" phase="solid" edible="true"></resource>
	<resource name="Sesame" phase="solid" edible="true">Seeds from sesame plant.</resource>
	<resource name="Soybean" phase="solid" edible="true">Soybean seeds.</resource>
	<resource name="Strawberry" phase="solid" edible="true"></resource>
	<resource name="Sugarcane" phase="solid" edible="true"></resource>
	<resource name="Swiss Chard" phase="solid" edible="true"></resource>
	<resource name="Tomato" phase="solid" edible="true"></resource>
	<resource name="Wheat" phase="solid" edible="true">Wheat Kernels are seeds harvested from wheat crop. 
	The kernel is the whole grain, made up of 3 edible parts – bran, germ, and endosperm – protected by an inedible husk </resource>
	<resource name="White Onion" phase="solid" edible="true"></resource>	
	

<!-- Chemical or Mineral Compounds -->	
	<resource name="Aluminum Oxide" phase="solid" />
	<resource name="Ammonia" phase="solid"> NH3+ is an essential nutrient for plants</resource>
	<resource name="Calcium Carbonate" phase="solid" />
	<resource name="Gypsum" phase="solid" />
	<resource name="Iron Oxide" phase="solid">also known as rust</resource>
