=== mars-sim/mars-sim/mars-sim-core/src/main/resources/conf/dtd/vehicles.dtd
<!ELEMENT vehicle-configuration (vehicle*, rover-name-list)>
<!ELEMENT vehicle (description?, drivetrain-efficiency, base-speed, 
empty-mass, crew-size?, cargo?, part-attachment?, sickbay?, lab?, 
airlock?, activity?)>
<!ATTLIST vehicle type CDATA #REQUIRED>
<!ATTLIST vehicle width CDATA #REQUIRED>
<!ATTLIST vehicle length CDATA #REQUIRED>
<!ELEMENT description (#PCDATA)>
<!ELEMENT drivetrain-efficiency EMPTY>
<!ATTLIST drivetrain-efficiency value CDATA #REQUIRED>
<!ELEMENT base-speed EMPTY>
<!ATTLIST base-speed value CDATA #REQUIRED>
<!ELEMENT empty-mass EMPTY>
<!ATTLIST empty-mass value CDATA #REQUIRED>
<!ELEMENT crew-size EMPTY>
<!ATTLIST crew-size value CDATA #REQUIRED>
<!ELEMENT cargo (capacity*)>
<!ATTLIST cargo total-capacity CDATA #REQUIRED>
<!ELEMENT capacity EMPTY>
<!ATTLIST capacity resource CDATA #REQUIRED>
<!ATTLIST capacity value CDATA #REQUIRED>
<!ELEMENT part-attachment (part+)>
<!ATTLIST part-attachment number-slots CDATA #REQUIRED>
<!ELEMENT part EMPTY>
<!ATTLIST part name CDATA #REQUIRED>
<!ELEMENT sickbay EMPTY>
<!ATTLIST sickbay tech-level CDATA #REQUIRED>
<!ATTLIST sickbay beds CDATA #REQUIRED>
<!ELEMENT lab (tech-specialty+)>
<!ATTLIST lab tech-level CDATA #REQUIRED>
<!ELEMENT tech-specialty EMPTY>
<!ATTLIST tech-specialty value CDATA #REQUIRED>
<!ELEMENT airlock EMPTY>
<!ATTLIST airlock xloc CDATA #REQUIRED>
<!ATTLIST airlock yloc CDATA #REQUIRED>
<!ATTLIST airlock interior-xloc CDATA #REQUIRED>
<!ATTLIST airlock interior-yloc CDATA #REQUIRED>
<!ATTLIST airlock exterior-xloc CDATA #REQUIRED>
<!ATTLIST airlock exterior-yloc CDATA #REQUIRED>
<!ELEMENT activity (activity-spot+)>
<!ELEMENT activity-spot EMPTY>
<!ATTLIST activity-spot type CDATA #REQUIRED>
<!ATTLIST activity-spot xloc CDATA #REQUIRED>
<!ATTLIST activity-spot yloc CDATA #REQUIRED>
<!ELEMENT rover-name-list (rover-name*)>
<!ELEMENT rover-name EMPTY>
<!ATTLIST rover-name value CDATA #REQUIRED>

=== mars-sim/mars-sim/mars-sim/mars-sim-core/src/main/resources/conf/vehicles.xml
<?xml version="1.0" encoding="UTF-8"?>

<!DOCTYPE vehicle-configuration SYSTEM "conf/dtd/vehicles.dtd">
<vehicle-configuration>

	<vehicle type="Explorer Rover" width="3.5" length="8.0">
		<description>A rover for collecting rock samples from remote sites and ice prospecting.</description>

		<!-- The fuel efficiency of the rover (km/kg) (required) -->
		<!-- Default: 2.0 -->
		<fuel-efficiency value="2.0" />

		<!-- Base speed of rover (km/hr) (required) -->
		<!-- Default: 30.0 -->
		<base-speed value="30.0" />

		<!-- Empty mass of rover (kg) (required) -->
		<!-- Default: 10000.0 -->
		<empty-mass value="10000.0" />

		<!-- The crew size of an rover -->
		<!-- Default: 4 -->
		<crew-size value="4" />

		<!-- Cargo capacity list -->
		<!-- total-capacity: total cargo capacity of rover. (kg) -->
		<!-- Default: 5800.0 -->
		<cargo total-capacity="5800.0">
 
			<!-- The methane cargo capacity of the rover (kg) -->
			<!-- See resources.txt -->
			<!-- Default: 1600.0 -->
			<capacity resource="Methane" value="1600.0" />

			<!-- The oxygen cargo capacity of the rover (kg) -->
			<!-- See resources.txt -->
			<!-- Default: 140.0 -->
			<capacity resource="Oxygen" value="140.0" />

			<!-- The water cargo capacity of the rover (kg) -->
			<!-- See resources.txt -->
			<!-- Default: 560.0 -->
			<capacity resource="Water" value="560.0" />

			<!-- The food cargo capacity of the rover (kg) -->
			<!-- See resources.txt -->
			<!-- Default: 210.0 -->
			<capacity resource="Food" value="210.0" />

			<!-- The dessert cargo capacity of the rover (kg) -->
			<!-- See resources.txt -->
			<!-- Default: 300.0 -->
			<capacity resource="Soymilk" value="300.0" />
			
			<!-- The rock samples cargo capacity of the rover (kg) -->
			<!-- See resources.txt -->
			<!-- Default: 2000.0 -->
			<!-- <capacity resource="Rock Samples" value="2000.0" /> -->

			<!-- The ice cargo capacity of the rover (kg) -->
			<!-- See resources.txt -->
			<!-- Default: 2000.0 -->
			<!-- <capacity resource="Ice" value="2000.0" /> -->

			<capacity resource="Grey Water" value="200.0" />
			<capacity resource="Black Water" value="200.0" />			
			<capacity resource="Solid Waste" value="200.0" />
			<capacity resource="Food Waste" value="200.0" />
			<capacity resource="Toxic Waste" value="200.0" />			
		</cargo>

		<!-- Sickbay -->
		<!-- Medical tech level of sickbay (see tech_level.txt) - default: 1 -->
		<!-- Number of beds in sickbay - default: 1 -->
		<sickbay tech-level="1" beds="1" />

		<!-- Lab -->
		<!-- Science tech level of lab (see tech_level.txt) - default: 1 -->
		<lab tech-level="1">
			<!-- Science tech specialty -->
			<tech-specialty value="Areology" />
			<tech-specialty value="Biology" />
		</lab>
		
		<!-- Airlock locations (optional) -->
		<!-- xloc, yloc: the relative X/Y location inside the airlock. -->
		<!-- interior-xloc, interior-yloc: the relative X/Y location inside the vehicle. -->
		<!-- exterior-xloc, exterior-yloc: the relative X/Y location outside the vehicle. -->
		<airlock xloc="-1.25" yloc="0.0" interior-xloc="-.75" interior-yloc="0.0" exterior-xloc="-2.75" 
		exterior-yloc="0.0" />
		
		<!-- Activity spots -->
		<!-- Locations for people to perform various activities within the vehicle. -->
		<activity>
			<activity-spot type="operator" xloc=".45" yloc="2.7" />
			<activity-spot type="passenger" xloc="-.45" yloc="2.7" />
			<activity-spot type="passenger" xloc=".45" yloc="1.7" />
			<activity-spot type="passenger" xloc="-.45" yloc="1.7" />
			<activity-spot type="sickbay" xloc="-.6" yloc="-.2" />
			<activity-spot type="lab" xloc=".25" yloc=".3" />
		</activity>

	</vehicle>

	<!-- Transport rover -->
	<vehicle type="Transport Rover" width="3.5" length="9.5">
		<description>A rover for transporting people from one settlement to another.</description>
		<fuel-efficiency value="2.0" />
		<base-speed value="30.0" />
		<empty-mass value="10000.0" />
		<crew-size value="8" />
		<cargo total-capacity="7300.0">
			<capacity resource="Methane" value="2000.0" />
			<capacity resource="Oxygen" value="350.0" />
			<capacity resource="Water" value="1400.0" />
			<capacity resource="Food" value="525.0" />
			<capacity resource="Soymilk" value="300.0" />
			
			<capacity resource="Grey Water" value="200.0" />
			<capacity resource="Black Water" value="200.0" />			
			<capacity resource="Solid Waste" value="200.0" />
			<capacity resource="Food Waste" value="200.0" />
			<capacity resource="Toxic Waste" value="200.0" />			
		</cargo>
		<sickbay tech-level="3" beds="2" />
		<airlock xloc="-1.25" yloc="0.0" interior-xloc="-.75" interior-yloc="0.0" exterior-xloc="-2.75" 
		exterior-yloc="0.0" />
		<activity>
			<activity-spot type="operator" xloc=".45" yloc="4.3" />
			<activity-spot type="passenger" xloc="-.45" yloc="4.3" />
			<activity-spot type="passenger" xloc=".45" yloc="3.3" />
			<activity-spot type="passenger" xloc="-.45" yloc="3.3" />
			<activity-spot type="passenger" xloc=".45" yloc="2.3" />
			<activity-spot type="passenger" xloc="-.45" yloc="2.3" />
			<activity-spot type="passenger" xloc=".45" yloc="1.3" />
			<activity-spot type="passenger" xloc="-.45" yloc="1.3" />
			<activity-spot type="sickbay" xloc="0.0" yloc=".3" />
		</activity>
	</vehicle>
	
	<!-- Cargo rover -->
	<vehicle type="Cargo Rover" width="4.0" length="8.0">
		<description>A rover for transporting cargo from one settlement to another.</description>
		<fuel-efficiency value="2.0" />
		<base-speed value="30.0" />
		<empty-mass value="10000.0" />
		<crew-size value="2" />
		<cargo total-capacity="10300.0">
			<capacity resource="Methane" value="2000.0" />
			<capacity resource="Oxygen" value="350.0" />
			<capacity resource="Water" value="1400.0" />
			<capacity resource="Food" value="525.0" />
			<capacity resource="Soymilk" value="300.0" />
			
			<capacity resource="Grey Water" value="200.0" />
			<capacity resource="Black Water" value="200.0" />			
			<capacity resource="Solid Waste" value="200.0" />
			<capacity resource="Food Waste" value="200.0" />
			<capacity resource="Toxic Waste" value="200.0" />
		</cargo>
		<sickbay tech-level="1" beds="1" />
		<airlock xloc="-1.5" yloc="0.0" interior-xloc="-1.0" interior-yloc="0.0" exterior-xloc="-3.0" 
		exterior-yloc="0.0" />
		<activity>
			<activity-spot type="operator" xloc=".5" yloc="2.9" />
			<activity-spot type="passenger" xloc="-.5" yloc="2.9" />
			<activity-spot type="sickbay" xloc="0.0" yloc="1.9" />
		</activity>
	</vehicle>

	<!-- Light Utility Vehicle -->
	<vehicle type="Light Utility Vehicle" width="1.7" length="2.55">
		<description>A small, unpressurized, one crew utility vehicle with attachable parts.</description>
		<fuel-efficiency value="0.0" />
		<base-speed value="0.0" />
		<empty-mass value="300.0" />
		<crew-size value="1" />
		<cargo total-capacity="400.0" />
		<part-attachment number-slots="2">
            <part name="bulldozer blade" />
			<part name="pneumatic drill" />
			<part name="backhoe" />
			<part name="soil compactor" />
			<part name="drilling rig" />
			<part name="crane boom" />
		</part-attachment>
		<activity>
			<activity-spot type="operator" xloc="0.0" yloc=".13" />
		</activity>
	</vehicle>
	
	<!-- remote controlled prospecting rover
	<vehicle type="remote controlled prospector" width="1.5" length="2.5">
		<description>used for automatic mineral prospecting</description>
		<fuel-efficiency value="1.0" />
		<base-speed value="12.0" />
		<empty-mass value="250.0" />
		<crew-size value="0" />
		<cargo total-capacity="500.0">
			<capacity resource="methane" value="100.0" />			
		</cargo>
	</vehicle>-->
<!--
	<vehicle type="rc dirigible" width="5.0" length="15.0">
		<description>
			remote controlled lighter-than-air craft for use
			in atmospheric research or as communications relay.
			can only function in a certain range of temperature
			and air pressure.
		</description>
	</vehicle>
-->
	<!-- low mars orbit atmosphere space craft
	<vehicle type="sounding rocket" width="0.5" length="3.0" >
		<description>
			a small rocket for atmospheric research
			or for delivering payloads to surface
			locations by hard landing
		</description>
		<fuel-efficiency value="1.0"/>
		<base-speed value="10.0" />
		<empty-mass value="200.0"/>
		<crew-size value="0"/>
		<cargo total-capacity="500.0">
			<capacity resource="oxygen" value="150"/>
			<capacity resource="hydrogen" value="150.0"/>
		</cargo>
		<part-attachment number-slots="1">
			<part name="satellite dish"/>
			<part name="algae tank"/>
		</part-attachment>
	</vehicle>
-->
	<!-- List of rover names -->
	<rover-name-list>		

		<rover-name value="Dune Drifter" />
		<rover-name value="Oasis" />
		<rover-name value="Sun Dancer" />
		<rover-name value="Desert Fox" />
		<rover-name value="Serenity" />
		<rover-name value="Gypsea" />
		<rover-name value="Martian Cloud" />	
		<rover-name value="Sand Spirit" />
		<rover-name value="Dust Sprite" />
		<rover-name value="Phobos Drifter" />
		<rover-name value="Osprey" />
		<rover-name value="Dune Runner" />
		<rover-name value="Wind Runner" />
		<rover-name value="Sand Dancer" />	
		<rover-name value="Nomad" />
		<rover-name value="Spice Trader" />
		<rover-name value="Solitude" />
		<rover-name value="Dust Storm" />
		<rover-name value="Martian Escape" />
		<rover-name value="Odyssey" />
		<rover-name value="Deimos Tide" />	
		<rover-name value="Red Mariner" />
		<rover-name value="Shooting Star" />
		<rover-name value="Dust Devil" />
		<rover-name value="Desert Star" />
		<rover-name value="Windstorm" />
		<rover-name value="Drift Wood" />
		<rover-name value="Desertfarer" />
		<rover-name value="Dream Chaser" />	
		<rover-name value="Bedouin" />	
		<rover-name value="Fremen Wanderer" />
		<rover-name value="Beagle IV" />	
		<rover-name value="Firefly" />
		<rover-name value="Desert Pearl" />
		<rover-name value="Princess of the Sands" />
		<rover-name value="Ridge Runner" />
		<rover-name value="Desert Rose" />
		<rover-name value="Crater Crab" />
