=== mars-sim/mars-sim/mars-sim-core/src/main/resources/xml/country/country.xsd
<?xml version="1.0" encoding="UTF-8" ?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">

	<!-- 
		Note: 
		1. GDP, PPP, and population are in millions.
		2. GDP-growth is in percentage.
	-->
	
    <xs:element name="GDP">
        <xs:complexType>
            <xs:attribute name="value" type="xs:string"/>
        </xs:complexType>
    </xs:element>
    
    <xs:element name="PPP">
        <xs:complexType>
            <xs:attribute name="value" type="xs:string"/>
        </xs:complexType>
    </xs:element>

    <xs:element name="GDP-growth">
        <xs:complexType>
            <xs:attribute name="value" type="xs:string"/>
        </xs:complexType>
    </xs:element>
    
    <xs:element name="population">
        <xs:complexType>
            <xs:attribute name="value" type="xs:string"/>
        </xs:complexType>
    </xs:element>
    
    <xs:element name="last-name">
        <xs:complexType>
            <xs:attribute name="value" type="xs:string"/>
        </xs:complexType>
    </xs:element>

    <xs:element name="first-name">
        <xs:complexType>
            <xs:attribute name="value" type="xs:string"/>
            <xs:attribute name="gender" type="xs:string"/>
        </xs:complexType>
    </xs:element>

    <xs:element name="characteristics">
        <xs:complexType>
	        <xs:attribute name="median-age-male" type="xs:string"/>
    	    <xs:attribute name="median-age-female" type="xs:string"/>
            <xs:attribute name="average-male-height" type="xs:string"/>
            <xs:attribute name="average-female-height" type="xs:string"/>
            <xs:attribute name="average-male-weight" type="xs:string"/>
            <xs:attribute name="average-female-weight" type="xs:string"/>
        </xs:complexType>
    </xs:element>

    <xs:element name="country">
        <xs:complexType>
            <xs:sequence>
				<!-- Note: 
					1. Economics Data referenced from
					 https://www.worldometers.info/gdp/gdp-by-country/ 
					 https://www.investopedia.com/insights/worlds-top-economies/
					 https://en.wikipedia.org/wiki/List_of_countries_by_GDP_(nominal)
					 https://en.wikipedia.org/wiki/List_of_countries_by_GDP_(PPP)
					2. When choosing GDP and PPP, do not use IMF or CIA data set, 
					   use the 'World Bank' data set
					   
					 -->
				 <xs:element name="economics-data">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element ref="GDP" minOccurs="1" maxOccurs="1"/>
                            <xs:element ref="PPP" minOccurs="1" maxOccurs="1"/>
                            <xs:element ref="population" minOccurs="1" maxOccurs="1"/>
                            <xs:element ref="GDP-growth" minOccurs="1" maxOccurs="1"/>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
                <xs:element ref="characteristics" minOccurs="0" maxOccurs="1"/>
                <xs:element name="first-name-list">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element ref="first-name" minOccurs="1" maxOccurs="unbounded"/>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
                <xs:element name="last-name-list">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element ref="last-name" minOccurs="1" maxOccurs="unbounded"/>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
            </xs:sequence>
            <xs:attribute name="name" type="xs:string"/>
        </xs:complexType>
    </xs:element>
</xs:schema>

=== mars-sim/mars-sim/mars-sim-core/src/main/resources/xml/country/country_finland.xml
<?xml version = "1.0" encoding = "UTF-8" standalone = "yes" ?>
<country xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="country.xsd"
        name="Finland">
    <first-name-list>
        <first-name value="Leo" gender="male" />
        <first-name value="Elias" gender="male" />
        <first-name value="Onni" gender="male" />
        <first-name value="Eino" gender="male" />
        <first-name value="Oliver" gender="male" />
        <first-name value="Niilo" gender="male" />
        <first-name value="Väinö" gender="male" />
        <first-name value="Eetu" gender="male" />
        <first-name value="Leevi" gender="male" />
        <first-name value="Daniel" gender="male" />

        <first-name value="Emil" gender="male" />
        <first-name value="William" gender="male" />
        <first-name value="Lucas" gender="male" />
        <first-name value="Max" gender="male" />
        <first-name value="Benjamin" gender="male" />
        <first-name value="Liam" gender="male" />
        <first-name value="Noah" gender="male" />
        <first-name value="Casper" gender="male" />
        <first-name value="Anton" gender="male" />
        <first-name value="Axel" gender="male" />

        <first-name value="Venla" gender="female" />
        <first-name value="Sofia" gender="female" />
        <first-name value="Aada" gender="female" />
        <first-name value="Aino" gender="female" />
        <first-name value="Elsa" gender="female" />
        <first-name value="Helmi" gender="female" />
        <first-name value="Emma" gender="female" />
        <first-name value="Eevi" gender="female" />
        <first-name value="Ella" gender="female" />
        <first-name value="Emilia" gender="female" />

        <first-name value="Louise" gender="female" />
        <first-name value="Alice" gender="female" />
        <first-name value="Chloé" gender="female" />
        <first-name value="Emma" gender="female" />
        <first-name value="Inès" gender="female" />
        <first-name value="Sarah" gender="female" />
        <first-name value="Jeanne" gender="female" />
        <first-name value="Anna" gender="female" />
        <first-name value="Adèle" gender="female" />
        <first-name value="Juliette" gender="female" />
    </first-name-list>
    <last-name-list>
        <!-- 10 most common Finnish surnames -->

        <last-name value="Heikkinen" />
        <last-name value="Hämäläinen" />
        <last-name value="Järvinen" />
        <last-name value="Korhonen" />
        <last-name value="Koskinen" />
        <last-name value="Laine" />
        <last-name value="Mäkelä" />
        <last-name value="Mäkinen" />
        <last-name value="Nieminen" />
        <last-name value="Virtanen" />
    </last-name-list>
</country>

=== mars-sim/mars-sim/mars-sim-core/src/main/resources/xml/country/country_greece.xml
<?xml version = "1.0" encoding = "UTF-8" standalone = "yes" ?>
<country xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="country.xsd"
 name="Greece">
    <first-name-list>
        <first-name value="Georgios" gender="male" />
        <first-name value="Ioannis" gender="male" />
        <first-name value="Konstantinos" gender="male" />
        <first-name value="Kostas" gender="male" />
        <first-name value="Dimitrios" gender="male" />
        <first-name value="Nikolaos" gender="male" />
        <first-name value="Panagiotis" gender="male" />
        <first-name value="Vasileios" gender="male" />
        <first-name value="Christos" gender="male" />
        <first-name value="Athanasios" gender="male" />
        <first-name value="Michail" gender="male" />

        <first-name value="Maria" gender="female" />
        <first-name value="Eleni" gender="female" />
        <first-name value="Aikaterini" gender="female" />
        <first-name value="Katerina" gender="female" />
        <first-name value="Vasikiki" gender="female" />
        <first-name value="Basiliki" gender="female" />
        <first-name value="Vaso" gender="female" />
        <first-name value="Sophia" gender="female" />
        <first-name value="Angeliki" gender="female" />
        <first-name value="Georgia" gender="female" />
        <first-name value="Giorgia" gender="female" />
        <first-name value="Gogo" gender="female" />
        <first-name value="Dimitra" gender="female" />
        <first-name value="Konstantina" gender="female" />
        <first-name value="Kostantina" gender="female" />
        <first-name value="Paraskevi" gender="female" />
        <first-name value="Paraskeui" gender="female" />
    </first-name-list>
    <last-name-list>
        <!-- 10 most common Greek surnames -->

        <last-name value="Angelopoulos" />
        <last-name value="Athanasiadis" />
        <last-name value="Dimitriadis" />
        <last-name value="Georgiou" />
        <last-name value="Nikolaidis" />
        <last-name value="Panagiotopoulos" />
        <last-name value="Papadakis" />
        <last-name value="Papadopoulos" />
        <last-name value="Petridis" />
        <last-name value="Vlachos" />
    </last-name-list>
</country>

=== mars-sim/mars-sim/mars-sim-core/src/main/resources/xml/country/country_switzerland.xml
<?xml version = "1.0" encoding = "UTF-8" standalone = "yes" ?>
<country xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="country.xsd"
    name="Switzerland">
    <first-name-list>
        <first-name value="Noah" gender="male" />
        <first-name value="Liam" gender="male" />
        <first-name value="Luca" gender="male" />
        <first-name value="Gabriel" gender="male" />
        <first-name value="Leon" gender="male" />
        <first-name value="David" gender="male" />
        <first-name value="Matteo" gender="male" />
        <first-name value="Elias" gender="male" />
        <first-name value="Louis" gender="male" />
        <first-name value="Levin" gender="male" />



        <first-name value="Mia" gender="female" />
        <first-name value="Emma" gender="female" />
        <first-name value="Lara" gender="female" />
        <first-name value="Lena" gender="female" />
        <first-name value="Sofia" gender="female" />
        <first-name value="Mila" gender="female" />
        <first-name value="Anna" gender="female" />
        <first-name value="Elena" gender="female" />
        <first-name value="Laura" gender="female" />
        <first-name value="Lina" gender="female" />
    </first-name-list>
    <last-name-list>
        <!-- 10 most common Swiss surnames (5 Italian, 5 German) -->

        <last-name value="Bernasconi" />
        <last-name value="Bianchi" />
        <last-name value="Crivelli" />
        <last-name value="Fontana" />
        <last-name value="Galli" />
        <last-name value="Keller" />
        <last-name value="Meier" />
        <last-name value="MÃ¼ller" />
        <last-name value="Schmid" />
        <last-name value="Weber" />
    </last-name-list>
</country>

=== mars-sim/mars-sim/mars-sim-core/src/main/resources/xml/country/country_brazil.xml
<?xml version = "1.0" encoding = "UTF-8" standalone = "yes" ?>
<country xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="country.xsd"
            name="Brazil">
    <first-name-list>
        <!-- Brazil : will replace with Brazilian names -->
        <first-name value="Paulo" gender="male" />
        <first-name value="Eduardo" gender="male" />		
        <first-name value="Marcos" gender="male" />
        
        <!--http://iheartbrazil.com/brazilian-boy-names/ -->
        <first-name value="Jose" gender="male" />
        <first-name value="Joao" gender="male" />
        <first-name value="Antonio" gender="male" />
        <first-name value="Francisco" gender="male" />
        <first-name value="Carlos" gender="male" />
        <first-name value="Pedro" gender="male" />
        <first-name value="Lucas" gender="male" />
        <first-name value="Luiz" gender="male" />
                
        <first-name value="Adriano" gender="male" />
        <first-name value="Afonso" gender="male" />
        <first-name value="Alexandre" gender="male" />
        <first-name value="Andre" gender="male" />
        <first-name value="Arthur" gender="male" />
        <first-name value="Augusto" gender="male" />
        
        <first-name value="Benicio" gender="male" />
        <first-name value="Benjamim" gender="male" />
        <first-name value="Bento" gender="male" />
        <first-name value="Breno" gender="male" />
        <first-name value="Bernardo" gender="male" />
        <first-name value="Bruno" gender="male" />
        
        <first-name value="Caio" gender="male" />
        <first-name value="Carlos" gender="male" />
        <first-name value="Caua" gender="male" />
        <first-name value="Cesar" gender="male" />
        <first-name value="Cleiton" gender="male" />
        <first-name value="Claudio" gender="male" />
        <first-name value="Cristiano" gender="male" />

        <first-name value="Damiao" gender="male" />
        <first-name value="Danilo" gender="male" />
        <first-name value="Davi" gender="male" />
        <first-name value="Diego" gender="male" />
        <first-name value="Domingos" gender="male" />
        
        
        <!--http://iheartbrazil.com/brazilian-girl-names/ -->
        <first-name value="Michele" gender="female" />
        
        <first-name value="Bruna" gender="female" />
        
        <first-name value="Maria" gender="female" />
        <first-name value="Ana" gender="female" />
        <first-name value="Francisca" gender="female" />
        <first-name value="Antonia" gender="female" />
        <first-name value="Adriana" gender="female" />
        <first-name value="Juliana" gender="female" />
        <first-name value="Marcia" gender="female" />
        <first-name value="Fernanda" gender="female" />
        <first-name value="Patricia" gender="female" />
        <first-name value="Aline" gender="female" />
        
        
        <first-name value="Adriene" gender="female" />
        <first-name value="Agata" gender="female" />
        <first-name value="Alessandra" gender="female" />

        <first-name value="Amelia" gender="female" />
        <first-name value="Anita" gender="female" />
        <first-name value="Aline" gender="female" />
        <first-name value="Alzira" gender="female" />
        <first-name value="Ana" gender="female" />

        <first-name value="Analu" gender="female" />
        <first-name value="Andreia" gender="female" />
        <first-name value="Aparecida" gender="female" />
        <first-name value="Aurea" gender="female" />
        
        
        <first-name value="Beatriz" gender="female" />

        <first-name value="Belinda" gender="female" />
        <first-name value="Bethania" gender="female" />
        <first-name value="Bibiana" gender="female" />
        <first-name value="Bruna" gender="female" />
        
        <first-name value="Camila" gender="female" />

        <first-name value="Carina" gender="female" />
        <first-name value="Carla" gender="female" />
        <first-name value="Carolina" gender="female" />
        <first-name value="Cassia" gender="female" />
        <first-name value="Catarina" gender="female" />

        <first-name value="Celia" gender="female" />
        <first-name value="Cintia" gender="female" />
        <first-name value="Conceicao" gender="female" />
        <first-name value="Claudia" gender="female" />
        <first-name value="Cristiana" gender="female" />

    </first-name-list>
    <last-name-list>
        <!--http://iheartbrazil.com/brazilian-last-names/ -->
        
        <last-name value="Pontes" />
        <last-name value="Melo" />
        <last-name value="Vasconcellos" />
        
        <last-name value="Silva" />
        <last-name value="Santos" />
        <last-name value="Olveira" />
        <last-name value="Souza" />
        <last-name value="Rodrigues" />
        <last-name value="Ferreira" />
        <last-name value="Alves" />

        <last-name value="Anjos" />
        <last-name value="Assuncao" />
        <last-name value="Batista" />
        <last-name value="Santiago" />
        <last-name value="Trindade" />

        <last-name value="Graca" />
        <last-name value="Pereira" />
        <last-name value="Lima" />
        <last-name value="carvalho" />
        <last-name value="Gomes" />

        <last-name value="Costa" />
        <last-name value="Ribeiro" />
        <last-name value="Martins" />
        <last-name value="Almeida" />
        <last-name value="Lopes" />

        <last-name value="Soares" />
        <last-name value="Fernandes" />
        <last-name value="Vieira" />
        <last-name value="Barbosa" />
        <last-name value="Rocha" />

        <last-name value="Dias" />
        <last-name value="Nascimento" />
        <last-name value="Andrade" />

        <last-name value="Moreira" />
        <last-name value="Nunes" />
        <last-name value="Marques" />
        <last-name value="Machado" />
        <last-name value="Mendes" />

        <last-name value="Freitas" />
        <last-name value="Cardoso" />
        <last-name value="Ramos" />
        <last-name value="Goncalves" />
        <last-name value="Santana" />

        <last-name value="Teixeira" />
        <last-name value="Araujo" />
        <last-name value="Conceicao" />
        <last-name value="Bezerra" />
        <last-name value="Campos" />

        <last-name value="Reis" />
        <last-name value="Moraes" />
        <last-name value="Borges" />
        <last-name value="Castro" />
        <last-name value="Monteiro" />

        <last-name value="Moura" />
        <last-name value="Miranda" />
        <last-name value="Garcia" />
        <last-name value="Duarte" />
        <last-name value="Medeiros" />				
    </last-name-list>
</country>

=== mars-sim/mars-sim/mars-sim-core/src/main/resources/xml/country/country_united_kingdom.xml
<?xml version = "1.0" encoding = "UTF-8" standalone = "yes" ?>
<country xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="country.xsd"
    name="United Kingdom">
     <economics-data>
		 <GDP value="3,070,670"/>
		 <PPP value="3,656,809"/>
		 <population value="67.508,936"/>
		 <GDP-growth value="4.1"/>
	</economics-data>
	
		
    <!-- Taken from 
  	  	https://en.wikipedia.org/wiki/List_of_countries_by_median_age
    	https://www.worlddata.info/average-bodyheight.php -->
    <characteristics median-age-male="39.6" median-age-female="41.7" 
    			average-male-height="177" average-female-height="163"
	            average-male-weight="90.6" average-female-weight="77.1"/>

    <first-name-list>
		<!-- https://momlovesbest.com/british-boy-names -->
		
        <first-name value="Aidan" gender="male" />
        <first-name value="Aldis" gender="male" />
        <first-name value="Alfred" gender="male" />
        <first-name value="Alistair" gender="male" />
        <first-name value="Archibald" gender="male" />
        
		<!-- https://www.netmums.com/pregnancy/top-1000-baby-boy-names-uk -->

        <first-name value="Leo" gender="male" />
        <first-name value="Henry" gender="male" />
        <first-name value="Theodore" gender="male" />
        <first-name value="Freddie" gender="male" />
        <first-name value="Finley" gender="male" />
        
        <first-name value="Arlo" gender="male" />
        <first-name value="Lucas" gender="male" />
        <first-name value="Roman" gender="male" />
        <first-name value="Tommy" gender="male" />
        <first-name value="Isaac" gender="male" />
        
		<!-- Miscs. -->
        <first-name value="Oliver" gender="male" />
        <first-name value="Jacob" gender="male" />
        <first-name value="Charlie" gender="male" />
        <first-name value="Jack" gender="male" />
        <first-name value="Noah" gender="male" />
        
        <first-name value="Alfie" gender="male" />
        <first-name value="Oscar" gender="male" />
        <first-name value="William" gender="male" />
        <first-name value="George" gender="male" />
        <first-name value="Harry" gender="male" />

	<!-- https://www.bounty.com/pregnancy-and-birth/baby-names/top-baby-names/the-latest-top-100-boys-names-chosen-in-the-uk-this-year -->

        <first-name value="Noah" gender="male" />
        <first-name value="Theo" gender="male" />
        <first-name value="Luca" gender="male" />
        <first-name value="Arthur" gender="male" />
        <first-name value="Archie" gender="male" />
        
        <first-name value="George" gender="male" />
        <first-name value="Albie" gender="male" /> 
        <first-name value="Finley" gender="male" />
        <first-name value="Jude" gender="male" />
        <first-name value="Charlie" gender="male" />
        
        <first-name value="Elijah" gender="male" />
        <first-name value="Tommy" gender="male" />
        <first-name value="Oakley" gender="male" />
        <first-name value="Hudson" gender="male" />
        <first-name value="Rory" gender="male" />

        <first-name value="Reuben" gender="male" />
        <first-name value="Louie" gender="male" />
        <first-name value="Reggie" gender="male" />
        <first-name value="Theodore" gender="male" />
        <first-name value="Ezra" gender="male" />
        
		<!-- https://www.netmums.com/pregnancy/top-1000-baby-girl-names-uk -->
        <first-name value="Amelia" gender="female" />
        <first-name value="Olivia" gender="female" />
        <first-name value="Emily" gender="female" />
        <first-name value="Isla" gender="female" />
        <first-name value="Ava" gender="female" />
     
        <first-name value="Ivy" gender="female" />
        <first-name value="Lily" gender="female" />
        <first-name value="Florence" gender="female" />
        <first-name value="Mia" gender="female" />
        <first-name value="Willow" gender="female" />
     
        <first-name value="Rosie" gender="female" />
        <first-name value="Sophia" gender="female" />
        <first-name value="Grace" gender="female" />
        <first-name value="Daisy" gender="female" />
        <first-name value="Sienna" gender="female" />

        <first-name value="Poppy" gender="female" />
        <first-name value="Elsie" gender="female" />
        <first-name value="Ella" gender="female" />
        <first-name value="Evelyn" gender="female" />
        <first-name value="Phoebe" gender="female" />
   
        <first-name value="Jessica" gender="female" />
        <first-name value="Ella" gender="female" />
        <first-name value="Isabella" gender="female" />
        <first-name value="Poppy" gender="female" />
        <first-name value="Mia" gender="female" />
  
  		<!-- https://www.bounty.com/pregnancy-and-birth/baby-names/top-baby-names/the-latest-top-100-girls-names-chosen-in-the-uk-this-year -->
       
        <first-name value="Harper" gender="female" />
        <first-name value="Bonnie" gender="female" />
        <first-name value="Freya" gender="female" />
        <first-name value="Evie" gender="female" />    
        <first-name value="Charlotte" gender="female" />
        
        <first-name value="Willow" gender="female" />
        <first-name value="Sienna" gender="female" />
        <first-name value="Florence" gender="female" />
        <first-name value="Delilah" gender="female" />  
        <first-name value="Maisie" gender="female" />

        <first-name value="Lottie" gender="female" />
        <first-name value="Aria" gender="female" />
        <first-name value="Millie" gender="female" />
        <first-name value="Maya" gender="female" />
        <first-name value="Violet" gender="female" />
   
        <first-name value="Arabella" gender="female" />
        <first-name value="Aurora" gender="female" />
        <first-name value="Matilda" gender="female" />
        <first-name value="Sofia" gender="female" />
        <first-name value="Hallie" gender="female" />
        
        <first-name value="Maeve" gender="female" />
        <first-name value="Mabel" gender="female" />
        <first-name value="Esme" gender="female" />
        <first-name value="Ruby" gender="female" />
        <first-name value="Emily" gender="female" />
        
    </first-name-list>
    
    <last-name-list>
        <!-- 10 common UK surnames, taking into account individual countries -->

        <last-name value="Brown" />
        <last-name value="Campbell" />
        <last-name value="Davies" />
        <last-name value="Evans" />
        <last-name value="Jones" />
        
        <last-name value="Robertson" />
        <last-name value="Smith" />
        <last-name value="Taylor" />
        <last-name value="Thomson" />
        <last-name value="Wilson" />
        
        <!-- https://en.wiktionary.org/wiki/Appendix:English_surnames_(England_and_Wales) -->
        
        <last-name value="Williams" />
        <last-name value="Johnson" />
        <last-name value="Roberts" />
        <last-name value="Thompson" />
        <last-name value="Wright" />
        
        <last-name value="Walker" />
        <last-name value="White" />
        <last-name value="Edwards" />
        <last-name value="Hughes" />
        <last-name value="Green" />
        
        <last-name value="Hall" />
        <last-name value="Lewis" />
        <last-name value="Harris" />
        <last-name value="Clarke" />
        <last-name value="Patel" />
             
		<last-name value="Jackson" />
        <last-name value="Wood" />
        <last-name value="Turner" />
        <last-name value="Martin" />
        <last-name value="Cooper" />
        
        <last-name value="Hill" />
        <last-name value="Morris" />
        <last-name value="Ward" />
        <last-name value="Moore" />
        <last-name value="Clark" />
        
        <last-name value="Baker" />
        <last-name value="Harrison" />
        <last-name value="King" />
        <last-name value="Morgan" />
        <last-name value="Lee" />
             
        <last-name value="Allen" />
        <last-name value="James" />
        <last-name value="Phillips" />
        <last-name value="Scott" />
        <last-name value="Watson" />
        
        <!-- https://one-name.org/modern-british-surnames/statistics/top-surnames/england-wales/top-500-names/  From 46 to 80 -->
              
        <last-name value="Parker" />
        <last-name value="Price" />
        <last-name value="Bennett" />
        <last-name value="Young" />
        <last-name value="Griffiths" />
        
        <last-name value="Mitchell" />
        <last-name value="Kelly" />
        <last-name value="Cook" />
        <last-name value="Carter" />
        <last-name value="Richardson" />
        
        <last-name value="Bailey" />
        <last-name value="Collins" />
        <last-name value="Bell" />
        <last-name value="Shaw" />
        <last-name value="Murphy" />
             
		<last-name value="Miller" />
        <last-name value="Cox" />
        <last-name value="Richards" />
        <last-name value="Khan" />
        <last-name value="Marshall" />
        
        <last-name value="Anderson" />
        <last-name value="Simpson" />
        <last-name value="Ellis" />
        <last-name value="Adams" />
        <last-name value="Singh" />
        
        <last-name value="Begum" />
        <last-name value="Wilkinson" />
        <last-name value="Foster" />
        <last-name value="Chapman" />
        <last-name value="Powell" />
             
        <last-name value="Webb" />
        <last-name value="Rogers" />
        <last-name value="Gray" />
        <last-name value="Mason" />
        <last-name value="Ali" />             
             
    </last-name-list>
</country>

=== mars-sim/mars-sim/mars-sim-core/src/main/resources/xml/country/country_czech_republic.xml
<?xml version = "1.0" encoding = "UTF-8" standalone = "yes" ?>
<country xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="country.xsd"
    name="Czech Republic">
    <first-name-list>

        <first-name value="Jakub" gender="male" />
        <first-name value="Jan" gender="male" />
        <first-name value="Tomáš" gender="male" />
        <first-name value="David" gender="male" />
        <first-name value="Adam" gender="male" />
        <first-name value="Matyáš" gender="male" />
        <first-name value="Filip" gender="male" />
        <first-name value="Vojtěch" gender="male" />
        <first-name value="Ondřej" gender="male" />
        <first-name value="Lukáš" gender="male" />
        <first-name value="Eliška" gender="female" />
        <first-name value="Tereza" gender="female" />
        <first-name value="Anna" gender="female" />
        <first-name value="Adéla" gender="female" />
        <first-name value="Natálie" gender="female" />
        <first-name value="Sofie" gender="female" />
        <first-name value="Kristýna" gender="female" />
        <first-name value="Karolína" gender="female" />
        <first-name value="Viktorie" gender="female" />
        <first-name value="Barbora" gender="female" />
    </first-name-list>
    <last-name-list>
        <!-- 10 most common Czech surnames (male only) -->

        <last-name value="Dvořák" />
        <last-name value="Horák" />
        <last-name value="Kučera" />
        <last-name value="Novotný" />
        <last-name value="Novák" />
        <last-name value="Němec" />
        <last-name value="Procházka" />
        <last-name value="Svoboda" />
        <last-name value="Veselý" />
        <last-name value="Černý" />
    </last-name-list>
</country>
