=== mars-sim/mars-sim/mars-sim-core/src/main/resources/xml/country/country.xsd
<?xml version="1.0" encoding="UTF-8" ?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">

	<!-- 
		Note: 
		1. GDP, PPP, and population are in millions.
		2. GDP-growth is in percentage.
	-->
	
    <xs:element name="GDP">
        <xs:complexType>
            <xs:attribute name="value" type="xs:string"/>
        </xs:complexType>
    </xs:element>
    
    <xs:element name="PPP">
        <xs:complexType>
            <xs:attribute name="value" type="xs:string"/>
        </xs:complexType>
    </xs:element>

    <xs:element name="GDP-growth">
        <xs:complexType>
            <xs:attribute name="value" type="xs:string"/>
        </xs:complexType>
    </xs:element>
    
    <xs:element name="population">
        <xs:complexType>
            <xs:attribute name="value" type="xs:string"/>
        </xs:complexType>
    </xs:element>
    
    <xs:element name="last-name">
        <xs:complexType>
            <xs:attribute name="value" type="xs:string"/>
        </xs:complexType>
    </xs:element>

    <xs:element name="first-name">
        <xs:complexType>
            <xs:attribute name="value" type="xs:string"/>
            <xs:attribute name="gender" type="xs:string"/>
        </xs:complexType>
    </xs:element>

    <xs:element name="characteristics">
        <xs:complexType>
	        <xs:attribute name="median-age-male" type="xs:string"/>
    	    <xs:attribute name="median-age-female" type="xs:string"/>
            <xs:attribute name="average-male-height" type="xs:string"/>
            <xs:attribute name="average-female-height" type="xs:string"/>
            <xs:attribute name="average-male-weight" type="xs:string"/>
            <xs:attribute name="average-female-weight" type="xs:string"/>
        </xs:complexType>
    </xs:element>

    <xs:element name="country">
        <xs:complexType>
            <xs:sequence>
				<!-- Note: 
					1. Economics Data referenced from
					 https://www.worldometers.info/gdp/gdp-by-country/ 
					 https://www.investopedia.com/insights/worlds-top-economies/
					 https://en.wikipedia.org/wiki/List_of_countries_by_GDP_(nominal)
					 https://en.wikipedia.org/wiki/List_of_countries_by_GDP_(PPP)
					2. When choosing GDP and PPP, do not use IMF or CIA data set, 
					   use the 'World Bank' data set
					   
					 -->
				 <xs:element name="economics-data">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element ref="GDP" minOccurs="1" maxOccurs="1"/>
                            <xs:element ref="PPP" minOccurs="1" maxOccurs="1"/>
                            <xs:element ref="population" minOccurs="1" maxOccurs="1"/>
                            <xs:element ref="GDP-growth" minOccurs="1" maxOccurs="1"/>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
                <xs:element ref="characteristics" minOccurs="0" maxOccurs="1"/>
                <xs:element name="first-name-list">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element ref="first-name" minOccurs="1" maxOccurs="unbounded"/>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
                <xs:element name="last-name-list">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element ref="last-name" minOccurs="1" maxOccurs="unbounded"/>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
            </xs:sequence>
            <xs:attribute name="name" type="xs:string"/>
        </xs:complexType>
    </xs:element>
</xs:schema>

=== mars-sim/mars-sim/mars-sim-core/src/main/resources/xml/country/country_norway.xml
<?xml version = "1.0" encoding = "UTF-8" standalone = "yes" ?>
<country xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="country.xsd"
        name="Norway">
     <economics-data>
		 <GDP value="579,267"/>
		 <PPP value="627,017"/>
		 <population value="5.434319"/>
		 <GDP-growth value="3.28"/>
	</economics-data>
	
	<!-- Taken from 
  	  	https://en.wikipedia.org/wiki/List_of_countries_by_median_age
    	https://www.worlddata.info/average-bodyheight.php -->
    <characteristics median-age-male="38.8" median-age-female="40.2" 
    			average-male-height="180" average-female-height="166"
	            average-male-weight="89.1" average-female-weight="72.6"/>

    <first-name-list>
        <first-name value="William" gender="male" />
        <first-name value="Mathias" gender="male" />
        <first-name value="Matias" gender="male" />
        <first-name value="Oliver" gender="male" />
        <first-name value="Jakob" gender="male" />
        <first-name value="Jacob" gender="male" />
        <first-name value="Lucas" gender="male" />
        <first-name value="Lukas" gender="male" />
        <first-name value="Filip" gender="male" />
        <first-name value="Fillip" gender="male" />
        <first-name value="Philip" gender="male" />
        <first-name value="Liam" gender="male" />
        <first-name value="Aksel" gender="male" />
        <first-name value="Axel" gender="male" />
        <first-name value="Emil" gender="male" />
        <first-name value="Oskar" gender="male" />
        <first-name value="Oscar" gender="male" />


        <first-name value="Emma" gender="female" />
        <first-name value="Nora" gender="female" />
        <first-name value="Norah" gender="female" />
        <first-name value="Sara" gender="female" />
        <first-name value="Sarah" gender="female" />
        <first-name value="Sahra" gender="female" />
        <first-name value="Sofie" gender="female" />
        <first-name value="Sophie" gender="female" />
        <first-name value="Olivia" gender="female" />
        <first-name value="Sofia" gender="female" />
        <first-name value="Sophia" gender="female" />
        <first-name value="Emilie" gender="female" />
        <first-name value="Ella" gender="female" />
        <first-name value="Leah" gender="female" />
        <first-name value="Lea" gender="female" />
        <first-name value="Maja" gender="female" />
        <first-name value="Maia" gender="female" />
        <first-name value="Maya" gender="female" />
        <first-name value="Anna" gender="female" />
    </first-name-list>
    <last-name-list>
        <!-- 10 most common Norwegian surnames -->

        <last-name value="Andersen" />
        <last-name value="Hansen" />
        <last-name value="Jensen" />
        <last-name value="Johansen" />
        <last-name value="Karlsen" />
        <last-name value="Kristiansen" />
        <last-name value="Larsen" />
        <last-name value="Nilsen" />
        <last-name value="Olsen" />
        <last-name value="Pedersen" />
    </last-name-list>
</country>

=== mars-sim/mars-sim/mars-sim-core/src/main/resources/xml/country/country_france.xml
<?xml version = "1.0" encoding = "UTF-8" standalone = "yes" ?>
<country xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="country.xsd"
         name="France">
    <economics-data>
		 <GDP value="2,782,910"/>
		 <PPP value="3,769,924"/>
		 <population value="64.626628"/>
		 <GDP-growth value="2.56"/>
	</economics-data> 
 	
	<!-- Taken from 
  	  	https://en.wikipedia.org/wiki/List_of_countries_by_median_age
    	https://www.worlddata.info/average-bodyheight.php -->
    <characteristics median-age-male="42.0" median-age-female="44.7" 	
				average-male-height="178" average-female-height="164"
	            average-male-weight="79.2" average-female-weight="65.2"/>
	
    <first-name-list>
        <first-name value="Adam" gender="male" />
        <first-name value="Gabriel" gender="male" />
        <first-name value="Raphael" gender="male" />
        <first-name value="Paul" gender="male" />
        <first-name value="Louis" gender="male" />
        <first-name value="Arthur" gender="male" />
        <first-name value="Alexandre" gender="male" />
        <first-name value="Victor" gender="male" />
        <first-name value="Jules" gender="male" />
        <first-name value="Mohammed" gender="male" />

        <first-name value="Leo" gender="male" />
        <first-name value="Noah" gender="male" />
        <first-name value="Liam" gender="male" />
        <first-name value="Mael" gender="male" />
        <first-name value="Leon" gender="male" />
        <first-name value="Lucas" gender="male" />
        <first-name value="Hugo" gender="male" />
        <first-name value="Marceau" gender="male" />
        <first-name value="Gabin" gender="male" />
        <first-name value="Malo" gender="male" />
        
        <first-name value="Basile" gender="male" />
        <first-name value="Augustin" gender="male" />
        <first-name value="Gaspard" gender="male" />


        <first-name value="Louise" gender="female" />
        <first-name value="Alice" gender="female" />
        <first-name value="Chloe" gender="female" />
        <first-name value="Emma" gender="female" />
        <first-name value="Ines" gender="female" />
        <first-name value="Sarah" gender="female" />
        <first-name value="Jeanne" gender="female" />
        <first-name value="Anna" gender="female" />
        <first-name value="Adele" gender="female" />
        <first-name value="Juliette" gender="female" />
        
        <first-name value="Jade" gender="female" />
        <first-name value="Ambre" gender="female" />
        <first-name value="Alba" gender="female" />
        <first-name value="Rose" gender="female" />
        <first-name value="Romy" gender="female" />
        <first-name value="Agathe" gender="female" />
        <first-name value="Romane" gender="female" />
        <first-name value="Lily" gender="female" />
        <first-name value="Lilly" gender="female" />
        <first-name value="Elea" gender="female" />
        
        <first-name value="Mila" gender="female" />
        <first-name value="Charlotte" gender="female" />
        <first-name value="Olivia" gender="female" />
        <first-name value="Alma" gender="female" />
        
    </first-name-list>
    <last-name-list>
        <!-- 10 most common French surnames -->

        <last-name value="Bernard" />	<!-- Germanic origin meaning "brave bear" -->
        <last-name value="Dubois" />	<!-- Topographical name meaning "from the woods" -->
        <last-name value="Durand" />	<!-- From Latin Durandus, meaning "enduring" or "stubborn" -->
        <last-name value="Leroy" />		<!-- Meaning "the king" -->
        <last-name value="Martin" />	<!-- Derived from the Latin Martinus (God of War), popularized by Saint Martin of Tours -->
        <last-name value="Moreau" />	<!-- Derived from Maurellus, often referring to someone with dark skin or hair -->
        <last-name value="Petit" />		<!-- Meaning "small" or "youngest" -->
        <last-name value="Richard" />	<!-- Germanic for "strong ruler" -->
        <last-name value="Robert" />	<!-- Germanic for "bright fame" -->
        <last-name value="Thomas" />	<!-- Biblical origin meaning "twin" -->
        
        <last-name value="Lefebvre" />	<!-- Occupational name for a blacksmith (faber) -->
        <last-name value="Simon" />		<!-- Biblical origin meaning "God has heard" -->
        <last-name value="Rousseau" />	<!-- Meaning "red-haired" or "reddish" -->
        <last-name value="Faure" />		<!-- Occupational name for a blacksmith (variant of Fèvre) -->
        
        <last-name value="Michel" />	<!-- Biblical origin meaning "Who is like God?" -->
        <last-name value="Lefevre" />	<!-- Another spelling for the blacksmith surname -->
        <last-name value="Muller" />	<!-- Occupational name for a miller (common in Alsace/Moselle) -->
        <last-name value="Blanc" />		<!-- Meaning "white," often referring to hair color or complexion -->
        <last-name value="Roux" />		<!-- Meaning "red" or "red-haired" -->
        <last-name value="Laurent" />	<!-- Derived from the laurel tree, symbolizing victory -->
        
    </last-name-list>
</country>

=== mars-sim/mars-sim/mars-sim-core/src/main/resources/xml/country/country_sweden.xml
<?xml version = "1.0" encoding = "UTF-8" standalone = "yes" ?>
<country xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="country.xsd"
    name="Sweden">
    <first-name-list>

        <first-name value="William" gender="male" />
        <first-name value="Lucas" gender="male" />
        <first-name value="Liam" gender="male" />
        <first-name value="Oscar" gender="male" />
        <first-name value="Elias" gender="male" />
        <first-name value="Hugo" gender="male" />
        <first-name value="Oliver" gender="male" />
        <first-name value="Charlie" gender="male" />
        <first-name value="Axel" gender="male" />
        <first-name value="Vincent" gender="male" />

        <first-name value="Elsa" gender="female" />
        <first-name value="Alice" gender="female" />
        <first-name value="Maja" gender="female" />
        <first-name value="Saga" gender="female" />
        <first-name value="Ella" gender="female" />
        <first-name value="Lily" gender="female" />
        <first-name value="Olivia" gender="female" />
        <first-name value="Ebba" gender="female" />
        <first-name value="Wilma" gender="female" />
        <first-name value="Julia" gender="female" />
    </first-name-list>
    <last-name-list>
        <!-- 10 most common Swedish surnames -->

        <last-name value="Andersson" />
        <last-name value="Eriksson" />
        <last-name value="Gustafsson" />
        <last-name value="Johansson" />
        <last-name value="Karlsson" />
        <last-name value="Larsson" />
        <last-name value="Nilsson" />
        <last-name value="Olsson" />
        <last-name value="Persson" />
        <last-name value="Svensson" />

    </last-name-list>
</country>

=== mars-sim/mars-sim/mars-sim-core/src/main/resources/xml/country/country_romania.xml
<?xml version = "1.0" encoding = "UTF-8" standalone = "yes" ?>
<country xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="country.xsd"
            name="Romania">
    <first-name-list>
        <first-name value="Andrei" gender="male" />
        <first-name value="David" gender="male" />
        <first-name value="Alexandru" gender="male" />
        <first-name value="Gabriel" gender="male" />
        <first-name value="Mihai" gender="male" />
        <first-name value="Cristian" gender="male" />
        <first-name value="Stefan" gender="male" />
        <first-name value="Luca" gender="male" />
        <first-name value="IonuÅ£" gender="male" />
        <first-name value="Darius" gender="male" />

        <first-name value="Maria" gender="female" />
        <first-name value="Elena" gender="female" />
        <first-name value="Ioana" gender="female" />
        <first-name value="Andreea" gender="female" />
        <first-name value="Sofia" gender="female" />
        <first-name value="Alexandra" gender="female" />
        <first-name value="Antonia" gender="female" />
        <first-name value="Daria" gender="female" />
        <first-name value="Ana" gender="female" />
        <first-name value="Gabriela" gender="female" />
    </first-name-list>
    <last-name-list>
        <!-- 10 most common Romanian surnames -->

        <last-name value="Ciobanu" />
        <last-name value="Dumitru" />
        <last-name value="Gheorghe" />
        <last-name value="Matei" />
        <last-name value="Pop" />
        <last-name value="Popa" />
        <last-name value="Popescu" />
        <last-name value="Radu" />
        <last-name value="Stan" />
        <last-name value="Stoica" />
    </last-name-list>
</country>

=== mars-sim/mars-sim/mars-sim-core/src/main/resources/xml/country/country_portugal.xml
<?xml version = "1.0" encoding = "UTF-8" standalone = "yes" ?>
<country xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="country.xsd"
        name="Portugal">
    <first-name-list>
        <first-name value="João" gender="male" />
        <first-name value="Martim" gender="male" />
        <first-name value="Rodrigo" gender="male" />
        <first-name value="Santiago" gender="male" />
        <first-name value="Francisco" gender="male" />
        <first-name value="Afonso" gender="male" />
        <first-name value="Tomás" gender="male" />
        <first-name value="Miguel" gender="male" />
        <first-name value="Guilherme" gender="male" />
        <first-name value="Gabriel" gender="male" />

        <first-name value="Maria" gender="female" />
        <first-name value="Leonor" gender="female" />
        <first-name value="Matilde" gender="female" />
        <first-name value="Beatriz" gender="female" />
        <first-name value="Carolina" gender="female" />
        <first-name value="Mariana" gender="female" />
        <first-name value="Ana" gender="female" />
        <first-name value="Inês" gender="female" />
        <first-name value="Margarida" gender="female" />
        <first-name value="Sofia" gender="female" />
    </first-name-list>
    <last-name-list>
        <!-- 10 most common Portuguese surnames -->

        <last-name value="Costa" />
        <last-name value="Ferreira" />
        <last-name value="Jesus" />
        <last-name value="Martins" />
        <last-name value="Oliveira" />
        <last-name value="Pereira" />
        <last-name value="Rodrigues" />
        <last-name value="Santos" />
        <last-name value="Silva" />
        <last-name value="Sousa" />
    </last-name-list>
</country>

=== mars-sim/mars-sim/mars-sim-core/src/main/resources/xml/country/country_luxembourg.xml
<?xml version = "1.0" encoding = "UTF-8" standalone = "yes" ?>
<country xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="country.xsd"
        name="Luxembourg">
    <first-name-list>
        <first-name value="Gabriel" gender="male" />
        <first-name value="Leo" gender="male" />
        <first-name value="Luca" gender="male" />
        <first-name value="Noah" gender="male" />
        <first-name value="David" gender="male" />
        <first-name value="Tom" gender="male" />
        <first-name value="Ben" gender="male" />
        <first-name value="Fränk" gender="male" />
        <first-name value="Andy" gender="male" />
        <first-name value="Teo" gender="male" />

        <first-name value="Emma" gender="female" />
        <first-name value="Lara" gender="female" />
        <first-name value="Zoé" gender="female" />
        <first-name value="Amy" gender="female" />
        <first-name value="Sarah" gender="female" />
        <first-name value="Charlotte" gender="female" />
        <first-name value="Emily" gender="female" />
    </first-name-list>
    <last-name-list>
        <!-- 10 most common Luxembourgish surnames -->

        <last-name value="Hoffmann" />
        <last-name value="Klein" />
        <last-name value="Muller" />
        <last-name value="Reuter" />
        <last-name value="Schmit" />
        <last-name value="Schmitz" />
        <last-name value="Schroeder" />
        <last-name value="Thill" />
        <last-name value="Wagner" />
        <last-name value="Weber" />
    </last-name-list>
</country>

=== mars-sim/mars-sim/mars-sim-core/src/main/resources/xml/country/country_ireland.xml
<?xml version = "1.0" encoding = "UTF-8" standalone = "yes" ?>
<country xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="country.xsd"
    name="Ireland">
    <first-name-list>
        <first-name value="Jack" gender="male" />
        <first-name value="James" gender="male" />
        <first-name value="Daniel" gender="male" />
        <first-name value="Conor" gender="male" />
        <first-name value="SeÃ¡n" gender="male" />
        <first-name value="Adam" gender="male" />
        <first-name value="Noah" gender="male" />
        <first-name value="Michael" gender="male" />
        <first-name value="Charlie" gender="male" />
        <first-name value="Luke" gender="male" />

        <first-name value="Emily" gender="female" />
        <first-name value="Emma" gender="female" />
        <first-name value="Ava" gender="female" />
        <first-name value="Sophie" gender="female" />
        <first-name value="Amelia" gender="female" />
        <first-name value="Ella" gender="female" />
        <first-name value="Lucy" gender="female" />
        <first-name value="Grace" gender="female" />
        <first-name value="Chloe" gender="female" />
        <first-name value="Mia" gender="female" />
    </first-name-list>
    <last-name-list>
        <!-- 10 most common Irish surnames -->

        <last-name value="Byrne" />
        <last-name value="Kelly" />
        <last-name value="Murphy" />
        <last-name value="Ryan" />
        <last-name value="Smith" />
        <last-name value="Sullivan" />
        <last-name value="O'Brien" />
        <last-name value="O'Connor" />
        <last-name value="O'Neill" />
        <last-name value="Walsh" />
    </last-name-list>
</country>

=== mars-sim/mars-sim/mars-sim-core/src/main/resources/xml/country/country_estonia.xml
<?xml version = "1.0" encoding = "UTF-8" standalone = "yes" ?>
<country xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="country.xsd"
        name="Estonia">
    <first-name-list>
        <first-name value="Rasmus" gender="male" />
        <first-name value="Robin" gender="male" />
        <first-name value="Oliver" gender="male" />
        <first-name value="Maksim" gender="male" />
        <first-name value="Robert" gender="male" />
        <first-name value="Martin" gender="male" />
        <first-name value="Kaspar" gender="male" />
        <first-name value="Oskar" gender="male" />
        <first-name value="Henri" gender="male" />
        <first-name value="Markus" gender="male" />

        <first-name value="Sofia" gender="female" />
        <first-name value="Eliise" gender="female" />
        <first-name value="Maria" gender="female" />
        <first-name value="Sandra" gender="female" />
        <first-name value="Laura" gender="female" />
        <first-name value="Mia" gender="female" />
        <first-name value="Alisa" gender="female" />
        <first-name value="Milana" gender="female" />
        <first-name value="Lenna" gender="female" />
        <first-name value="Polina" gender="female" />
        <first-name value="Liisa" gender="female" />
        <first-name value="Anna" gender="female" />
        <first-name value="Emilia" gender="female" />
    </first-name-list>
    <last-name-list>
        <!-- 10 most common Estonian surnames -->

        <last-name value="Ilves" />
        <last-name value="Kask" />
        <last-name value="Koppel" />
        <last-name value="Kukk" />
        <last-name value="PÃ¤rn" />
        <last-name value="Rebane" />
        <last-name value="Saar" />
        <last-name value="Sepp" />
        <last-name value="Tamm" />
    </last-name-list>
</country>
