=== mars-sim/mars-sim/mars-sim/mars-sim-core/src/main/resources/conf/dtd/landmarks.dtd
<!ELEMENT landmark-list (landmark*)>
<!ELEMENT landmark EMPTY>
<!ATTLIST landmark name CDATA #REQUIRED>
<!ATTLIST landmark longitude CDATA #REQUIRED>
<!ATTLIST landmark latitude CDATA #REQUIRED>
<!ATTLIST landmark approvaldate CDATA #REQUIRED>
<!ATTLIST landmark diameter CDATA #REQUIRED>
<!ATTLIST landmark origin CDATA #REQUIRED>

=== mars-sim/mars-sim/mars-sim/mars-sim-core/src/main/resources/conf/landmarks.xml
<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE landmark-list SYSTEM "conf/dtd/landmarks.dtd">
  <!--Landmark coordinates from USGS Astrogeology Research Program-->
  <!--http://planetarynames.wr.usgs.gov/AdvancedSearch-->
  <!--Landmarks to be displayed in the user interface. -->
  <landmark-list>
    <landmark approvaldate="1973" diameter="43.05" latitude="5.14 S" longitude="0.05 E" name="Airy" origin="George B.; British astronomer (1801-1892)." type="AA"/>
  	<landmark approvaldate="1973" diameter="158.38" latitude="18.87 N" longitude="150.47 E" name="Albor Tholus" origin="Classical albedo feature name." type="TH"/>
  	<landmark approvaldate="1991" diameter="52.51" latitude="29.81 S" longitude="86.65 E" name="Anseris Mons" origin="From albedo feature Anseris Fons." type="MO"/>
  	<landmark approvaldate="1973" diameter="400.95" latitude="21.38 N" longitude="60.83 E" name="Antoniadi" origin="Eugène Michael; Turkish-born French astronomer (1870-1944)." type="AA"/>
  	<landmark approvaldate="1997" diameter="32.39" latitude="17.64 S" longitude="175.75 E" name="Apollinaris Tholus" origin="Albedo feature name." type="TH"/>
  	<landmark approvaldate="1973" diameter="470" latitude="8.26 S" longitude="120.09 W" name="Arsia Mons" origin="Arsia Silva-classical albedo feature name." type="MO"/>
  	<landmark approvaldate="1973" diameter="456.4" latitude="11.92 N" longitude="104.08 W" name="Ascraeus Mons" origin="Ascraeus Lacus-classical albedo feature name." type="MO"/>
  	<landmark approvaldate="1973" diameter="181.31" latitude="22.76 N" longitude="65.48 E" name="Baldet" origin="Fernand; French astronomer (1885-1964)." type="AA"/>
  	<landmark approvaldate="1973" diameter="165.23" latitude="21.89 N" longitude="7.94 W" name="Becquerel" origin="Antoine H.; French physicist (1852-1908)." type="AA"/>
  	<landmark approvaldate="1973" diameter="408.23" latitude="23.35 N" longitude="32.11 E" name="Cassini" origin="Giovanni; Italian astronomer (1625-1712)." type="AA"/>
  	<landmark approvaldate="1973" diameter="128.58" latitude="24 N" longitude="97.25 W" name="Ceraunius Tholus" origin="Classical albedo feature name." type="TH"/>
  	<landmark approvaldate="1973" diameter="301.83" latitude="48.84 S" longitude="168.83 W" name="Copernicus" origin="Nicolaus; Polish astronomer (1473-1543)." type="AA"/>
  	<landmark approvaldate="1973" diameter="176.38" latitude="56.97 S" longitude="19.15 W" name="Darwin" origin="Charles R.; British naturalist (1809-1882) and George H.; British astronomer (1845-1912)." type="AA"/>
  	<landmark approvaldate="1973" diameter="185.32" latitude="9.11 S" longitude="38.06 E" name="Dawes" origin="William R.; British astronomer (1799-1868)." type="AA"/>
  	<landmark approvaldate="1973" diameter="159.71" latitude="17.43 S" longitude="33.52 E" name="Denning" origin="William F.; British astronomer (1848-1931)." type="AA"/>
  	<landmark approvaldate="1973" diameter="401" latitude="25.02 N" longitude="147.21 E" name="Elysium Mons" origin="Classical albedo feature name." type="MO"/>
  	<landmark approvaldate="1991" diameter="4.6" latitude="35.92 N" longitude="85.13 W" name="E. Mareotis Tholus" origin="Classical albedo name." type="TH"/>
  	<landmark approvaldate="2003" diameter="88.91" latitude="44.82 S" longitude="105.18 E" name="Euripus Mons" origin="Albedo feature name." type="MO"/>
  	<landmark approvaldate="1973" diameter="173.7" latitude="25.22 N" longitude="48.28 E" name="Flammarion" origin="Camille; French astronomer (1842-1925)." type="AA"/>
  	<landmark approvaldate="1973" diameter="236.06" latitude="16.8 S" longitude="19.22 E" name="Flaugergues" origin="Honore; French astronomer (1755-1835)." type="AA"/>
  	<landmark approvaldate="1991" diameter="154.08" latitude="5.37 S" longitude="137.81 E" name="Gale" origin="Walter F.; Australian astronomer (1865-1945)." type="AA"/>
  	<landmark approvaldate="1973" diameter="223.53" latitude="50.63 S" longitude="31 W" name="Galle" origin="Johann G.; German astronomer (1812-1910)." type="AA"/>
  	<landmark approvaldate="1991" diameter="49.38" latitude="41.21 N" longitude="90.88 W" name="Gonnus Mons" origin="Classical town." type="MO"/>
  	<landmark approvaldate="1973" diameter="182.07" latitude="52.3 S" longitude="8.54 W" name="Green" origin="Nathan E.; British astronomer (1823-1899)." type="AA"/>
  	<landmark approvaldate="1976" diameter="158.12" latitude="14.53 S" longitude="175.52 E" name="Gusev" origin="Matvei M.; Russian astronomer (1826-1866)." type="AA"/>
  	<landmark approvaldate="1973" diameter="181.57" latitude="32.12 N" longitude="150.24 E" name="Hecates Tholus" origin="Classcial albedo feature name." type="TH"/>
  	<landmark approvaldate="1973" diameter="167.57" latitude="10.79 N" longitude="23.45 E" name="Henry" origin="Paul; French astronomer (1848-1905). Prosper; French astronomer (1849-1903)." type="AA"/>
  	<landmark approvaldate="1973" diameter="297.92" latitude="14.48 S" longitude="129.89 E" name="Herschel" origin="John F.; British astronomer (1792-1871); William H.; British astronomer (1738-1822)." type="AA"/>
  	<landmark approvaldate="1991" diameter="20.5" latitude="51.05 S" longitude="36.56 W" name="Horarum Mons" origin="Albedo name." type="MO"/>
  	<landmark approvaldate="Nov 25, 2009" diameter="64.9" latitude="32.06 S" longitude="140.75 E" name="Horowitz" origin="Norman H.; American biologist and geneticist (1915-2005). " type="AA"/>
  	<landmark approvaldate="1973" diameter="467.25" latitude="13.88 S" longitude="55.58 E" name="Huygens" origin="Christiaan; Dutch physicist-astronomer (1629-1695)." type="AA"/>
  	<landmark approvaldate="1991" diameter="54.53" latitude="36.05 N" longitude="94.83 W" name="Issedon Tholus" origin="Classical albedo name." type="TH"/>
  	<landmark approvaldate="1973" diameter="58.07" latitude="18.2 N" longitude="117.41 W" name="Jovis Tholus" origin="Classical albedo feature name." type="TH"/>
  	<landmark approvaldate="1973" diameter="201.67" latitude="46.19 S" longitude="19.11 E" name="Kaiser" origin="Frederick; Dutch astronomer (1808-1872)." type="AA"/>
  	<landmark approvaldate="1973" diameter="228.24" latitude="46.69 S" longitude="140.98 E" name="Kepler" origin="Johannes; German astronomer (1571-1630)." type="AA"/>
  	<landmark approvaldate="1985" diameter="296.67" latitude="29.56 S" longitude="141.54 W" name="Koval'sky" origin="M. A.; Russian astronomer (1821-1884)." type="AA"/>
  	<landmark approvaldate="1994" diameter="42.78" latitude="37.48 N" longitude="75.86 W" name="Labeatis Mons" origin="Named for albedo feature Labeatis Lacus." type="MO"/>
  	<landmark approvaldate="1973" diameter="202.22" latitude="51.96 S" longitude="81.5 W" name="Lowell" origin="Percival; American astronomer (1855-1916)." type="AA"/>
  	<landmark approvaldate="1973" diameter="221.53" latitude="50.47 N" longitude="29.34 E" name="Lyot" origin="Bernard; French astronomer (1897-1952)." type="AA"/>
  	<landmark approvaldate="1967" diameter="156.58" latitude="34.68 S" longitude="164.24 W" name="Mariner" origin="Named for Mariner IV spacecraft." type="AA"/>
  	<landmark approvaldate="1973" diameter="168.87" latitude="27.5 S" longitude="149.27 E" name="Molesworth" origin="Percy B.; British astronomer (1867-1908)." type="AA"/>
  	<landmark approvaldate="1985" diameter="198.81" latitude="0.6 N" longitude="55.21 W" name="Mutch" origin="Dr. Thomas A.; American geologist, Viking Lander Imaging Team leader (1931-1980)." type="AA"/>
  	<landmark approvaldate="1976" diameter="11.34" latitude="22.91 N" longitude="42.13 W" name="Naar" origin="Town in Egypt." type="AA"/>
  	<landmark approvaldate="1976" diameter="8.68" latitude="24.45 N" longitude="107.44 E" name="Naic" origin="Town in the Philippines." type="AA"/>
  	<landmark approvaldate="1979" diameter="6.89" latitude="41.47 N" longitude="126.84 E" name="Nain" origin="Town in Newfoundland, Canada." type="AA"/>
  	<landmark approvaldate="1979" diameter="8.03" latitude="44.99 N" longitude="122.86 E" name="Naju" origin="Town in the Republic of Korea." type="AA"/>
  	<landmark approvaldate="1982" diameter="669.63" latitude="4.89 N" longitude="33.39 E" name="Naktong Vallis" origin="Modern name for river in the Republic of Korea." type="VA"/>
  	<landmark approvaldate="Sep 14, 2006" diameter="7.26" latitude="24.73 N" longitude="35.45 W" name="Nakusp" origin="Town in British Columbia." type="AA"/>
  	<landmark approvaldate="1976" diameter="2.29" latitude="26.69 S" longitude="19.94 W" name="Nan" origin="Town in Thailand." type="AA"/>
  	<landmark approvaldate="1976" diameter="550" latitude="5.05 N" longitude="48.62 W" name="Nanedi Valles" origin="Word for &quot;planet&quot; in Sesotho, national language of Lesotho, Africa." type="VA"/>
  	<landmark approvaldate="1967" diameter="74.63" latitude="49.92 S" longitude="140.42 W" name="Nansen" origin="Fridtjof; Norwegian explorer (1861-1930)." type="AA"/>
  	<landmark approvaldate="Oct 12, 2014" diameter="87.5" latitude="25.97 S" longitude="78.03 E" name="Napo Vallis" origin="River in Ecuador." type="VA"/>
  	<landmark approvaldate="1976" diameter="25.1" latitude="27.51 S" longitude="32.84 W" name="Nardo" origin="Town in Italy." type="AA"/>
  	<landmark approvaldate="1985" diameter="442.72" latitude="4 S" longitude="60.71 E" name="Naro Vallis" origin="Ancient name for modern Neretva River, Yugoslavia." type="VA"/>
  	<landmark approvaldate="Jan 18, 2008" diameter="4.17" latitude="36.24 S" longitude="161.7 W" name="Naruko" origin="Former town in Japan." type="AA"/>
  	<landmark approvaldate="Jul 1, 2008" diameter="3.94" latitude="14.89 N" longitude="123.3 E" name="Naryn" origin="Town in Kyrgyzstan. " type="AA"/>
  	<landmark approvaldate="1976" diameter="7.47" latitude="21.25 N" longitude="30.58 W" name="Naukan" origin="Town in Russia." type="AA"/>
  	<landmark approvaldate="1976" diameter="24.86" latitude="25.89 S" longitude="23.5 W" name="Navan" origin="Town in Ireland." type="AA"/>
