=== mars-sim/mars-sim/mars-sim-core/src/main/resources/xml/scenario/scenario.xsd
<?xml version="1.0" encoding="UTF-8" ?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">

    <xs:element name="location">
        <xs:complexType>
            <xs:attribute name="coordinates" type="xs:string"/>
        </xs:complexType>
    </xs:element>

    <xs:element name="settlement">
        <xs:complexType>
            <xs:sequence>
                <xs:element ref="location" minOccurs="1" maxOccurs="unbounded"/>
            </xs:sequence>
            <xs:attribute name="name" type="xs:string"/>
            <xs:attribute name="template" type="xs:string"/>
            <xs:attribute name="crew" type="xs:string"/>
            <xs:attribute name="sponsor" type="xs:string"/>
            <xs:attribute name="persons" type="xs:integer"/>
            <xs:attribute name="robots" type="xs:integer" use="optional"/>
        </xs:complexType>
    </xs:element>

    <xs:element name="arriving-settlement">
        <xs:complexType>
            <xs:sequence>
                <xs:element ref="location" minOccurs="1" maxOccurs="unbounded"/>
            </xs:sequence>
            <xs:attribute name="name" type="xs:string"/>
            <xs:attribute name="template" type="xs:string"/>
            <xs:attribute name="arrival-in-sols" type="xs:integer"/>
            <xs:attribute name="sponsor" type="xs:string"/>
            <xs:attribute name="persons" type="xs:integer"/>
            <xs:attribute name="robots" type="xs:integer" use="optional"/>
        </xs:complexType>
    </xs:element>

    <xs:element name="scenario-configuration">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="initial-settlement-list">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element ref="settlement"  maxOccurs="unbounded"/>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
                <xs:element name="arriving-settlement-list" minOccurs="0">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element ref="arriving-settlement" minOccurs="0" maxOccurs="unbounded"/>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
            </xs:sequence>
            <xs:attribute name="name" type="xs:string"/>
            <xs:attribute name="description" type="xs:string"/>
            <xs:attribute name="max-colonies" type="xs:integer" use="optional" default="0"/>
        </xs:complexType>
    </xs:element>
</xs:schema>

=== mars-sim/mars-sim/mars-sim-core/src/main/resources/xml/scenario/scenario_default.xml
<?xml version = "1.0" encoding = "UTF-8"?>

<scenario-configuration xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="scenario.xsd"
	name="Default" description="Default Scenario">
	<initial-settlement-list>
	<!-- List of initial settlements in the simulation -->
		<!-- location coordinates= xxx N (+ve is North) xxx E (+ve is East) -->	

		<settlement name="New London" template="Phase 1-UK" persons="8" robots="4" sponsor="UKSA">
			<!-- sits between Star Base and New Seoul -->	
			<location coordinates="33.4570 144.0189" />
		</settlement>
		
		<settlement name="Tai Ping" template="Phase 1-TW" persons="8" robots="4" sponsor="TASA">
			<!-- sits between New Dubai and Foundation -->	
			<location coordinates="19.0487 145.0289" />
		</settlement>
		
		<settlement name="Catarina" template="Phase 1-BR" persons="8" robots="4" sponsor="AEB">
			<!-- sits between Zvezda and Tian Cheng -->	
			<location coordinates="25.0892 58.8805" />
		</settlement>

		<settlement name="Origin" template="Phase 2-BO" persons="8" robots="8" sponsor="BO">
			<location coordinates="6.26 -20.46" />
		</settlement>
		
		<settlement name="Arcadia" template="Phase 2-EU" persons="8" robots="8" sponsor="ESA">
			<!-- Other names available: Schiaparelli Point			
				2 landing proposed sites for ESA ExoMars: 
				(1). Hypanis Vallis at 314.0 E, 11.9 N    
			    (2). Mawrth Vallis at 342.0 E, 22.4 N
			<location longitude="342.0 E" coordinates="22.4 " />			    
			-->
			<location coordinates="24.3612 -29.7837" />
		</settlement>

		<settlement name="Hong Tian" template="Phase 2-CN" persons="8" robots="8" sponsor="CNSA">
			<location coordinates="15.9873 -47.8419" />
		</settlement>

		<settlement name="Kyocera" template="Phase 2-JP" persons="12" robots="6" sponsor="JAXA">
			<location coordinates="43.3018 -171.8967" />
		</settlement>

		<settlement name="New Seoul" template="Phase 2-KR" persons="14" robots="8" sponsor="KASA">
			<location coordinates="40.4244 -105.8939" />
		</settlement>
	
		<settlement name="New Taipei" template="Phase 3-ISRA" persons="16" robots="8" sponsor="ISRA">
			<!-- previously, longitude="20.9156 E" coordinates="0.7777 " -->
			<location coordinates="9.68 24.57" />	
		</settlement>		
				
		<settlement name="Bharatiya" template="Phase 3-IN" persons="16" robots="8" sponsor="ISRO">
			<location coordinates="26.3650 -70.9710" />
		</settlement>

		<settlement name="Star Base" template="Phase 3-SX" persons="16" robots="8" sponsor="SPACEX">
    	<!-- 52nd Lunar and Planetary Science Conference 2021 (LPI COntrib. No. 2548), 
        "SpaceX Starship Landing Sites on Mars" 2420.pdf -->   
       		<!-- PM-1 site (Elev -3.2 km) in Phelgra Montes, the 1st prime landing -->
			<location coordinates="35.23 163.95" />        		
     		<!-- AP-1site (Elev -3.9 km) in Arcadia Planitia, the 2nd prime landing -->
			<location coordinates="39.8 202.1" />       
      		<!-- AP-9 site (Elev -3.9 km) in Arcadia Planitia, the 3rd prime landing -->
			<location coordinates="40.02 203.35" />        		
     		<!-- EM-16 site (Elev -3.9 km) in Erebus Montes, the 4th prime landing -->
			<location coordinates="39.89 192.03" />
		</settlement>

		<settlement name="Von-Braun" template="Phase 1-DE" persons="8" robots="8" sponsor="DLR">
 			<!-- sits between Catarina and Arcadia --> 
			<location coordinates="17.3983 81.9044" />
		</settlement>

		<settlement name="Korolev" template="Alpha Base 1" persons="40" robots="24" sponsor="RKA">
 			<!--  An ice-filled impact crater. The ice is permanently stable because the crater acts as a natural cold trap.
 				  https://pubs.usgs.gov/publication/70029300 
 				  https://en.wikipedia.org/wiki/Korolev_(Martian_crater) 
 			--> 
			<location coordinates="72.77 164.58" />
		</settlement>

		<settlement name="Terminus" template="Alpha Base 2" crew="Alpha" persons="44" robots="24" sponsor="NASA">
			<location coordinates="-4.8051 0.0" />
		</settlement>
			
		<settlement name="Heritage" template="Hub Base" persons="52" robots="36" sponsor="MS">
			<location coordinates="15.1255 114.1535" />
		</settlement>

		<settlement name="Foundation" template="Sector Base 1" crew="Founders" persons="212" robots="84" sponsor="MS">
			<location coordinates="24.14 172.29" />
		</settlement>

	</initial-settlement-list>
	<arriving-settlement-list>
	
		<arriving-settlement name="New Madinah" template="Phase 1-SA" 
			persons="4" robots="4" sponsor="SSA" arrival-in-sols="5">
			<location coordinates="45.4157 -141.3300" />
		</arriving-settlement>
			
		<arriving-settlement name="New Dubai" template="Phase 0-AE" 
			persons="4" robots="4" sponsor="UAESA" arrival-in-sols="4">
			<location coordinates="13.5488 136.4239" />
		</arriving-settlement>	
	
		<arriving-settlement name="Halley" template="Phase 1-IT" 
			persons="8" robots="6" sponsor="ASI" arrival-in-sols="3">
			<location coordinates="22.6532 37.0579" />				 
		</arriving-settlement>
	
		<arriving-settlement name="Descartes" template="Phase 2-FR" 
			persons="16" robots="12" sponsor="CNES" arrival-in-sols="2">
			<location coordinates="56.0878 171.9375" />				 
		</arriving-settlement>
		
		<arriving-settlement name="Danube" template="Phase 2-HU" 
			persons="8" robots="8" sponsor="HSO" arrival-in-sols="1">
			<location coordinates="25.2143 95.2903" />
		</arriving-settlement>

	</arriving-settlement-list>
</scenario-configuration>
