<?xml version = "1.0" encoding = "UTF-8" standalone = "yes" ?>
<!DOCTYPE construction [
	<!ELEMENT construction (foundation-list, frame-list, building-list)>
	<!ELEMENT foundation-list (foundation*)>
	<!ELEMENT foundation (resource*, part*, vehicle*)>
	<!ATTLIST foundation name CDATA #REQUIRED>
	<!ATTLIST foundation width CDATA #REQUIRED>
	<!ATTLIST foundation length CDATA #REQUIRED>
	<!ATTLIST foundation north-south-alignment (width|length) #REQUIRED>		
	<!ATTLIST foundation base-level CDATA #REQUIRED>
	<!ATTLIST foundation constructable (true|false) #REQUIRED>
	<!ATTLIST foundation salvagable (true|false) #REQUIRED>
	<!ATTLIST foundation work-time CDATA #REQUIRED>
	<!ATTLIST foundation skill-required CDATA #REQUIRED>
	<!ELEMENT resource EMPTY>
	<!ATTLIST resource type CDATA #REQUIRED>
	<!ATTLIST resource amount CDATA #REQUIRED>
	<!ELEMENT part EMPTY>
	<!ATTLIST part type CDATA #REQUIRED>
	<!ATTLIST part number CDATA #REQUIRED>
	<!ELEMENT vehicle (attachment-part*)>
	<!ATTLIST vehicle type CDATA #REQUIRED>
	<!ELEMENT attachment-part EMPTY>
	<!ATTLIST attachment-part type CDATA #REQUIRED>
	<!ELEMENT frame-list (frame*)>
	<!ELEMENT frame (resource*, part*, vehicle*)>
	<!ATTLIST frame name CDATA #REQUIRED>
	<!ATTLIST frame width CDATA #REQUIRED>
	<!ATTLIST frame length CDATA #REQUIRED>
	<!ATTLIST frame north-south-alignment (width|length) #REQUIRED>	
	<!ATTLIST frame base-level CDATA #REQUIRED>
	<!ATTLIST frame constructable (true|false) #REQUIRED>
	<!ATTLIST frame salvagable (true|false) #REQUIRED>
	<!ATTLIST frame work-time CDATA #REQUIRED>
	<!ATTLIST frame skill-required CDATA #REQUIRED>
	<!ATTLIST frame foundation CDATA #REQUIRED>
	<!ELEMENT building-list (building*)>
	<!ELEMENT building (resource*, part*, vehicle*)>
	<!ATTLIST building name CDATA #REQUIRED>
	<!ATTLIST building width CDATA #REQUIRED>
	<!ATTLIST building length CDATA #REQUIRED>
	<!ATTLIST building north-south-alignment (width|length) #REQUIRED>		
	<!ATTLIST building base-level CDATA #REQUIRED>
	<!ATTLIST building constructable (true|false) #REQUIRED>
	<!ATTLIST building salvagable (true|false) #REQUIRED>
	<!ATTLIST building work-time CDATA #REQUIRED>
	<!ATTLIST building skill-required CDATA #REQUIRED>
	<!ATTLIST building frame CDATA #REQUIRED>
]>

<construction>

	<!-- 
	mars-sim adopts a paradigm of the construction that involves 
	3 key stages as follows : 
	
	A. FOUNDATION : 
	The Foundation stage is the first physical step in construction, where the 
	structural base of the home is established.
	
	This involves site preparation, including clearing the land, leveling the ground, 
	and sometimes excavation.
 
 	Depending on the design and soil conditions, foundations can be concrete slabs, 
 	block walls, or poured walls.
 	
	Before pouring the concrete slab, underground services like plumbing and electrical 
	conduits are often installed.
 
 	This stage is crucial as it supports the entire structure and ensures stability.

	B. FRAMING :
	Following the foundation, the Frame stage begins, where the skeleton of the house is 
	constructed.
 
 	This involves installing the structural framework for walls, floors, and the roof, 
 	using materials like timber or steel.
 
 	The frame defines the layout and shape of the home, giving a clear visual 
 	representation of the rooms and spaces.
 
 	This stage is often considered a major milestone as the home's basic structure 
 	becomes visible.

	C. BULIDING : 
	The Building stage includes the subsequent phases such as the Lock-up stage, 
	where external walls, windows, doors, and the roof are installed to make 
	the home weatherproof.
	
	This is followed by the Fixing or Fit-out stage, involving internal components like 
	electrical wiring, plumbing, insulation, and interior walls.
	
	No doubt, the final phase are Completion and Handover, which involve inspections, 
	cleaning, landscaping, testing systems, and the final walkthrough before the 
	homeowner receives the keys.	
	-->


	<foundation-list>
		<!-- work-time in sols, not millisols -->
		<foundation name="Surface Foundation 2x3" width="2.0" length="3.0" 
		 north-south-alignment="length" base-level="0"
		 constructable="true" salvagable="true" work-time="0.4" skill-required="1" >
			<resource type="concrete" amount="6.0" />
			<vehicle type="LUV" >
				<attachment-part type="bulldozer blade" />
				<attachment-part type="soil compactor" />
			</vehicle>
		</foundation>

		<foundation name="Surface Foundation 5x5" width="5.0" length="5.0"
		 north-south-alignment="length" base-level="0"
		 constructable="true" salvagable="true" work-time="0.8" skill-required="1" >
			<resource type="concrete" amount="25.0" />
			<vehicle type="LUV" >
				<attachment-part type="bulldozer blade" />
				<attachment-part type="soil compactor" />
			</vehicle>
		</foundation>

		<foundation name="Surface Foundation 7x7" width="7.0" length="7.0"
		 north-south-alignment="length" base-level="0"
		 constructable="true" salvagable="true" work-time="0.8" skill-required="1" >
			<resource type="concrete" amount="49.0" />
			<vehicle type="LUV" >
				<attachment-part type="bulldozer blade" />
				<attachment-part type="soil compactor" />
			</vehicle>
		</foundation>

		<foundation name="Surface Foundation 3x6" width="3.0" length="6.0" 
		 north-south-alignment="length" base-level="0"
		 constructable="true" salvagable="true" work-time="0.6" skill-required="1" >
			<resource type="concrete" amount="18.0" />
			<vehicle type="LUV" >
				<attachment-part type="bulldozer blade" />
				<attachment-part type="soil compactor" />
			</vehicle>
		</foundation>

		<foundation name="Surface Foundation 3x7" width="3.0" length="7.0" 
		 north-south-alignment="length" base-level="0"
		 constructable="true" salvagable="true" work-time="0.8" skill-required="1" >
			<resource type="concrete" amount="21.0" />
			<vehicle type="LUV" >
				<attachment-part type="bulldozer blade" />
				<attachment-part type="soil compactor" />
			</vehicle>
		</foundation>

		<foundation name="Surface Foundation 5x10" width="5.0" length="10.0"
		 north-south-alignment="length" base-level="0"
		 constructable="true" salvagable="true" work-time="1.2" skill-required="1" >
			<resource type="concrete" amount="50.0" />
			<vehicle type="LUV" >
				<attachment-part type="bulldozer blade" />
				<attachment-part type="soil compactor" />
			</vehicle>
		</foundation>

		<!-- surface foundation 6m_x_6m is setting for a modular frame. work-time = 3.0 -->
		<foundation name="Surface Foundation 6x6" width="6.0" length="6.0"
		 north-south-alignment="length" base-level="0"
		 constructable="true" salvagable="true" work-time="1.0" skill-required="1" >
			<resource type="concrete" amount="36.0" />
			<vehicle type="LUV" >
				<attachment-part type="bulldozer blade" />
				<attachment-part type="soil compactor" />
			</vehicle>
		</foundation>
		
		<!-- surface foundation 6m_x_9m is setting for a Modular B Frame. work-time = 3.0 -->
		<foundation name="Surface Foundation 6x9" width="9.0" length="7.0"
		 north-south-alignment="length" base-level="0"
		 constructable="true" salvagable="true" work-time="1.25" skill-required="1" >
			<resource type="concrete" amount="54.0" />
			<vehicle type="LUV" >
				<attachment-part type="bulldozer blade" />
				<attachment-part type="soil compactor" />
			</vehicle>
		</foundation>
				
		<!-- surface foundation 7m_x_9m is setting for Modular A Frame. work-time = 3.0 -->
		<foundation name="Surface Foundation 7x9" width="9.0" length="6.0"
		 north-south-alignment="length" base-level="0"
		 constructable="true" salvagable="true" work-time="1.3" skill-required="1" >
			<resource type="concrete" amount="63.0" />
			<vehicle type="LUV" >
				<attachment-part type="bulldozer blade" />
				<attachment-part type="soil compactor" />
			</vehicle>
		</foundation>

		<foundation name="Surface Foundation 9x9" width="9.0" length="9.0" 
		 north-south-alignment="length" base-level="-1"
		 constructable="true" salvagable="true" work-time="1.4" skill-required="1" >
			<resource type="concrete" amount="81.0" />
			<vehicle type="LUV" >
				<attachment-part type="bulldozer blade" />
				<attachment-part type="backhoe" />
			</vehicle>
		</foundation>

		<foundation name="Surface Foundation 8x11" width="8.0" length="11.0" 
		 north-south-alignment="length" base-level="-1"
		 constructable="true" salvagable="true" work-time="1.8" skill-required="1" >
			<resource type="concrete" amount="88.0" />
			<vehicle type="LUV" >
				<attachment-part type="bulldozer blade" />
				<attachment-part type="backhoe" />
			</vehicle>
		</foundation>

		<foundation name="Surface Foundation 12x18" width="18.0" length="12.0"
		 north-south-alignment="length" base-level="0"
		 constructable="true" salvagable="true" work-time="2.4" skill-required="1" >
			<resource type="concrete" amount="96.0" />
			<vehicle type="LUV" >
				<attachment-part type="bulldozer blade" />
				<attachment-part type="soil compactor" />
			</vehicle>
		</foundation>

		<foundation name="Subsurface Foundation 5x5x3" width="5.0" length="5.0"
		 north-south-alignment="length" base-level="-1"
		 constructable="true" salvagable="true" work-time="6.0" skill-required="1" >
			<resource type="concrete" amount="37.5" />
			<vehicle type="LUV" >
				<attachment-part type="bulldozer blade" />
				<attachment-part type="backhoe" />
			</vehicle>
		</foundation>

		<foundation name="Subsurface Foundation 6x6x3" width="6.0" length="6.0"
		 north-south-alignment="length" base-level="-1"
		 constructable="true" salvagable="true" work-time="7.0" skill-required="1" >
			<resource type="concrete" amount="54.0" />
			<vehicle type="LUV" >
				<attachment-part type="bulldozer blade" />
				<attachment-part type="backhoe" />
			</vehicle>
		</foundation>


		<foundation name="Subsurface Foundation 5x10x3" width="5.0" length="10.0"
		 north-south-alignment="length" base-level="-1"
		 constructable="true" salvagable="true" work-time="8.0" skill-required="1" >
			<resource type="concrete" amount="75.0" />
			<vehicle type="LUV" >
				<attachment-part type="bulldozer blade" />
				<attachment-part type="backhoe" />
			</vehicle>
		</foundation>

		<foundation name="Subsurface Foundation 10x10x3" width="10.0" length="10.0"
		 north-south-alignment="length" base-level="-1"
		 constructable="true" salvagable="true" work-time="10.0" skill-required="1" >
			<resource type="concrete" amount="150.0" />
			<vehicle type="LUV" >
				<attachment-part type="bulldozer blade" />
				<attachment-part type="backhoe" />
			</vehicle>
		</foundation>

		<foundation name="Ramped Subsurface Foundation 15x18x5" width="18.0" length="15.0"
		 north-south-alignment="length" base-level="-1"
		 constructable="true" salvagable="true" work-time="12.0" skill-required="1" >
			<resource type="concrete" amount="369.0" />
			<vehicle type="LUV" >
				<attachment-part type="bulldozer blade" />
				<attachment-part type="backhoe" />
			</vehicle>
		</foundation>

		<foundation name="Shallow Borehole Drilling Site" width="5.0" length="10.0"
		 north-south-alignment="length" base-level="0"
		 constructable="true" salvagable="true" work-time="5.0" skill-required="2" >
		 	<part type="bore drill bit" number="1" />
		 	<part type="bore drill pipe" number="20" />
			<vehicle type="LUV" >
				<attachment-part type="crane boom" />
				<attachment-part type="drilling rig" />
			</vehicle>
		</foundation>


		<foundation name="Deep Borehole Large Drilling Site" width="10.0" length="15.0"
		 north-south-alignment="length" base-level="0"
		 constructable="true" salvagable="true" work-time="10.0" skill-required="3" >
		 	<part type="bore drill bit" number="4" />
		 	<part type="bore drill pipe" number="60" />
			<vehicle type="LUV" >
				<attachment-part type="crane boom" />
				<attachment-part type="drilling rig" />
			</vehicle>
		</foundation>

		<foundation name="Deep Borehole Small Drilling Site" width="5.0" length="5.0"
		 north-south-alignment="length" base-level="0"
		 constructable="true" salvagable="true" work-time="3.0" skill-required="2" >
	 		<part type="bore drill bit" number="2" />
		 	<part type="bore drill pipe" number="15" />
			<vehicle type="LUV" >
				<attachment-part type="crane boom" />
				<attachment-part type="drilling rig" />
			</vehicle>
		</foundation>
		
		<!-- Surface foundation with a variable width and length is dynamically set. -->
		<!-- (Used for hallway construction) -->
		<foundation name="Surface Foundation Variable Size" width="-1.0" length="-1.0"
		 north-south-alignment="length" base-level="0"
		 constructable="true" salvagable="true" work-time="1.0" skill-required="1" >
			<resource type="concrete" amount="100.0" />
			<vehicle type="LUV" >
				<attachment-part type="bulldozer blade" />
				<attachment-part type="soil compactor" />
			</vehicle>
		</foundation>

		<!-- Subsurface foundation with a variable width and length that is dynamically set. -->
		<!-- (Used for tunnel construction)	-->
		<foundation name="Subsurface Foundation Variable Size" width="-1.0" length="-1.0"
		 north-south-alignment="length" base-level="-1"
		 constructable="true" salvagable="true" work-time="2.0" skill-required="1" >
		 	<resource type="concrete" amount="150.0" />
			<vehicle type="LUV" >
				<attachment-part type="bulldozer blade" />
				<attachment-part type="backhoe" />
			</vehicle>
		</foundation>

	</foundation-list>


	<frame-list>

		<frame name="Steel Frame Tower" width="5.0" length="5.0"
		 north-south-alignment="length" base-level="0" constructable="true"
		 salvagable="true" work-time="1.0" skill-required="2" foundation="Surface Foundation 5x5" >
			<resource type="acetylene" amount="1.0" />
			<resource type="concrete" amount="25.0" />
			<part type="insulation board" number="4" />				
			<part type="steel truss" number="20" />
			<part type="Flood light" number="2" />
			<part type="steel cable" number="6" />
			<vehicle type="LUV" >
				<attachment-part type="crane boom" />
			</vehicle>
		</frame>

		<frame name="Small Steel Frame" width="5.0" length="5.0"
		 north-south-alignment="length" base-level="0" constructable="true"
		 salvagable="true" work-time="1.0" skill-required="1" foundation="Surface Foundation 5x5" >
			<resource type="acetylene" amount="1.0" />
			<resource type="concrete" amount="25.0" />
			<part type="insulation board" number="4" />			
			<part type="steel truss" number="10" />
			<part type="steel sheet" number="5" />
			<part type="Flood light" number="2" />
			<vehicle type="LUV" >
				<attachment-part type="crane boom" />
			</vehicle>
		</frame>

		<frame name="Array Frame" width="5.0" length="10.0"
		 north-south-alignment="length" base-level="0" constructable="true"
		 salvagable="true" work-time="1.0" skill-required="2" foundation="Surface Foundation 5x10" >
			<resource type="acetylene" amount="1.5" />
			<resource type="concrete" amount="50.0" />
			<part type="insulation board" number="6" />				
			<part type="steel truss" number="20" />
			<part type="Flood light" number="2" />
			<vehicle type="LUV" >
				<attachment-part type="crane boom" />
			</vehicle>
		</frame>

		<frame name="Brick Bin Frame" width="2.0" length="3.0"
		 north-south-alignment="length" base-level="0" constructable="true"
		 salvagable="true" work-time="0.5" skill-required="1" foundation="Surface Foundation 2x3" >
			<resource type="concrete" amount="6.0" />
			<part type="brick" number="200" />
			<part type="Flood light" number="2" />
			<vehicle type="LUV" >
				<attachment-part type="crane boom" />
			</vehicle>
		</frame>

		<frame name="Small Brick Shed Frame" width="5.0" length="5.0"
		 north-south-alignment="length" base-level="-1" constructable="true"
		 salvagable="true" work-time="1.0" skill-required="1" foundation="Subsurface Foundation 5x5x3" >
			<resource type="concrete" amount="25.0" />
			<part type="brick" number="250" />
			<part type="Flood light" number="2" />
			<vehicle type="LUV" >
				<attachment-part type="crane boom" />
			</vehicle>
		</frame>
				
		<frame name="Round Hab Frame" width="9.0" length="9.0"
		 north-south-alignment="length" base-level="0" constructable="true"
		 salvagable="true" work-time="1.0" skill-required="2" foundation="Surface Foundation 9x9" >
		 	<resource type="concrete" amount="81.0" />
			<resource type="acetylene" amount="2.0" />		 	
			<part type="aluminum sheet" number="10" />
			<part type="insulation board" number="10" />			
			<part type="steel truss" number="20" />
			<part type="steel post" number="8" />			
			<part type="steel sheet" number="10" />	
			<part type="plastic sheet" number="20" />					
			<part type="plastic pipe" number="50" />
			<part type="electrical wire" number="200" />
			<part type="wire connector" number="200" />
			<part type="power cable" number="20" />
			<part type="steel pipe" number="40" />
			<part type="gasket" number="40" />
			<part type="valve" number="10" />
			<part type="solar panel" number="4" />
			<part type="Flood light" number="2" />
		</frame>

		<frame name="Inflatable Frame" width="6.0" length="9.0"
		 north-south-alignment="length" base-level="0" constructable="true"
		 salvagable="true" work-time="1.0" skill-required="2" foundation="Surface Foundation 6x9" >
		 	<resource type="concrete" amount="54.0" />
			<resource type="acetylene" amount="1.25" />		 	
			<part type="aluminum sheet" number="10" />
			<part type="insulation board" number="10" />			
			<part type="steel truss" number="20" />
			<part type="steel post" number="5" />			
			<part type="steel sheet" number="10" />	
			<part type="plastic sheet" number="20" />
			<part type="plastic pipe" number="50" />
			<part type="electrical wire" number="80" />
			<part type="wire connector" number="80" />
			<part type="power cable" number="12" />
			<part type="steel pipe" number="40" />
			<part type="gasket" number="30" />
			<part type="valve" number="30" />			
			<part type="Flood light" number="2" />
		</frame>

		<frame name="Atmospheric Processor Frame" width="8.0" length="11.0"
		 north-south-alignment="length" base-level="0" constructable="true"
		 salvagable="true" work-time="1.0" skill-required="3" foundation="Surface Foundation 8x11" >
		 	<resource type="concrete" amount="88.0" />
			<resource type="acetylene" amount="1.0" />		 	
			<part type="aluminum sheet" number="10" />
			<part type="steel truss" number="20" />
			<part type="steel post" number="6" />			
			<part type="steel sheet" number="10" />
			<part type="plastic sheet" number="20" />			
			<part type="plastic pipe" number="50" />
			<part type="valve" number="20" />
			<part type="electrical wire" number="50" />
			<part type="wire connector" number="50" />
			<part type="power cable" number="10" />
			<part type="steel pipe" number="10" />
			<part type="gasket" number="18" />
			<part type="Flood light" number="2" />
		</frame>

		<frame name="Modular A Frame" width="7.0" length="9.0"
		 north-south-alignment="length" base-level="0" constructable="true"
		 salvagable="true" work-time="1.0" skill-required="2" foundation="Surface Foundation 7x9" >
		 	<resource type="concrete" amount="63.0" />
			<resource type="acetylene" amount="0.9" />		 	
			<part type="aluminum sheet" number="8" />
			<part type="insulation board" number="8" />			
			<part type="steel truss" number="16" />
			<part type="steel post" number="6" />			
			<part type="steel sheet" number="8" />
			<part type="plastic sheet" number="16" />
			<part type="plastic pipe" number="40" />
			<part type="valve" number="50" />
			<part type="electrical wire" number="50" />
			<part type="wire connector" number="50" />
			<part type="power cable" number="15" />
			<part type="gasket" number="15" />
			<part type="Flood light" number="2" />
		</frame>

		<frame name="Modular B Frame" width="6.0" length="9.0"
		 north-south-alignment="length" base-level="0" constructable="true"
		 salvagable="true" work-time="1.0" skill-required="2" foundation="Surface Foundation 6x9" >
		 	<resource type="concrete" amount="54.0" />
			<resource type="acetylene" amount="0.8" />		 	
			<part type="aluminum sheet" number="7" />
			<part type="insulation board" number="8" />			
			<part type="steel truss" number="16" />
			<part type="steel post" number="6" />			
			<part type="steel sheet" number="7" />
			<part type="plastic sheet" number="15" />
			<part type="plastic pipe" number="40" />
			<part type="valve" number="50" />
			<part type="electrical wire" number="50" />
			<part type="wire connector" number="50" />
			<part type="power cable" number="12" />
			<part type="gasket" number="12" />
			<part type="Flood light" number="2" />
		</frame>

		<frame name="Core A Frame" width="6.0" length="6.0"
		 north-south-alignment="length" base-level="0" constructable="true"
		 salvagable="true" work-time="1.0" skill-required="2" foundation="Surface Foundation 6x6" >
		 	<resource type="concrete" amount="36.0" />
			<resource type="acetylene" amount="0.6" />		 	
			<part type="aluminum sheet" number="5" />
			<part type="insulation board" number="5" />			
			<part type="steel truss" number="10" />
			<part type="steel post" number="4" />			
			<part type="steel sheet" number="4" />
			<part type="plastic sheet" number="10" />
			<part type="plastic pipe" number="20" />
			<part type="valve" number="30" />
			<part type="electrical wire" number="30" />
			<part type="wire connector" number="30" />
			<part type="power cable" number="8" />
			<part type="gasket" number="8" />
			<part type="Flood light" number="1" />
		</frame>

		<frame name="Core B Frame" width="3.0" length="6.0"
		 north-south-alignment="length" base-level="0" constructable="true"
		 salvagable="true" work-time="1.0" skill-required="2" foundation="Surface Foundation 3x6" >
		 	<resource type="concrete" amount="18.0" />
			<resource type="acetylene" amount="0.3" />		 	
			<part type="aluminum sheet" number="3" />
			<part type="insulation board" number="3" />			
			<part type="steel truss" number="4" />
			<part type="steel post" number="2" />			
			<part type="steel sheet" number="2" />
			<part type="plastic sheet" number="5" />
			<part type="plastic pipe" number="10" />
			<part type="valve" number="15" />
			<part type="electrical wire" number="15" />
			<part type="wire connector" number="15" />
			<part type="power cable" number="4" />
			<part type="gasket" number="4" />
			<part type="Flood light" number="1" />
		</frame>
	
		<frame name="Core C Frame" width="3.0" length="6.0"
		 north-south-alignment="length" base-level="0" constructable="true"
		 salvagable="true" work-time="1.0" skill-required="2" foundation="Surface Foundation 3x7" >
		 	<resource type="concrete" amount="20.0" />
			<resource type="acetylene" amount="0.3" />		 	
			<part type="aluminum sheet" number="3" />
			<part type="insulation board" number="4" />			
			<part type="steel truss" number="4" />
			<part type="steel post" number="2" />			
			<part type="steel sheet" number="3" />
			<part type="plastic sheet" number="6" />
			<part type="plastic pipe" number="10" />
			<part type="valve" number="15" />
			<part type="electrical wire" number="15" />
			<part type="wire connector" number="15" />
			<part type="power cable" number="4" />
			<part type="gasket" number="4" />
			<part type="Flood light" number="1" />
		</frame>
						
		<frame name="Round Frame" width="7.0" length="7.0"
		 north-south-alignment="length" base-level="0" constructable="true"
		 salvagable="true" work-time="1.0" skill-required="2" foundation="Surface Foundation 7x7" >
		 	<resource type="concrete" amount="49.0" />
			<resource type="acetylene" amount="0.7" />		 	
			<part type="aluminum sheet" number="6" />
			<part type="insulation board" number="7" />			
			<part type="steel truss" number="14" />
			<part type="steel post" number="6" />			
			<part type="steel sheet" number="7" />
			<part type="plastic sheet" number="14" />
			<part type="plastic pipe" number="36" />
			<part type="valve" number="45" />
			<part type="electrical wire" number="45" />
			<part type="wire connector" number="45" />
			<part type="power cable" number="13" />
			<part type="gasket" number="13" />
			<part type="Flood light" number="2" />
		</frame>
		
		<frame name="Large Greenhouse Frame" width="12.0" length="18.0"
		 north-south-alignment="length" base-level="0" constructable="true"
		 salvagable="true" work-time="1.5" skill-required="3" foundation="Surface Foundation 12x18" >
		 	<resource type="concrete" amount="216.0" />
			<resource type="acetylene" amount="2.5" />		 	
			<part type="aluminum sheet" number="20" />
			<part type="insulation board" number="20" />			
			<part type="steel truss" number="30" />
			<part type="steel post" number="12" />			
			<part type="steel sheet" number="20" />
			<part type="plastic sheet" number="20" />	
			<part type="glass sheet" number="50" />
			<part type="plastic pipe" number="150" />
			<part type="valve" number="90" />
			<part type="gasket" number="90" />
			<part type="electrical wire" number="120" />
			<part type="wire connector" number="120" />
			<part type="power cable" number="30" />
			<part type="Flood light" number="4" />
		</frame>

		<frame name="Garage Frame" width="12.0" length="16.0"
		 north-south-alignment="length" base-level="0" constructable="true"
		 salvagable="true" work-time="1.2" skill-required="2" foundation="Surface Foundation 12x18" >
		 	<resource type="concrete" amount="192.0" />
			<resource type="acetylene" amount="2.5" />			 	
			<part type="aluminum sheet" number="20" />
			<part type="insulation board" number="20" />			
			<part type="steel truss" number="30" />
			<part type="steel post" number="12" />			
			<part type="steel sheet" number="20" />
			<part type="plastic sheet" number="20" />
			<part type="plastic pipe" number="100" />
			<part type="valve" number="50" />
			<part type="electrical wire" number="50" />
			<part type="wire connector" number="50" />
			<part type="power cable" number="20" />
			<part type="gasket" number="40" />
			<part type="Flood light" number="4" />
		</frame>

		<frame name="Small Areothermal Well Frame" width="5.0" length="10.0"
		 north-south-alignment="length" base-level="0" constructable="true"
		 salvagable="true" work-time="1.0" skill-required="2" foundation="Shallow Borehole Drilling Site" >
			<resource type="concrete" amount="50.0" />
			<resource type="acetylene" amount="0.5" />				
			<part type="steel truss" number="10" />
			<part type="steel sheet" number="15" />
			<vehicle type="LUV" >
				<attachment-part type="crane boom" />
			</vehicle>
		</frame>

		<frame name="Large Areothermal Well Frame" width="10.0" length="15.0"
		 north-south-alignment="length" base-level="0" constructable="true"
		 salvagable="true" work-time="1.3" skill-required="3" foundation="Deep Borehole Large Drilling Site" >
			<resource type="concrete" amount="150.0" />
			<resource type="acetylene" amount="1.0" />				
			<part type="steel truss" number="20" />
			<part type="steel sheet" number="30" />
			<vehicle type="LUV" >
				<attachment-part type="crane boom" />
			</vehicle>
		</frame>

		<frame name="Brine Water Well Frame" width="5.0" length="5.0"
		 north-south-alignment="length" base-level="0" constructable="true"
		 salvagable="true" work-time="0.4" skill-required="2" foundation="Deep Borehole Small Drilling Site" >
			<resource type="concrete" amount="45.0" />
			<resource type="acetylene" amount="0.2" />				
			<part type="steel truss" number="5" />
			<part type="steel sheet" number="6" />
			<vehicle type="LUV" >
				<attachment-part type="crane boom" />
			</vehicle>
		</frame>
		
		<frame name="Round Vaulted Brick Frame" width="10.0" length="10.0"
		 north-south-alignment="length" base-level="-1" constructable="true"
		 salvagable="true" work-time="1.2" skill-required="2" foundation="Subsurface Foundation 10x10x3" >
			<resource type="concrete" amount="100.0" />
			<part type="brick" number="1200" />
			<vehicle type="LUV" >
				<attachment-part type="crane boom" />
			</vehicle>
		</frame>

		<frame name="Large Garage Brick Frame" width="15.0" length="18.0"
		 north-south-alignment="length" base-level="-1" constructable="true"
		 salvagable="true" work-time="1.5" skill-required="3" foundation="Ramped Subsurface Foundation 15x18x5" >
			<resource type="concrete" amount="270.0" />
			<resource type="acetylene" amount="2.5" />				
			<part type="brick" number="3600" />
			<part type="aluminum sheet" number="50" />
			<part type="insulation board" number="50" />			
			<part type="steel truss" number="30" />
			<part type="steel post" number="12" />			
			<part type="steel sheet" number="50" />
			<part type="plastic sheet" number="20" />
			<part type="plastic pipe" number="100" />
			<part type="valve" number="50" />
			<part type="electrical wire" number="50" />
			<part type="wire connector" number="50" />
			<part type="power cable" number="20" />
			<part type="gasket" number="40" />
			<vehicle type="LUV" >
				<attachment-part type="crane boom" />
			</vehicle>
		</frame>

		<frame name="Vaulted Glass Brick Frame" width="5.0" length="10.0"
		 north-south-alignment="length" base-level="-1" constructable="true"
		 salvagable="true" work-time="1.0" skill-required="3" foundation="Subsurface Foundation 5x10x3" >
			<resource type="concrete" amount="50.0" />
			<resource type="acetylene" amount="0.5" />				
			<part type="brick" number="700" />
			<part type="aluminum sheet" number="10" />
			<part type="insulation board" number="10" />			
			<part type="steel truss" number="8" />
			<part type="steel post" number="4" />						
			<part type="glass sheet" number="10" />
			<part type="plastic pipe" number="7" />
			<part type="valve" number="5" />
			<part type="gasket" number="5" />
			<part type="electrical wire" number="6" />
			<part type="wire connector" number="6" />
			<part type="power cable" number="3" />
			<vehicle type="LUV" >
				<attachment-part type="crane boom" />