<?xml version = "1.0" encoding = "UTF-8" standalone = "yes" ?>
<!DOCTYPE crew-configuration [
	<!ELEMENT crew-configuration (crew-list)>

	<!ELEMENT crew-list (person*)>
	<!ELEMENT person (personality-trait-list?, natural-attribute-list?, skill-list?, relationship-list?)>
	<!ATTLIST person crew CDATA #REQUIRED>
	<!ATTLIST person name CDATA #REQUIRED>
	<!ATTLIST person gender (male|female) #IMPLIED>
	<!ATTLIST person personality-type CDATA #IMPLIED>
	<!ATTLIST person settlement CDATA #IMPLIED>
	<!ATTLIST person sponsor CDATA #IMPLIED>
	<!ATTLIST person country CDATA #IMPLIED>
	<!ATTLIST person job CDATA #IMPLIED>
	<!ATTLIST person favorite-main-dish CDATA #IMPLIED>
	<!ATTLIST person favorite-side-dish CDATA #IMPLIED>
	<!ATTLIST person favorite-dessert CDATA #IMPLIED>
	<!ATTLIST person favorite-activity CDATA #IMPLIED>
	
	<!ELEMENT personality-trait-list (personality-trait*)>
	<!ELEMENT personality-trait EMPTY>
	<!ATTLIST personality-trait name CDATA #REQUIRED>
	<!ATTLIST personality-trait value CDATA #REQUIRED>
	
	<!ELEMENT natural-attribute-list (natural-attribute*)>
	<!ELEMENT natural-attribute EMPTY>
	<!ATTLIST natural-attribute name CDATA #REQUIRED>
	<!ATTLIST natural-attribute value CDATA #REQUIRED>
	
	<!ELEMENT skill-list (skill*)>
	<!ELEMENT skill EMPTY>
	<!ATTLIST skill name CDATA #REQUIRED>
	<!ATTLIST skill level CDATA #REQUIRED>
	
	<!ELEMENT relationship-list (relationship*)>
	<!ELEMENT relationship EMPTY>
	<!ATTLIST relationship person-name CDATA #REQUIRED>
	<!ATTLIST relationship opinion CDATA #REQUIRED>
]>


<crew-configuration>

	<!-- List of preconfigured crew  -->
	<crew-list>

		<!--    Configure a crew member   -->
		<!--    Note that it must include at least a member -->
		<!--                                                -->
		<!--             crew : the crew designation of the person (required) -->
		<!--             name : the person's name (required) -->
		<!--           gender : the person's gender ("male" or "female") (optional) -->
		<!-- personality-type : the person's MBTI personality type. (optional) -->
		<!--       settlement : the person's starting settlement. Must be a named settlement configured in settlements.xml.  (optional) -->
		<!--          sponsor : the space agency or organization that sponsors this person (optional. "Mars Society (MS)" by default)-->
		<!--          country : the nationality of this person (optional. "USA" by default)-->
		<!--              job : the person's permanent job. (optional) -->
		
		<!--    See a list of Favorite subject and meal names in FavoriteType class and meals.xml -->
		<!--                                                -->
		<!-- favorite-main-dish : the person's favorite main dish. (optional) -->
		<!-- favorite-side-dish : the person's favorite side dish. (optional) -->
		<!--   favorite-dessert : the person's favorite dessert. (optional)  Available dessert are Soymilk, Sugarcane Juice, 
		                          Strawberry, Granola Bar, Blueberry Muffin, and Ccranberry Juice -->
		<!--  favorite-activity : the person's favorite hobby. see list in the FavoriteType class (optional) -->
		<person name="Karen Andersen" crew="alpha" gender="female" personality-type="ISTJ"
			settlement="Schiaparelli Point"
			sponsor="Mars Society (MS)"
			country="USA"
			job="Botanist"
			favorite-main-dish="Bean Sprout Garlic Stir Fry"
			favorite-side-dish="Roasted Carrot Soup"
			favorite-dessert="strawberry"
			favorite-activity="Field Work">

			<!-- A list of predefined personality traits (optional)

		 	Personality Trait Model / Big Five Model:

//          Openness - The willingness to make a shift of standards in new situations and appreciation for a variety of experience.
// Conscientiousness - Planning ahead rather than being spontaneous.
//      Extraversion - The willingness to communicate and socialize with people. Being energetic with people.
//     Agreeableness - The adaptiveness to other people. Adopt goals in favor of others.
//       Neuroticism - The extent to which one's emotion are sensitive to his environment; 
//                     The degree of worrying or feeling vulnerable;
//	                   The emotional sensitivity and sense of security to the situation.

			See https://www.ibm.com/smarterplanet/us/en/ibmwatson/developercloud/doc/personality-insights/models.shtml -->

			<personality-trait-list>
				<!-- the personality trait for a person using The Big Five Personality Traits, aka the Five Factor Model (FFM) -->
				<!--  name : the dimension (required) -->
				<!-- value : 0 (the absence of this trait) to 100 (the max presence of this trait) (required) -->
				<personality-trait name = "openness" 	value = "25"/>
				<personality-trait name = "conscientiousness"	 value = "65"/>
				<personality-trait name = "extraversion" 	value = "20"/>
				<personality-trait name = "agreeableness" 	value = "45"/>
				<personality-trait name = "neuroticism" 	value = "55"/>
			</personality-trait-list>

			<!-- List of configured natural attributes. (optional) -->
			<natural-attribute-list>
				<!-- A natural attribute for the person. -->
				<!-- name: the name of the attribute (required).-->
				<!-- value: 0 (low) to 100 (high) (required). -->
				<natural-attribute name="Strength" value="60"/>
				<natural-attribute name="Endurance" value="42"/>
				<natural-attribute name="Agility" value="71"/>
				<natural-attribute name="Teaching" value="65"/>
				<natural-attribute name="Academic Aptitude" value="70"/>
				<natural-attribute name="Experience Aptitude" value="35"/>
				<natural-attribute name="Stress Resilience" value="43"/>
				<natural-attribute name="Attractiveness" value="67"/>
				<natural-attribute name="Leadership" value="25"/>
				<natural-attribute name="Conversation" value="80"/>
			</natural-attribute-list>

			<!-- List of configured skills. (optional) -->
			<skill-list>
				<!-- A skill for the person. See the list in SkillType class. -->
				<!--  name : the name of the skill. (required). -->
				<!-- level : the level of the skill ( >= 0 ) (required). -->
				<skill name="Botany" level="2"/>
				<skill name="Mechanics" level="1"/>
				<skill name="EVA Operations" level="1"/>
				<skill name="Areology" level="1"/>
				<skill name="Medicine" level="1"/>
				<skill name="Cooking" level="1"/>
			</skill-list>

			<!-- List of configured relationships. (optional) -->
			<relationship-list>
				<!-- A relationship with another configured person. -->
				<!-- person-name : the name of the relationship person. (required) -->
				<!--   Note that other person must be configured on this list. -->
				<!--     opinion : this person's opinion of the relationship person. -->
				<!--                values from 0 (hate) to 100 (close friend) (required) -->
				<relationship person-name="Rik Declercq" opinion="100"/> 
			</relationship-list>
		</person>

		<person name="Rik Declercq" crew ="alpha" gender="male" personality-type="ESTP"
			settlement="Schiaparelli Point"
			sponsor="Mars Society (MS)"
			country="USA"
			job="Areologist"
			favorite-main-dish="Salsa Potato Salad" 
			favorite-side-dish="Miso Soup" 
			favorite-dessert="Soymilk"
			favorite-activity="Operation">
			<personality-trait-list>
				<personality-trait name = "openness"	 value = "35"/>
				<personality-trait name = "conscientiousness"	 value = "60"/>
				<personality-trait name = "extraversion" 	value = "80"/>
				<personality-trait name = "agreeableness" 	value = "55"/>
				<personality-trait name = "neuroticism" 	value = "45"/>
			</personality-trait-list>
			<skill-list>
                <skill name="Piloting" level="1"/>
                <skill name="Physics" level="1"/>
                <skill name="Botany" level="1"/>
                <skill name="Trading" level="1"/>
                <skill name="EVA Operations" level="1"/>
                <skill name="Cooking" level="2"/>
            </skill-list>
       </person>

        <person name="Leonardo DaVinci" crew ="alpha" gender="male" personality-type="INFJ"
        	settlement="Schiaparelli Point"
        	sponsor="Mars Society (MS)"
			country="USA"
        	job="Engineer"
			favorite-main-dish="Roasted Carrot Soup and Brown Rice" 
			favorite-side-dish="Baby Carrots" 
			favorite-dessert="Craneberry Juice"
			favorite-activity="Research">
			<personality-trait-list>
				<personality-trait name = "openness" 	value = "65"/>
				<personality-trait name = "conscientiousness" 	value = "80"/>
				<personality-trait name = "extraversion" 	value = "15"/>
				<personality-trait name = "agreeableness" 	value = "75"/>
				<personality-trait name = "neuroticism" 	value = "75"/>
			</personality-trait-list>
            <skill-list>
                <skill name="Physics" level="1"/>
                <skill name="Botany" level="1"/>
                <skill name="Mechanics" level="1"/>
                <skill name="Areology" level="1"/>
                <skill name="Medicine" level="1"/>
                <skill name="Materials Science" level="2"/>
            </skill-list>
        </person>

        <person name="Lena LaGranda" crew ="alpha" gender="female" personality-type="ENFJ"
        	settlement="Schiaparelli Point"
        	sponsor="Mars Society (MS)"
			country="USA"
        	job="Technician"
			favorite-main-dish="Kidney Bean Fried Rice with Onion" 
			favorite-side-dish="Peas and Onions" 
			favorite-dessert="Bluebbery Muffin"
			favorite-activity="Tinkering">
			<personality-trait-list>
				<personality-trait name = "openness" 	value = "70"/>
				<personality-trait name = "conscientiousness" 	value = "60"/>
				<personality-trait name = "extraversion" 	value = "85"/>
				<personality-trait name = "agreeableness" 	value = "80"/>
				<personality-trait name = "neuroticism" 	value = "35"/>
			</personality-trait-list>
            <skill-list>
                <skill name="Piloting" level="1"/>
                <skill name="Physics" level="1"/>
                <skill name="Botany" level="1"/>
                <skill name="Mechanics" level="2"/>
                <skill name="EVA Operations" level="1"/>
                <skill name="Materials Science" level="1"/>
            </skill-list>
        </person>

       <person name="Ray Bradbury" crew ="alpha" gender="male" personality-type="INTP"
        	settlement="Schiaparelli Point"
        	sponsor="Mars Society (MS)"
			country="USA"
        	job="Doctor"
			favorite-main-dish="Veggie Sandwich" 
			favorite-side-dish="Taro Soup"
			favorite-dessert="Soymilk"
			favorite-activity="Astronomy">
			<personality-trait-list>
				<personality-trait name = "openness" 	value = "80"/>
				<personality-trait name = "conscientiousness" 	value = "90"/>
				<personality-trait name = "extraversion" 	value = "35"/>
				<personality-trait name = "agreeableness" 	value = "70"/>
				<personality-trait name = "neuroticism" 	value = "20"/>
			</personality-trait-list>
            <skill-list>
                <skill name="Reporting" level="1"/>
                <skill name="Physics" level="1"/>
                <skill name="Medicine" level="2"/>
                <skill name="Astronomy" level="1"/>
                <skill name="Materials Science" level="1"/>
            </skill-list>
        </person>
        
	</crew-list>

</crew-configuration>
