<?xml version = "1.0" encoding = "UTF-8" standalone = "yes" ?>
<!DOCTYPE foodProduction-processes [
	<!ELEMENT foodProduction-processes (process*)>
	<!ELEMENT process (description?, inputs, outputs)>
	<!ATTLIST process name CDATA #REQUIRED>
	<!ATTLIST process tech CDATA #REQUIRED>
	<!ATTLIST process skill CDATA #REQUIRED>
	<!ATTLIST process work-time CDATA #REQUIRED>
	<!ATTLIST process process-time CDATA #REQUIRED>
	<!ATTLIST process power-required CDATA #REQUIRED>
	<!ELEMENT description (#PCDATA)>
	<!ELEMENT inputs (part*, resource*)>
	<!ELEMENT outputs (part*, resource*, equipment*)>
	<!ELEMENT resource EMPTY>
	<!ATTLIST resource name CDATA #REQUIRED>
	<!ATTLIST resource amount CDATA #REQUIRED>
	<!ELEMENT part EMPTY>
	<!ATTLIST part name CDATA #REQUIRED>
	<!ATTLIST part number CDATA #REQUIRED>
	<!ELEMENT equipment EMPTY>
	<!ATTLIST equipment name CDATA #REQUIRED>
	<!ATTLIST equipment number CDATA #REQUIRED>
]>

<!-- List of all food production processes. -->
<foodProduction-processes>

	<!-- tech - The minimum tech level required to perform the process.  -->
	<!-- skill - The minimum person skill level in cooking to perform the process. -->
	<!-- work-time - The effort time (in millisols) required to perform the process.  Higher skilled workers will produce more effort time than lower skilled workers. -->
	<!-- process-time - The minimum time (in millisols) required for the process regardless of effort time. -->
	<!-- power-required - The total amount of power (kW hr) required for the process. -->
	<process name="Package Cabbage as Preserved Food"
			tech="1" skill="0"
			work-time="50"
			process-time="50"
			power-required="0.1">
		<description>Cut and freeze dry cabbage into package food.</description>

		<!-- List of inputs for the process ( parts and resources). -->
		<inputs>
			<!-- amount - The amount of the resource in kilograms. -->
			<part name="refrigerator" number="1" />
			<resource name="Cabbage" amount="5.0" />
		</inputs>

		<!-- List of outputs from the process (parts, resources, equipment). -->
		<outputs>
			<part name="refrigerator" number="1" />
			<resource name="food" amount="3.0" />
		</outputs>
	</process>

	<process name="Package leaves as Preserved Food"
			tech="0" skill="0"
			work-time="5"
			process-time="5"
			power-required="0.1">
		<description>Cut and freeze dry leaves into package food.</description>
		<inputs>
			<part name="refrigerator" number="1" />
			<resource name="leaves" amount="10.0" />
		</inputs>
		<outputs>
			<part name="refrigerator" number="1" />
			<resource name="food" amount="6.0" />
		</outputs>
	</process>
	
	<process name="Package Carrot as Preserved Food"
			tech="1" skill="0"
			work-time="50"
			process-time="50"
			power-required="0.1">
		<description>Cut and freeze dry carrots into package food.</description>
		<inputs>
			<part name="refrigerator" number="1" />
			<resource name="Carrot" amount="5.0" />
		</inputs>
		<outputs>
			<part name="refrigerator" number="1" />
			<resource name="food" amount="3.0" />
		</outputs>
	</process>

	<process name="Package Swiss Chard as Preserved Food"
			tech="1" skill="0"
			work-time="50"
			process-time="50"
			power-required="0.1">
		<description>Cut and freeze dry swiss chard into package food.</description>
		<inputs>
			<part name="refrigerator" number="1" />
			<resource name="Swiss Chard" amount="5.0" />
		</inputs>
		<outputs>
			<part name="refrigerator" number="1" />
			<resource name="food" amount="3.0" />
		</outputs>
	</process>

	<process name="Package Potatoes as Preserved Food"
			tech="1" skill="0"
			work-time="50"
			process-time="50"
			power-required="0.1">
		<description>Cut and dry potatoes into package food.</description>
		<inputs>
			<resource name="Potato" amount="10.0" />
		</inputs>
		<outputs>
			<resource name="food" amount="5.0" />
		</outputs>
	</process>


	<process name="Package Quinoa into Granola Bar"
			tech="1" skill="0"
			work-time="50"
			process-time="100"
			power-required="0.1">
		<description>Package puffed Quinoa, honey, nuts and dried fruits into Granola Bar.</description>
		<inputs>
			<resource name="Quinoa" amount="4.0" />
			<resource name="Strawberry" amount="0.5" />
			<resource name="Honey" amount="0.5" />
			<resource name="Peanut" amount="1.0" />
		</inputs>
		<outputs>
			<resource name="Granola Bar" amount="4.0" />
		</outputs>
	</process>

	<process name="Package Rice into Granola Bar"
			tech="1" skill="0"
			work-time="50"
			process-time="100"
			power-required="0.1">
		<description>Package puffed rice, honey, nuts and dried fruits into Granola Bar.</description>
		<inputs>
			<resource name="Rice" amount="4.0" />
			<resource name="Strawberry" amount="0.5" />
			<resource name="Honey" amount="0.5" />
			<resource name="Peanut" amount="1.0" />
		</inputs>
		<outputs>
			<resource name="Granola Bar" amount="4.0" />
		</outputs>
	</process>

		<process name="Package Wheat into Granola Bar"
			tech="1" skill="0"
			work-time="50"
			process-time="100"
			power-required="0.1">
		<description>Package puffed wheat, honey, nuts and dried fruits into Granola Bar.</description>
		<inputs>
			<resource name="Wheat" amount="4.0" />
			<resource name="Strawberry" amount="0.5" />
			<resource name="Honey" amount="0.5" />
			<resource name="Peanut" amount="1.0" />
		</inputs>
		<outputs>
			<resource name="Granola Bar" amount="4.0" />
		</outputs>
	</process>

	<process name="Package Quinoa into Granola Bar"
			tech="1" skill="0"
			work-time="50"
			process-time="100"
			power-required="0.1">
		<description>Package puffed Quinoa, sugarcane juice, nuts and dried fruits into Granola Bar.</description>
		<inputs>
			<resource name="Quinoa" amount="4.0" />
			<resource name="Strawberry" amount="0.5" />
			<resource name="Sugarcane Juice" amount="0.5" />
			<resource name="Peanut" amount="1.0" />
		</inputs>
		<outputs>
			<resource name="Granola Bar" amount="5.0" />
		</outputs>
	</process>

	<process name="Package Rice into Granola Bar"
			tech="1" skill="0"
			work-time="50"
			process-time="100"
			power-required="0.1">
		<description>Package puffed rice, sugarcane juice, nuts and dried fruits into Granola Bar.</description>
		<inputs>
			<resource name="Rice" amount="4.0" />
			<resource name="Strawberry" amount="0.5" />
			<resource name="Sugarcane Juice" amount="0.5" />
			<resource name="Peanut" amount="1.0" />
		</inputs>
		<outputs>
			<resource name="Granola Bar" amount="5.0" />
		</outputs>
	</process>

	<process name="Package Wheat into Granola Bar"
			tech="1" skill="0"
			work-time="50"
			process-time="100"
			power-required="0.1">
		<description>Package puffed wheat, sugarcane juice, nuts and dried fruits into Granola Bar.</description>
		<inputs>
			<resource name="Wheat" amount="4.0" />
			<resource name="Strawberry" amount="0.5" />
			<resource name="Sugarcane Juice" amount="0.5" />
			<resource name="Peanut" amount="1.0" />
		</inputs>
		<outputs>
			<resource name="Granola Bar" amount="5.0" />
		</outputs>
	</process>

	<process name="Package Okara and Wheat into Granola Bar"
			tech="1" skill="0"
			work-time="50"
			process-time="100"
			power-required="0.1">
		<description>Package puffed wheat, sugarcane juice, nuts and dried fruits into Granola Bar.</description>
		<inputs>
			<resource name="Wheat" amount="2.0" />
			<resource name="Okara" amount="9.11" />
			<resource name="Strawberry" amount="0.5" />
			<resource name="Sugarcane Juice" amount="0.5" />
			<resource name="Peanut" amount="1.0" />
		</inputs>
		<outputs>
			<resource name="Granola Bar" amount="5.0" />
		</outputs>
	</process>

	<process name="Package Okara and Rice into Granola Bar"
			tech="1" skill="0"
			work-time="50"
			process-time="100"
			power-required="0.1">
		<description>Package puffed wheat, sugarcane juice, nuts and dried fruits into Granola Bar.</description>
		<inputs>
			<resource name="Rice" amount="2.0" />
			<resource name="Okara" amount="9.11" />
			<resource name="Strawberry" amount="0.5" />
			<resource name="Sugarcane Juice" amount="0.5" />
			<resource name="Peanut" amount="1.0" />
		</inputs>
		<outputs>
			<resource name="Granola Bar" amount="5.0" />
		</outputs>
	</process>

	<process name="Package Okara and Quinoa into Granola Bar"
			tech="1" skill="0"
			work-time="50"
			process-time="100"
			power-required="0.1">
		<description>Package puffed wheat, sugarcane juice, nuts and dried fruits into Granola Bar.</description>
		<inputs>
			<resource name="Quinoa" amount="2.0" />
			<resource name="Okara" amount="9.11" />
			<resource name="Strawberry" amount="0.5" />
			<resource name="Sugarcane Juice" amount="0.5" />
			<resource name="Peanut" amount="1.0" />
		</inputs>
		<outputs>
			<resource name="Granola Bar" amount="5.0" />
		</outputs>
	</process>
	
	<process name="Make French Fries from potatoes"
			tech="1" skill="1"
			work-time="50"
			process-time="50"
			power-required="0.7">
		<description>Cut potatoes and make French Fries.</description>
		<inputs>
			<resource name="Potato" amount="10.0" />
			<resource name="Peanut Oil" amount="1.0" />
		</inputs>
		<outputs>
			<resource name="French Fries" amount="10.0" />
		</outputs>
	</process>
	
	<process name="Make French Fries from potatoes"
			tech="1" skill="1"
			work-time="50"
			process-time="50"
			power-required="0.7">
		<description>Cut potatoes and make French Fries.</description>
		<inputs>
			<resource name="Potato" amount="10.0" />
			<resource name="Soybean Oil" amount="1.0" />
		</inputs>
		<outputs>
			<resource name="French Fries" amount="10.0" />
		</outputs>
	</process>

	<process name="Make Soy Sprouts from Soybeans"
			tech="1" skill="1"
			work-time="50"
			process-time="3000"
			power-required="0.0">
		<description>Sanitize soybean seeds with sodium hypochlorite. 
			Wash the seeds and soak them in water and
			wait for germination. When germinated, freeze dry them. </description>
		<inputs>
			<part name="refrigerator" number="1" />
			<resource name="Soybean" amount="3.0" />
			<resource name="Water" amount="3.0" />
			<resource name="sodium hypochlorite" amount="0.003" />
		</inputs>

		<outputs>
			<part name="refrigerator" number="1" />
			<resource name="Soy Sprout" amount="15.0" />
		</outputs>
	</process>

	<process name="Make Quinoa Sprouts from Quinoa"
			tech="1" skill="1"
			work-time="50"
			process-time="2000"
			power-required="0.0">
		<description>Rinse the quinoa seeds in a bowl. Wash the quinoa seeds 
			to remove the soapy coating known as saponin. Soak in water and 
			drain the water after 30 minutes. Repeat the rinsing and draining 
			process every 8 hours. Put the tray of quinoa in a dark room. 
			Place the cloth back over the quinoa for protection.The quinoa will 
			sprout into a plate full of spiral-shaped roots that are at least 
			one-quarter inch in length. Dry out sprouts for up to 12 hours 
			after fully germinated. </description>
		<inputs>
			<resource name="Quinoa" amount="3.0" />
			<resource name="Water" amount="3.0" />
		</inputs>

		<outputs>
			<resource name="Quinoa Sprout" amount="15.0" />
		</outputs>
	</process>

	<!-- see http://dx.doi.org/10.2135/cropsci1999.0011183X0039000200017x and http://dx.doi.org/10.1016/B978-0-12-394437-5.00130-3 for soymilk/tofu yield (5.1 ml/g and 0.865 g/ml) and okara yield (1.1 per kg beans) and water:dry bean ratio (8:1 to 10:1); assumes density of soymilk is 1.03 kg/l and about 3/4 as much sugar as before; aiming for 13.6 g/l total sugar -->
	<process name="Make Okara and Soymilk from Soybeans"
		tech="1" skill="0" work-time="30" process-time="70"
			power-required="0.5">

		<description> Make pulp (Okara) and Soymilk from Soybean after
			Washing, Dehulling, Soaking, Milling, Paste
			Heating, and Filtration. </description>
		<inputs>
			<part name="blender" number="1" />
			<part name="stove" number="1" />
			<resource name="Soybean" amount="0.95" />
			<resource name="Water" amount="10.5" />
			<resource name="Sugar" amount="0.0465" />
		</inputs>
		<outputs>
			<part name="blender" number="1" />
			<part name="stove" number="1" />
			<resource name="Grey Water" amount="1.9" />
			<resource name="Okara" amount="1.045" />
			<resource name="Soymilk" amount="5" />
		</outputs>
	</process>

	<process name="Make sesame milk from soymilk"
		tech="1" skill="1" work-time="20" process-time="20"
			power-required="1.0">

		<description> Make sesame milk from soymilk </description>
		<inputs>
			<part name="blender" number="1" />
			<resource name="sesame seed" amount="0.5" />
			<resource name="soymilk" amount="4.5" />
		</inputs>
		<outputs>
			<part name="blender" number="1" />
			<resource name="sesame milk" amount="5.0" />
		</outputs>
	</process>
	
	<process name="Press and Refine Peanut Oil from Peanuts"
		tech="2" skill="1" work-time="50" process-time="400"
			power-required="2.0">

		<description>Derive vegetable oil from peanuts. Press and refine it
			for use </description>

		<inputs>
			<resource name="Peanut" amount="4.0" />
		</inputs>
		<outputs>
			<resource name="Peanut Oil" amount="2.0" />
		</outputs>
	</process>

	<process name="Chop and Roast Peanuts in Oven"
		tech="1" skill="1" work-time="50" process-time="300"
			power-required="1.0">

		<description>Chopped up peanuts and roast them in oven </description>

		<inputs>
			<part name="oven" number="1" />
			<resource name="Peanut" amount="5.0" />
			<resource name="table salt" amount="0.5" />
		</inputs>
		<outputs>
			<part name="oven" number="1" />
			<resource name="Roasted Peanut" amount="5.0" />
		</outputs>
	</process>

	<process name="Make Peanut Butter from Peanuts"
		tech="1" skill="0" work-time="50" process-time="50"
			power-required="0.2">

		<description>Ground peanuts, mix with oil, pour the mixture into food processor.
		Blend until smooth.</description>

		<inputs>
			<part name="blender" number="1" />
			<!--
			TODO: add cocoa powder, cinnamon or other spice
			/>-->
			<resource name="Peanut" amount="3.0" />
			<resource name="Soybean Oil" amount="0.5" />
			<resource name="table salt" amount="0.1" />
			<resource name="Soy Protein" amount="0.1" />
		</inputs>
		<outputs>
			<part name="blender" number="1" />
			<resource name="Peanut Butter" amount="3.5" />
		</outputs>
	</process>
	
	<process name="Make Peanut Butter from Peanuts"
		tech="1" skill="0" work-time="50" process-time="50"
			power-required="0.2">

		<description>Ground peanuts, mix with oil, pour the mixture into food processor.
		Blend until smooth.</description>

		<inputs>
			<part name="blender" number="1" />
			<!--
			TODO: add cocoa powder, cinnamon or other spice
			/>-->
			<resource name="Peanut" amount="3.0" />
			<resource name="Peanut Oil" amount="0.5" />
			<resource name="table salt" amount="0.1" />
			<resource name="Soy Protein" amount="0.1" />
		</inputs>
		<outputs>
			<part name="blender" number="1" />
			<resource name="Peanut Butter" amount="3.5" />
		</outputs>
	</process>

	<process name="Package Roast Peanuts into Dry Food"
		tech="0" skill="0" work-time="50" process-time="50"
			power-required="1.0">

		<description>Pack peanuts into dry food</description>

		<inputs>
			<part name="oven" number="1" />
			<resource name="Roasted Peanut" amount="5.0" />
		</inputs>
		<outputs>
			<part name="oven" number="1" />
			<resource name="food" amount="5.0" />
		</outputs>
	</process>


	<process name="Bake White Bread from Soy Flour"
		tech="1" skill="1" work-time="50" process-time="200"
			power-required="1.0">

		<description> Make 2 loaves of White Bread from Soy Flour </description>

		<inputs>
			<part name="oven" number="1" />
			<resource name="Soy Flour" amount="1.0" />
			<resource name="Water" amount="0.33" />
			<resource name="Yeast" amount="0.01" />
		</inputs>
		<outputs>
			<part name="oven" number="1" />
			<resource name="White Bread" amount="1.2" />
		</outputs>
	</process>

	<process name="Make Tofu from Soymilk and Epsom Salt"
		tech="1" skill="1" work-time="25" process-time="50"
			power-required="1.0">

		<description> Boil up Soymilk, add Epsom Salt as Coagulant,
			gently stir and heat, and the curds will separate.</description>

		<inputs>
			<part name="stove" number="1" />
			<resource name="Soymilk" amount="2.5" />
			<resource name="Epsom Salt" amount="0.021" />
		</inputs>
		<outputs>
			<part name="stove" number="1" />
			<resource name="Tofu" amount="2.1" />
			<!-- Grey Water is (edible) tofu whey -->
			<resource name="Grey Water" amount="0.4" />
		</outputs>
	</process>

	<!-- 7.37 g/kg soymilk to 15.47 g/kg soymilk is ideal according to https://www.instructables.com/Homemade-Tofu/ ...TODO: add gypsum later? -->
	<process name="Make Tofu from Soymilk and Vinegar"
		tech="1" skill="1" work-time="25" process-time="50"
			power-required="1.0">

		<description> Boil up Soymilk, add Epsom Salt as Coagulant,
			gently stir and heat, and the curds will separate.</description>

		<inputs>
			<part name="stove" number="1" />
			<resource name="Soymilk" amount="2.5" />
			<resource name="Rice Vinegar" amount="0.039" />
		</inputs>
		<outputs>
			<part name="stove" number="1" />
			<resource name="Tofu" amount="2.1" />
			<!-- Grey Water is (edible) tofu whey -->
			<resource name="Grey Water" amount="0.4" />
		</outputs>
	</process>

	<process name="Make Tofu from Soybeans, Water, and Epsom Salt (large batch)"
		tech="1" skill="2" work-time="70" process-time="400"
			power-required="3.8">

		<description> Boil up Soybeans, grind into soymilk, filter off okra, and add Epsom Salt as Coagulants.
			gently stir and heat, the curds will separate.</description>

		<inputs>
			<part name="blender" number="1" />
			<part name="stove" number="1" />
			<resource name="Soybean" amount="1.7" />
			<resource name="Water" amount="18.7" />
			<resource name="Epsom Salt" amount="0.076" />
		</inputs>
		<outputs>
			<part name="blender" number="1" />
			<part name="stove" number="1" />
			<resource name="Tofu" amount="7.5" />
			<resource name="Okara" amount="1.87" />
			<resource name="Grey Water" amount="3.4" />
		</outputs>
	</process>

	<process name="Make Tofu from Soybeans, Water, and Vinegar (large batch)"
		tech="1" skill="2" work-time="70" process-time="400"
			power-required="3.8">

		<description> Boil up Soybeans, grind into soymilk, filter off okra, and add vinegar as Coagulants.
			gently stir and heat, the curds will separate.</description>

		<inputs>
			<part name="blender" number="1" />
			<part name="stove" number="1" />
			<resource name="Soybean" amount="1.7" />
			<resource name="Water" amount="18.7" />
			<resource name="Rice Vinegar" amount="0.0691" />
		</inputs>
		<outputs>
			<part name="blender" number="1" />
			<part name="stove" number="1" />
			<resource name="Tofu" amount="7.5" />
			<resource name="Okara" amount="1.87" />
			<resource name="Grey Water" amount="3.4" />
		</outputs>
	</process>

	<process name="Make Soymilk and Tofu from Soybeans, Water, and Epsom Salt"
		tech="1" skill="2" work-time="53" process-time="400"
			power-required="2.8">

		<description> Boil up Soybeans, grind into soymilk, filter off okra, and add Epsom Salt as Coagulants.
			gently stir and heat, the curds will separate. Save and sweeten some soymilk.</description>

		<inputs>
			<part name="blender" number="1" />
			<part name="stove" number="1" />
			<resource name="Soybean" amount="1.25" />
			<resource name="Water" amount="13.75" />
			<resource name="Epsom Salt" amount="0.556" />
			<resource name="Sugar" amount="0.280" />
		</inputs>
		<outputs>
			<part name="blender" number="1" />
			<part name="stove" number="1" />
			<resource name="Tofu" amount="3.0" />
			<resource name="Soymilk" amount="3.0" />
			<resource name="Okara" amount="1.375" />
			<resource name="Grey Water" amount="6.07" />
		</outputs>
	</process>

	<process name="Make Soymilk and Tofu from Soybeans, Water, and Vinegar"
		tech="1" skill="2" work-time="53" process-time="400"
			power-required="2.8">

		<description> Boil up Soybeans, grind into soymilk, filter off okra, and add vinegar as coagulants.
			gently stir and heat, the curds will separate. Save and sweeten some soymilk.</description>

		<inputs>
			<part name="blender" number="1" />
			<part name="stove" number="1" />
			<resource name="Soybean" amount="1.25" />
			<resource name="Water" amount="13.75" />
			<resource name="Rice Vinegar" amount="0.0508" />
			<resource name="Sugar" amount="0.280" />
		</inputs>
		<outputs>
			<part name="blender" number="1" />
			<part name="stove" number="1" />
			<resource name="Tofu" amount="3.0" />
			<resource name="Soymilk" amount="3.0" />
			<resource name="Okara" amount="1.375" />
			<resource name="Grey Water" amount="6.07" />
		</outputs>
	</process>

	<process name="Process Soybean into Soy Flour"
		tech="1" skill="2" work-time="50" process-time="300"
			power-required="0.25">
		<description> Create defatted soy flour by cracking, screening, heating soybean 
		at 130 deg C with hot extrusion and high pressure .  </description>
		<inputs>
			<part name="oven" number="1" />
			<resource name="Soybean" amount="1.0" />
			<resource name="Water" amount="1.0" />
		</inputs>
		<outputs>
			<part name="oven" number="1" />
			<resource name="Soy Flour" amount="1.0" />
		</outputs>
	</process>

	<!-- https://www.youtube.com/watch?v=LGMVoL7nGSI says 30 g vinegar per 500 g cooked substrate... https://en.wikipedia.org/wiki/Tempeh#Dry_matter_losses_and_yield suggests 1.9 kg tempeh from 1 kg raw soybeans 1 kg dry ~2.3 kg cooked http://dx.doi.org/10.1016/B978-0-12-394437-5.00130-3 for moisture content, and https://www.youtube.com/watch?v=Zfkd6VXT9_0 for starter -->
	<process name="Make Tempeh from Soybeans"
		tech="1" skill="2" work-time="70" process-time="1000"
			power-required="0.6">

		<description> Boil Soybeans, add vinegar and Rhizopus oligosporus starter, and
			allow to ferment.</description>

		<inputs>
			<part name="autoclave" number="1" />
			<resource name="soybean" amount="1.0" />
			<resource name="Water" amount="3.5" />
			<resource name="Rice Vinegar" amount="0.138" />
			<resource name="Rhizopus oligosporus" amount="0.0023" />
		</inputs>
		<outputs>
			<part name="autoclave" number="1" />
			<resource name="Tempeh" amount="1.9" />
			<resource name="Grey Water" amount="2.0" />
		</outputs>
	</process>

	<!-- Tempeh yield from okara is approximate/estimated, assuming excess water from okara evaporates away -->
	<process name="Make Black Oncom from Okara"
		tech="1" skill="2" work-time="71" process-time="10500"
			power-required="0.1">

		<description> Moisten Okara with vinegar, add Rhizopus oligosporus starter, and
			allow to ferment.</description>

		<inputs>
			<part name="autoclave" number="1" />
			<resource name="Rice Vinegar" amount="0.174" />
			<resource name="Okara" amount="2.9" />
			<resource name="Rhizopus oligosporus" amount="0.0029" />
		</inputs>
		<outputs>
			<part name="autoclave" number="1" />
			<resource name="Tempeh" amount="2.2" />
		</outputs>
	</process>
	
	<process name="Make Tempeh from half Soybeans and half Okara"
		tech="1" skill="2" work-time="72" process-time="1000"
			power-required="0.63">

		<description> Boil Soybeans, add vinegar, Rhizopus oligosporus starter, and okara,
			and allow to ferment.</description>

		<inputs>
			<part name="autoclave" number="1" />
			<resource name="soybean" amount="1.0" />
			<resource name="Water" amount="3.5" />
			<resource name="Rice Vinegar" amount="0.198" />
			<resource name="Okara" amount="1.0" />
			<resource name="Rhizopus oligosporus" amount="0.0033" />
		</inputs>
		<outputs>
			<part name="autoclave" number="1" />
			<resource name="Tempeh" amount="2.66" />
			<resource name="Grey Water" amount="1.0" />
		</outputs>
	</process>
	
	<process name="Make Tofu and Tempeh from Soybeans and Vinegar (large batch)"
		tech="1" skill="2" work-time="125" process-time="1000"
			power-required="3.85">

		<description> Boil Soybeans, blend, separate okara and ferment with Rhizopus
			oligosporus starter. Add vinegar to soymilk as coagulant. This uses
			all the okara by-product of tofu.</description>

		<inputs>
			<part name="autoclave" number="1" />
			<resource name="soybean" amount="1.7" />
			<resource name="Water" amount="18.7" />
			<resource name="Rice Vinegar" amount="0.181" />
			<resource name="Rhizopus oligosporus" amount="0.0019" />
		</inputs>
		<outputs>
			<part name="autoclave" number="1" />
			<part name="blender" number="1" />
			<part name="stove" number="1" />
			<resource name="Tofu" amount="7.5" />
			<resource name="Tempeh" amount="1.42" />
			<resource name="Grey Water" amount="4.83" />
		</outputs>
	</process>
	
	<process name="Make Tofu and Tempeh from Soybeans and Epsom Salt (large batch)"
		tech="1" skill="2" work-time="125" process-time="1000"
			power-required="3.85">

		<description> Boil Soybeans, blend, separate okara and ferment with Rhizopus
			oligosporus starter. Add vinegar to soymilk as coagulant. This uses
			all the okara by-product of tofu.</description>

		<inputs>
			<part name="autoclave" number="1" />
			<resource name="soybean" amount="1.7" />
			<resource name="Water" amount="18.7" />
			<resource name="Rice Vinegar" amount="0.112" />
			<resource name="Rhizopus oligosporus" amount="0.0019" />
			<resource name="Epsom Salt" amount="0.0962" />
		</inputs>
		<outputs>
			<part name="autoclave" number="1" />
			<part name="blender" number="1" />
			<part name="stove" number="1" />
			<resource name="Tofu" amount="7.5" />
			<resource name="Tempeh" amount="1.42" />
			<resource name="Grey Water" amount="4.83" />
		</outputs>
	</process>
	
	<process name="Make Tofu, Soymilk, and Tempeh from Soybeans and Vinegar"
		tech="1" skill="2" work-time="125" process-time="1000"
			power-required="1.3">

		<description> Boil Soybeans, blend, separate okara and ferment with Rhizopus
			oligosporus starter. Add vinegar to some soymilk as coagulant,
			sweetening the remainder.</description>

		<inputs>
			<part name="autoclave" number="1" />
			<resource name="soybean" amount="1.25" />
			<resource name="Water" amount="13.75" />
			<resource name="Rice Vinegar" amount="0.133" />
			<resource name="Rhizopus oligosporus" amount="0.0014" />
			<resource name="Sugar" amount="0.028" />
		</inputs>
		<outputs>
			<part name="autoclave" number="1" />
			<part name="blender" number="1" />
			<part name="stove" number="1" />
			<resource name="Tofu" amount="3.0" />
			<resource name="Soymilk" amount="3.0" />
			<resource name="Tempeh" amount="1.04" />
			<resource name="Grey Water" amount="6.07" />
		</outputs>
	</process>
	
	<process name="Make Tofu, Soymilk, and Tempeh from Soybeans and Epsom Salt"
		tech="1" skill="2" work-time="125" process-time="1000"
			power-required="1.3">

		<description>Boil Soybeans, blend, separate okara and ferment with Rhizopus
			oligosporus starter. Add vinegar to some soymilk as coagulant,
			sweetening the remainder.</description>
		
		<inputs>
			<part name="autoclave" number="1" />
			<resource name="soybean" amount="1.25" />
			<resource name="Water" amount="13.75" />
			<resource name="Rice Vinegar" amount="0.0825" />
			<resource name="Rhizopus oligosporus" amount="0.0014" />
			<resource name="Epsom Salt" amount="0.0707" />
			<resource name="Sugar" amount="0.028" />
		</inputs>
		<outputs>
			<part name="autoclave" number="1" />
			<part name="blender" number="1" />
			<part name="stove" number="1" />
			<resource name="Tofu" amount="3.0" />
			<resource name="Soymilk" amount="3.0" />
			<resource name="Tempeh" amount="1.04" />
			<resource name="Grey Water" amount="6.07" />
		</outputs>
	</process>
	
	<process name="Process White Rice into Rice Flour"
		tech="1" skill="2" work-time="25" process-time="300"
			power-required="0.25">
		<description> Rince rice, dry, and finely grind.</description>
		<inputs>
			<resource name="White Rice" amount="1.0" />
			<resource name="Water" amount="3.0" />

		</inputs>
		<outputs>
			<resource name="Water" amount="2.9" />
			<resource name="Rice Flour" amount="1.0" />
		</outputs>

	</process>

	<process name="Process Rice into White Rice and rice bran oil"
		tech="1" skill="1" work-time="50" process-time="100" power-required="0.5">
		<description> Remove hulls, bran layers and germ from rice.
		May enrich milled rice with vitamins and minerals </description>

		<inputs>
			<resource name="Rice" amount="2.0" />

		</inputs>
		<outputs>
			<resource name="White Rice" amount="1.33" />
			<resource name="Crop Waste" amount="0.495" />
			<resource name="rice bran oil" amount="0.175" />			
		</outputs>
	</process>

	<!-- http://www.knowledgebank.irri.org/step-by-step-production/postharvest/milling says rice is 20 % hull, 11 % bran, and 69 % other ideally, but ranges are 20 % hull, 8-12 % bran, and 68-72 % other; extrapolates waste from buckwheat -->
	<process name="Process Rice into Brown Rice"
		tech="1" skill="0" work-time="50" process-time="50" power-required=".1">
		<description> Remove only hulls from rice. The light brown color is due to the presence of the bran layers