<?xml version = "1.0" encoding = "UTF-8" standalone = "yes" ?>
<!DOCTYPE malfunction-list [
	<!ELEMENT malfunction-list (malfunction*)>
	<!ELEMENT malfunction (severity, malfunction-probability, repair-inside?, repair-eva?,
	system-list, effect-list?, medical-complaint-list?, repair-parts-list?)>
	<!ATTLIST malfunction name CDATA #REQUIRED>
	<!ELEMENT severity EMPTY>
	<!ATTLIST severity value CDATA #REQUIRED>
	<!ELEMENT malfunction-probability EMPTY>
	<!ATTLIST malfunction-probability value CDATA #REQUIRED>
	<!ELEMENT repair-inside EMPTY>
	<!ATTLIST repair-inside time CDATA #REQUIRED>
	<!ATTLIST repair-inside repairers CDATA #IMPLIED>
	<!ELEMENT repair-eva EMPTY>
	<!ATTLIST repair-eva time CDATA #REQUIRED>
	<!ATTLIST repair-eva repairers CDATA #IMPLIED>
	<!ELEMENT system-list (system+)>
	<!ELEMENT system EMPTY>
	<!ATTLIST system name CDATA #REQUIRED>
	<!ELEMENT effect-list (effect*)>
	<!ELEMENT effect EMPTY>
	<!ATTLIST effect name CDATA #REQUIRED>
	<!ATTLIST effect type (resource|life-support) #REQUIRED>
	<!ATTLIST effect change-rate CDATA #REQUIRED>
	<!ELEMENT medical-complaint-list (medical-complaint*)>
	<!ELEMENT medical-complaint EMPTY>
	<!ATTLIST medical-complaint name CDATA #REQUIRED>
	<!ATTLIST medical-complaint medical-probability CDATA #REQUIRED>
	<!ELEMENT repair-parts-list (part*)>
	<!ELEMENT part EMPTY>
	<!ATTLIST part name CDATA #REQUIRED>
	<!ATTLIST part number CDATA #REQUIRED>
	<!ATTLIST part repair-probability CDATA #REQUIRED>
]>

<!-- List of possible malfunctions -->
<malfunction-list>

	<!-- Small air leak -->
	<malfunction name="Air Leak">

		<!-- Relative severity of the malfunction. (required) -->
		<!-- Values: 1 to 100 (100 = most severe) -->
		<severity value="100" />

		<!-- Initial probability of this malfunction occurring. (required)
		     This composite value is the sum of the weighted probabilities of
		     all items found in <repair-parts-list>. It is dynamically updated
		     as soon as new field reliability data becomes readily available.
		     To account for the trend of this malfunction, the new probability
		     will be calculated as the average between the previous one and
		     the newly calculated one. -->
		<!-- Values: 0.0 to 100.0 (100.0 = most likely) -->
		<malfunction-probability value="5.0" />

		<!-- The average general (non-EVA) repair time. (millisols) (optional) -->
		<repair-inside time="30.0" />

		<!-- Note: each of the expected repair time above will be
             computed based on a gaussian curve when this malfunction occurs. -->

		<!-- List of systems (or functions of a building) that are susceptible
		to this malfunction. (min 1 entity required) -->
		<system-list>
			<system name="habitable" />
			<system name="crew cabin" />
			<system name="farming" />
			<system name="life support" />
		</system-list>

		<!-- List of effects this malfunction can produce. (optional) -->
		<effect-list>

			<!-- Resource effects have a change rate for a given resource in inventory. -->
			<!-- Values: Change rate of resource in inventory. (kg/millisol) -->
			<!-- See resources.txt -->
			<effect type="resource" name="Oxygen" change-rate="-.01" />

			<!-- Life support effects have a change rate in life support provided. -->
			<!-- Values: Change rate of life support. (kg/millisol) -->
			<!-- See resources.txt -->
			<effect type="life-support" name="Oxygen" change-rate="-.01" />

			<!-- Life support effects have a change rate in life support provided. -->
			<!-- Values: Change rate of life support. (atm/millisol) -->
			<effect type="life-support" name="Air Pressure" change-rate="-.01" />
		</effect-list>

		<!-- List of medical injuries that can be immediately caused by this malfunction. (optional) -->
		<medical-complaint-list>
			<!-- See medical complaint names in medical.xml. -->
			<!-- Values: probability - the percentage probability that the complaint may happen. -->
			<medical-complaint name="Heartburn" medical-probability="10.0" />
		</medical-complaint-list>

		<!-- Repair parts required to fix this malfunction. (optional) -->
		<!-- See parts.xml -->
		<repair-parts-list>
			<!-- A part required for repairing this malfunction. -->
			<!-- number - the number of the part needed. -->
			<!-- repair-probability - the % repair probability that a new part will be
			     needed when swapping out the old part in a repair 
			     triggered by a malfunction.
			     Ideally speaking, all probability should sum up to be 
			     around 100%. Don't need to be exactly 100%
			     Note that this malfunction probability is apart from 
			     and not related to part reliability %, MTBF or 
			     failure rate of this item. -->
			<part name="airleak patch" number="2" repair-probability="75" />
			<part name="work glove" number="1" repair-probability="10" />
			<part name="fiberglass cloth" number="1" repair-probability="10" />
		</repair-parts-list>
	</malfunction>

	<malfunction name="Roof Leak">
		<severity value="90" />
		<malfunction-probability value="5.0" />
		<repair-inside time="50.0" />
		<system-list>
			<system name="farming" />
		</system-list>
		<effect-list>
			<effect type="resource" name="Oxygen" change-rate="-.01" />
			<effect type="life-support" name="Oxygen" change-rate="-.01" />
			<effect type="life-support" name="Air Pressure" change-rate="-.01" />
		</effect-list>
		<medical-complaint-list>
			<medical-complaint name="Heartburn" medical-probability="10.0" />
		</medical-complaint-list>
		<repair-parts-list>
			<part name="airleak patch" number="3" repair-probability="75" />
			<part name="work glove" number="1" repair-probability="15" />
			<part name="fiberglass cloth" number="1" repair-probability="5" />
			<part name="polycarbonate roofing" number="1" repair-probability="10" />
		</repair-parts-list>

	</malfunction>


	<!-- Leak in the water reserves. -->
	<malfunction name="Water Leak">
		<severity value="50" />
		<malfunction-probability value="3.0" />
		<repair-inside time="50.0" />
		<system-list>
			<system name="rover" />
			<system name="living accommodation" />
			<system name="farming" />
			<system name="manufacture" />
			<system name="cooking" />
		</system-list>
		<effect-list>
			<effect type="resource" name="Water" change-rate="-.1" />
		</effect-list>
		<repair-parts-list>
			<part name="gasket" number="1" repair-probability="15" />
			<part name="valve" number="1" repair-probability="15" />
			<part name="plastic tubing" number="2" repair-probability="15" />
			<part name="plastic bottle" number="1" repair-probability="15" />
			<part name="copper pipe" number="1" repair-probability="2" />
			<part name="water tank" number="1" repair-probability="3" />
			<part name="water pump small" number="1" repair-probability="15" />
		</repair-parts-list>
	</malfunction>

	<malfunction name="Battery Failure">
		<severity value="60" />
		<malfunction-probability value="2.0" />
		<repair-inside time="150.0" />
		<system-list>
			<system name="battery" />
			<system name="power storage" />
		</system-list>
		<medical-complaint-list>
			<medical-complaint name="Minor Burns" medical-probability="5.0" />
		</medical-complaint-list>
		<repair-parts-list>
			<part name="fire extinguisher" number="1" repair-probability="15" />
			<part name="oxygen pump" number="1" repair-probability="5" />
			<part name="heating element" number="1" repair-probability="5" />
			<part name="battery module" number="1" repair-probability="2" />
			<part name="valve" number="2" repair-probability="5" />
			<part name="electrical wire" number="2" repair-probability="5" />
			<part name="wire connector" number="2" repair-probability="5" />		
			<part name="work glove" number="1" repair-probability="10" />
		</repair-parts-list>
	</malfunction>

	<!-- Fuel Leak -->
	<malfunction name="Fuel Leak">
		<severity value="50" />
		<malfunction-probability value="3.0" />
		<repair-eva time="60.0" />
		<system-list>
			<system name="fuel heating source" />
			<system name="fuel power source" />
			<system name="methane fuel" />
		</system-list>
		<effect-list>
			<effect type="resource" name="Methane" change-rate="-.1" />
		</effect-list>
		<repair-parts-list>
			<part name="gasket" number="1" repair-probability="15" />
			<part name="valve" number="1" repair-probability="15" />
			<part name="plastic bottle" number="1" repair-probability="15" />
			<part name="plastic tubing" number="1" repair-probability="15" />
			<part name="fuel tank" number="1" repair-probability="10" />
			<part name="work glove" number="1" repair-probability="10" />
			<part name="decontamination kit" number="1" repair-probability="30" />
		</repair-parts-list>
	</malfunction>
	
	<malfunction name="Methanol Fuel Cell Failure">
		<severity value="80" />
		<malfunction-probability value="2.0" />
		<repair-inside time="150.0" />
		<system-list>
			<system name="methanol fuel" />
		</system-list>
		<medical-complaint-list>
			<medical-complaint name="Minor Burns" medical-probability="5.0" />
		</medical-complaint-list>
		<repair-parts-list>
			<part name="fire extinguisher" number="1" repair-probability="15" />
			<part name="oxygen pump" number="1" repair-probability="5" />
			<part name="fuel pump" number="1" repair-probability="5" />
			<part name="heating element" number="1" repair-probability="5" />
			<part name="gas tank" number="1" repair-probability="5" />
			<part name="fuel tank" number="1" repair-probability="5" />
			<part name="valve" number="2" repair-probability="5" />
			<part name="electrical wire" number="2" repair-probability="5" />
			<part name="wire connector" number="2" repair-probability="5" />
			<part name="methanol fuel cell" number="1" repair-probability="5" />
			<part name="methanol fuel cell stack" number="1" repair-probability="1" />			
			<part name="work glove" number="1" repair-probability="10" />
		</repair-parts-list>
	</malfunction>

	<malfunction name="Methane Fuel Cell Failure">
		<severity value="80" />
		<malfunction-probability value="2.0" />
		<repair-inside time="150.0" />
		<system-list>
			<system name="methane fuel" />
		</system-list>
		<medical-complaint-list>
			<medical-complaint name="Minor Burns" medical-probability="5.0" />
		</medical-complaint-list>
		<repair-parts-list>
			<part name="fire extinguisher" number="1" repair-probability="15" />
			<part name="oxygen pump" number="1" repair-probability="5" />
			<part name="fuel pump" number="1" repair-probability="5" />
			<part name="heating element" number="1" repair-probability="5" />
			<part name="gas tank" number="1" repair-probability="5" />
			<part name="fuel tank" number="1" repair-probability="5" />
			<part name="valve" number="2" repair-probability="5" />
			<part name="electrical wire" number="2" repair-probability="5" />
			<part name="wire connector" number="2" repair-probability="5" />
			<part name="methane fuel cell" number="1" repair-probability="5" />
			<part name="methane fuel cell stack" number="1" repair-probability="1" />			
			<part name="work glove" number="1" repair-probability="10" />
		</repair-parts-list>
	</malfunction>

	<!-- Class A Fire are fires in ordinary combustibles such as wood, paper,
		cloth, trash, and plastics. -->
	<malfunction name="Class A Combustible Fire">
		<severity value="60" />
		<malfunction-probability value="3.0" />
		<repair-inside time="40.0" repairers="4"/>
		<system-list>
			<system name="waste processing" />
			<system name="life support" />
		</system-list>
		<medical-complaint-list>
			<medical-complaint name="Minor Burns" medical-probability="5.0" />
		</medical-complaint-list>
		<repair-parts-list>
			<part name="fire extinguisher" number="2" repair-probability="35" />
			<part name="lubricant bottle" number="1" repair-probability="5" />
			<part name="plastic sheet" number="1" repair-probability="5" />
			<part name="fiberglass cloth" number="3" repair-probability="15" />
			<part name="heating element" number="2" repair-probability="20" />
			<part name="valve" number="2" repair-probability="5" />
			<part name="electrical wire" number="2" repair-probability="5" />
			<part name="wire connector" number="2" repair-probability="5" />
			<part name="work glove" number="1" repair-probability="10" />
		</repair-parts-list>
	</malfunction>

	<!-- Class B fires are caused by oxygen and flammable liquids such as methanol.  -->
	<malfunction name="Class B-1 Fuel Fire">
		<severity value="80" />
		<malfunction-probability value="2" />
		<repair-inside time="30.0" repairers="5"/>
		<system-list>
			<system name="methanol fuel" />
			<system name="cooking" />
			<system name="farming" />
			<system name="thermal generation" />
		</system-list>
		<effect-list>
			<effect type="life-support" name="Oxygen" change-rate="-.01" />
			<effect type="life-support" name="Temperature" change-rate="+.01" />
		</effect-list>
		<medical-complaint-list>
			<medical-complaint name="Minor Burns" medical-probability="15.0" />
			<medical-complaint name="Burns" medical-probability="5.0" />
		</medical-complaint-list>
		<repair-parts-list>
			<part name="fire extinguisher" number="2" repair-probability="45" />
			<part name="gas tank" number="1" repair-probability="5" />
			<part name="fuel tank" number="1" repair-probability="10" />
			<part name="methanol fuel cell" number="1" repair-probability="5" />
			<part name="methanol fuel cell stack" number="1" repair-probability="1" />
			<part name="aluminum sheet" number="1" repair-probability="5" />
			<part name="plastic sheet" number="1" repair-probability="5" />
			<part name="fiberglass" number="1" repair-probability="5" />
			<part name="plastic pipe" number="2" repair-probability="5" />
			<part name="valve" number="3" repair-probability="5" />
			<part name="electrical wire" number="2" repair-probability="5" />
			<part name="wire connector" number="2" repair-probability="5" />
			<part name="work glove" number="1" repair-probability="10" />
		</repair-parts-list>
	</malfunction>

	<!-- Class B-2 fires are caused by oxygen and flammable gases such as methane. -->
	<malfunction name="Class B-2 Fuel Fire">
		<severity value="80" />
		<malfunction-probability value="2" />
		<repair-inside time="30.0" repairers="5"/>
		<system-list>
			<system name="methane fuel" />
			<system name="cooking" />
			<system name="farming" />
			<system name="thermal generation" />
		</system-list>
		<effect-list>
			<effect type="life-support" name="Oxygen" change-rate="-.01" />
			<effect type="life-support" name="Temperature" change-rate="+.01" />
		</effect-list>
		<medical-complaint-list>
			<medical-complaint name="Minor Burns" medical-probability="15.0" />
			<medical-complaint name="Burns" medical-probability="5.0" />
		</medical-complaint-list>
		<repair-parts-list>
			<part name="fire extinguisher" number="2" repair-probability="45" />
			<part name="gas tank" number="1" repair-probability="5" />
			<part name="fuel tank" number="1" repair-probability="10" />
			<part name="methane fuel cell" number="1" repair-probability="5" />
			<part name="methane fuel cell stack" number="1" repair-probability="1" />
			<part name="aluminum sheet" number="1" repair-probability="5" />
			<part name="plastic sheet" number="1" repair-probability="5" />
			<part name="fiberglass" number="1" repair-probability="5" />
			<part name="plastic pipe" number="2" repair-probability="5" />
			<part name="valve" number="3" repair-probability="5" />
			<part name="electrical wire" number="2" repair-probability="5" />
			<part name="wire connector" number="2" repair-probability="5" />
			<part name="work glove" number="1" repair-probability="10" />
		</repair-parts-list>
	</malfunction>
	
	<!-- Class C fires are fires involving energized electrical equipment such
		as motors, transformers, and appliances. -->
	<malfunction name="Class C Electrical Fire">
		<severity value="100" />
		<malfunction-probability value="1" />
		<repair-inside time="40.0" repairers="6"/>
		<system-list>
			<system name="power generation" />
			<system name="power storage" />
		</system-list>
		<effect-list>
			<effect type="life-support" name="Oxygen" change-rate="-.01" />
			<effect type="life-support" name="Temperature" change-rate="+.02" />
		</effect-list>
		<medical-complaint-list>
			<medical-complaint name="Minor Burns" medical-probability="30.0" />
			<medical-complaint name="Burns" medical-probability="15.0" />
			<medical-complaint name="Major Burns" medical-probability="5.0" />
		</medical-complaint-list>
		<repair-parts-list>
			<part name="fire extinguisher" number="2" repair-probability="30" />
			<part name="power cable" number="2" repair-probability="5" />
			<part name="aluminum sheet" number="2" repair-probability="5" />
			<part name="heating element" number="2" repair-probability="5" />
			<part name="logic board" number="3" repair-probability="1" />
			<part name="valve" number="4" repair-probability="5" />
			<part name="electrical wire" number="5" repair-probability="10" />
			<part name="wire connector" number="5" repair-probability="20" />
			<part name="work glove" number="1" repair-probability="10" />
			<part name="transformer" number="1" repair-probability="1" />			
		</repair-parts-list>
	</malfunction>

	<!-- Class D fires are fires in combustible metals such as potassium,
		sodium, aluminum, and magnesium. -->
	<malfunction name="Class D Metal Fire">
		<severity value="100" />
		<malfunction-probability value="1" />
		<repair-inside time="30.0" repairers="6"/>
		<system-list>
			<system name="metallic element" />
		</system-list>
		<effect-list>
			<effect type="life-support" name="Oxygen" change-rate="-.01" />
			<effect type="life-support" name="Temperature" change-rate="+.02" />
		</effect-list>
		<medical-complaint-list>
			<medical-complaint name="Minor Burns" medical-probability="30.0" />
			<medical-complaint name="Burns" medical-probability="15.0" />
			<medical-complaint name="Major Burns" medical-probability="5.0" />
		</medical-complaint-list>
		<repair-parts-list>
			<part name="fire extinguisher" number="3" repair-probability="35" />
			<part name="steel sheet" number="2" repair-probability="10" />
			<part name="aluminum sheet" number="2" repair-probability="10" />
			<part name="plastic sheet" number="2" repair-probability="5" />
			<part name="fiberglass" number="2" repair-probability="5" />
			<part name="plastic pipe" number="4" repair-probability="5" />
			<part name="valve" number="4" repair-probability="5" />
			<part name="electrical wire" number="4" repair-probability="5" />
			<part name="wire connector" number="4" repair-probability="5" />
			<part name="plastic bottle" number="1" repair-probability="15" />
			<part name="work glove" number="1" repair-probability="10" />
			<part name="decontamination kit" number="1" repair-probability="30" />
		</repair-parts-list>
	</malfunction>

	<!-- Class K fires involving cooking oils and greases such as animals
		fats and vegetable fats. -->
	<malfunction name="Class K Oil Fire">
		<severity value="100" />
		<malfunction-probability value="1" />
		<repair-inside time="40.0"/>
		<system-list>
			<system name="cooking" />
			<system name="food production" />
		</system-list>
		<effect-list>
			<effect type="life-support" name="Oxygen" change-rate="-.01" />
			<effect type="life-support" name="Temperature" change-rate="+.02" />
		</effect-list>
		<medical-complaint-list>
			<medical-complaint name="Minor Burns" medical-probability="30.0" />
			<medical-complaint name="Burns" medical-probability="15.0" />
			<medical-complaint name="Major Burns" medical-probability="5.0" />
		</medical-complaint-list>
		<repair-parts-list>
			<part name="fire extinguisher" number="3" repair-probability="35" />
			<part name="ventilation fan" number="1" repair-probability="10" />
			<part name="blender" number="1" repair-probability="10" />
			<part name="refrigerator" number="1" repair-probability="5" />
			<part name="autoclave" number="1" repair-probability="5" />
			<part name="microwave" number="1" repair-probability="5" />
			<part name="oven" number="1" repair-probability="5" />
			<part name="electrical wire" number="4" repair-probability="5" />
			<part name="wire connector" number="4" repair-probability="5" />
			<part name="fuel tank" number="1" repair-probability="5" />
			<part name="work glove" number="1" repair-probability="10" />
			<part name="decontamination kit" number="1" repair-probability="15" />
		</repair-parts-list>
	</malfunction>

	<!-- Damaged wheel on cargo rover. -->
	<malfunction name="Cargo Rover Damaged Wheel">
		<severity value="65" />
		<malfunction-probability value="5.0" />
		<repair-eva time="50.0" />
		<system-list>
			<system name="cargo rover" />
		</system-list>
		<repair-parts-list>
			<part name="rover wheel" number="2" repair-probability="20" />
			<part name="steel wire" number="4" repair-probability="20" />
			<part name="work glove" number="1" repair-probability="20" />
			<part name="valve" number="1" repair-probability="10" />
			<part name="plastic tubing" number="2" repair-probability="10" />
			<part name="plastic bottle" number="1" repair-probability="10" />
			<part name="heat pipe" number="1" repair-probability="5" />
		</repair-parts-list>
	</malfunction>
	
	<!-- Damaged wheel on transport rover. -->
	<malfunction name="Transport Rover Damaged Wheel">
		<severity value="65" />
		<malfunction-probability value="5.0" />
		<repair-eva time="50.0" />
		<system-list>
			<system name="transport rover" />
		</system-list>
		<repair-parts-list>
			<part name="rover wheel" number="2" repair-probability="20" />
			<part name="steel wire" number="4" repair-probability="20" />			
			<part name="work glove" number="1" repair-probability="10" />
			<part name="valve" number="1" repair-probability="10" />
			<part name="plastic tubing" number="2" repair-probability="10" />
			<part name="plastic bottle" number="1" repair-probability="10" />
			<part name="heat pipe" number="1" repair-probability="5" />
		</repair-parts-list>
	</malfunction>
	
	<!-- Damaged wheel on explorer rover. -->
	<malfunction name="Explorer Rover Damaged Wheel">
		<severity value="65" />
		<malfunction-probability value="5.0" />
		<repair-eva time="50.0" />
		<system-list>
			<system name="explorer rover" />	
		</system-list>
		<repair-parts-list>
			<part name="rover wheel" number="1" repair-probability="20" />
			<part name="steel wire" number="2" repair-probability="20" />			
			<part name="work glove" number="1" repair-probability="20" />
			<part name="valve" number="1" repair-probability="10" />
			<part name="plastic tubing" number="2" repair-probability="10" />
			<part name="plastic bottle" number="1" repair-probability="10" />
			<part name="heat pipe" number="1" repair-probability="5" />
		</repair-parts-list>
	</malfunction>

	<!-- Damaged wheel on LUV. -->
	<malfunction name="LUV Damaged Wheel">
		<severity value="65" />
		<malfunction-probability value="5.0" />
		<repair-eva time="50.0" />
		<system-list>
			<system name="light utility vehicle" />
		</system-list>
		<repair-parts-list>
			<part name="wheel small" number="1" repair-probability="20" />
			<part name="steel wire" number="1" repair-probability="20" />			
			<part name="work glove" number="1" repair-probability="10" />
			<part name="valve" number="1" repair-probability="10" />
			<part name="plastic tubing" number="2" repair-probability="10" />
			<part name="plastic bottle" number="1" repair-probability="10" />
			<part name="heat pipe" number="1" repair-probability="5" />
		</repair-parts-list>
	</malfunction>

	<!-- Problems with the generator. -->
	<malfunction name="Generator Problems">
		<severity value="50" />
		<malfunction-probability value="2.0" />
		<repair-inside time="50.0" />
		<system-list>
			<system name="vehicle" />
			<system name="power generation" />
		</system-list>
		<repair-parts-list>
			<part name="gasket" number="1" repair-probability="10" />
			<part name="spark plug" number="1" repair-probability="15" />
			<part name="coolant bottle" number="2" repair-probability="10" />
			<part name="electrical wire" number="2" repair-probability="25" />
			<part name="wire connector" number="2" repair-probability="25" />
			<part name="plastic tubing" number="1" repair-probability="5" />
			<part name="lubricant bottle" number="1" repair-probability="5" />
			<part name="timing belt" number="1" repair-probability="5" />
			<part name="methane fuel cell stack" number="1" repair-probability="2" />
			<part name="logic board" number="1" repair-probability="2" />
			<part name="valve" number="1" repair-probability="10" />
			<part name="steel pipe" number="1" repair-probability="5" />
			<part name="power cable" number="1" repair-probability="5" />
		</repair-parts-list>
	</malfunction>

	<!-- Rover Power failure. -->
	<malfunction name="Vehicle Power System Failure">
		<severity value="40" />
		<malfunction-probability value="2.0" />
		<repair-inside time="50.0" />
		<system-list>
			<system name="vehicle" />
		</system-list>
		<medical-complaint-list>
			<medical-complaint name="Minor Burns" medical-probability="3.0" />
		</medical-complaint-list>
		<repair-parts-list>
			<part name="wire connector" number="2" repair-probability="40" />
			<part name="electrical wire" number="2" repair-probability="40" />
			<part name="battery module" number="1" repair-probability="2" />
			<part name="microcontroller" number="1" repair-probability="1" />
			<part name="logic board" number="1" repair-probability="5" />
			<part name="power cable" number="1" repair-probability="5" />
			<part name="Surge Protector" number="1" repair-probability="5" />	
			<part name="fire extinguisher" number="1" repair-probability="30" />
		</repair-parts-list>
	</malfunction>

	<!-- Power failure. -->
	<malfunction name="Power System Failure">
		<severity value="40" />
		<malfunction-probability value="3.0" />
		<repair-inside time="100.0" />
		<system-list>
			<system name="power storage" />
			<system name="power generation" />
		</system-list>
		<medical-complaint-list>
			<medical-complaint name="Minor Burns" medical-probability="3.0" />
		</medical-complaint-list>
		<repair-parts-list>
			<part name="wire connector" number="2" repair-probability="40" />
			<part name="electrical wire" number="2" repair-probability="40" />
			<part name="battery module" number="1" repair-probability="2" />
			<part name="microcontroller" number="1" repair-probability="1" />
			<part name="power cable" number="2" repair-probability="10" />
			<part name="Power Panel" number="1" repair-probability="5" />	
			<part name="fire extinguisher" number="1" repair-probability="30" />
		</repair-parts-list>
	</malfunction>

		<!-- EVA Power failure. -->
	<malfunction name="EVA Power Failure">
		<severity value="40" />
		<malfunction-probability value="3.0" />
		<repair-inside time="50.0" />
		<system-list>
			<system name="eva" />
		</system-list>
		<medical-complaint-list>
			<medical-complaint name="Minor Burns" medical-probability="3.0" />
		</medical-complaint-list>
		<repair-parts-list>
			<part name="wire connector" number="2" repair-probability="40" />
			<part name="electrical wire" number="2" repair-probability="40" />
			<part name="eva battery" number="1" repair-probability="2" />
			<part name="microcontroller" number="1" repair-probability="1" />
			<part name="logic board" number="1" repair-probability="5" />
		</repair-parts-list>
	</malfunction>

	<!-- Communication system failure. -->
	<malfunction name="Communication System Failure">
		<severity value="35" />
		<malfunction-probability value="5.0" />
		<repair-inside time="50.0" />
		<repair-eva time="50.0" />
		<system-list>
			<system name="vehicle" />
			<system name="communication" />
		</system-list>
		<repair-parts-list>
			<part name="wire connector" number="2" repair-probability="25" />
			<part name="electrical wire" number="2" repair-probability="15" />
			<part name="radio antenna" number="1" repair-probability="10" />
			<part name="satellite dish" number="1" repair-probability="3" />
			<part name="communications circuit board" number="1" repair-probability="10" />
			<part name="microcontroller" number="1" repair-probability="1" />
			<part name="logic board" number="1" repair-probability="5" />
			<part name="power transistor" number="1" repair-probability="3" />
			<part name="optical cable" number="1" repair-probability="3" />
		</repair-parts-list>
	</malfunction>

	<!-- Navigation system failure. -->
	<malfunction name="Navigation System Failure">
		<severity value="15" />
		<malfunction-probability value="2.0" />
		<repair-inside time="50.0" />
		<repair-eva time="20.0" />
		<system-list>
			<system name="rover" />
		</system-list>
		<repair-parts-list>
			<part name="wire connector" number="2" repair-probability="25" />
			<part name="electrical wire" number="2" repair-probability="25" />
			<part name="satellite dish" number="1" repair-probability="3" />
			<part name="navigation circuit board" number="1" repair-probability="10" />
			<part name="microcontroller" number="1" repair-probability="1" />
			<part name="logic board" number="1" repair-probability="5" />
			<part name="power transistor" number="1" repair-probability="3" />
		</repair-parts-list>
	</malfunction>

	<malfunction name="Rover Control Malfunction">
		<severity value="35" />
		<malfunction-probability value="2.0" />
		<repair-inside time="100.0" />
		<system-list>
			<system name="rover" />
		</system-list>
		<repair-parts-list>
			<part name="wire connector" number="2" repair-probability="30" />
			<part name="electrical wire" number="2" repair-probability="40" />
			<part name="light emitting diode kit" number="1" repair-probability="10" />
			<part name="logic board" number="1" repair-probability="5" />
			<part name="microcontroller" number="1" repair-probability="1" />
			<part name="navigation circuit board" number="1" repair-probability="5" />