<?xml version = "1.0" encoding = "UTF-8" standalone = "yes" ?>
<!DOCTYPE manufacturing-processes [
	<!ELEMENT manufacturing-processes (tooling, process*, salvage*)>
	
	<!ELEMENT tooling (tool*)>
	<!ELEMENT tool EMPTY>
	<!ATTLIST tool name CDATA #REQUIRED>
	<!ATTLIST tool description CDATA #REQUIRED>
	<!ELEMENT process (description?, inputs, outputs)>
	<!ATTLIST process name CDATA #REQUIRED>
	<!ATTLIST process tech CDATA #REQUIRED>
	<!ATTLIST process skill CDATA #REQUIRED>
	<!ATTLIST process work-time CDATA #REQUIRED>
	<!ATTLIST process process-time CDATA #IMPLIED>
	<!ATTLIST process tooling CDATA #IMPLIED>
	<!ATTLIST process power-required CDATA #REQUIRED>
	<!ELEMENT description (#PCDATA)>
	<!ELEMENT inputs (resource*, part*)>
	<!ELEMENT outputs (resource*, part*, equipment*, bin*, vehicle*, robot*)>
	<!ELEMENT resource (alternative*)>
	<!ATTLIST resource name CDATA #REQUIRED>
	<!ATTLIST resource amount CDATA #REQUIRED>
	<!ELEMENT alternative EMPTY>
	<!ATTLIST alternative name CDATA #REQUIRED>
	<!ATTLIST alternative amount CDATA #REQUIRED>
	<!ELEMENT part EMPTY>
	<!ATTLIST part name CDATA #REQUIRED>
	<!ATTLIST part number CDATA #REQUIRED>
	<!ELEMENT equipment EMPTY>
	<!ATTLIST equipment name CDATA #REQUIRED>
	<!ATTLIST equipment number CDATA #REQUIRED>
	<!ELEMENT bin EMPTY>
	<!ATTLIST bin name CDATA #REQUIRED>
	<!ATTLIST bin number CDATA #REQUIRED>
	<!ELEMENT vehicle EMPTY>
	<!ATTLIST vehicle name CDATA #REQUIRED>
	<!ATTLIST vehicle number CDATA #REQUIRED>
	
	<!ELEMENT robot EMPTY>
	<!ATTLIST robot name CDATA #REQUIRED>
	<!ATTLIST robot number CDATA #REQUIRED>
	
	<!ELEMENT salvage (part-salvage*)>
	<!ATTLIST salvage item-name CDATA #REQUIRED>
	<!ATTLIST salvage type (equipment|vehicle) #REQUIRED>
	<!ATTLIST salvage tech CDATA #REQUIRED>
	<!ATTLIST salvage skill CDATA #REQUIRED>
	<!ATTLIST salvage work-time CDATA #REQUIRED>
	<!ELEMENT part-salvage EMPTY>
	<!ATTLIST part-salvage name CDATA #REQUIRED>
	<!ATTLIST part-salvage number CDATA #REQUIRED>
]>

<!--
1. A Chemical Approach to C02 Util on Mars
http://www.uapress.arizona.edu/onlinebks/ResourcesNearEarthSpace/resources28.pdf

2. Regolith composition :
http://canada.marssociety.org/winnipeg/soil.html
 -->

<!-- List of all manufacturing processes. -->
<manufacturing-processes>
	<tooling>
		<tool name="3D Printer" description="Generic 3D printer" />
		<tool name="Chemical" description="Ability to perform chemical reactions and transformations" />
		<tool name="Furnace" description="Equipment used to bake or melt materials" />		
		<tool name="Lifting" description="Lifting equipment for working on large items" />
		<tool name="Metalwork" description="Tools to shape and construct metal items" />
		<tool name="Soldering" description="Assembling various electrical parts together" />
	</tooling>

<!-- 
 work-time means the amount of time it takes for settlers to examine, operate and direct this process.
 process-time means the amount of time it takes for the output resource to be synthesized.
-->
	
<!--
	Note: In earth's ocean, the most common compound found in brine water are magnesium chloride, magnesium sulfate,
	calcium sulfate, potassium chloride, magnesium bromide, and calcium carbonate.
-->
	<!-- Purify Rock Salt to Food Grade Table Salt -->
	<process name="Purify rock salt into compounds"
	tech="1" skill="1" work-time="10.0" process-time="10"
			tooling="chemical" power-required=".4">
		<description> http://www.madehow.com/Volume-2/Salt.html
			One method of evaporating brine is solar evaporation.
			Most brine is processed by a multiple-effect vacuum evaporator.
			This device consists of three or more closed metal cylinders with conical bottoms.
			Brine is first treated chemically to remove calcium and magnesium compounds.
			It then fills the bottom.
			Brine may also be processed in a grainer.
		</description>
		<inputs>
			<resource name="rock salt" amount="7.5" />
		</inputs>
		<outputs>
			<resource name="table salt" amount="1.5" />
			<resource name="calcium" amount="0.5" />
			<resource name="magnesium" amount="0.5" />
			<resource name="potassium" amount="0.5" />
			<resource name="calcium carbonate" amount="1.0" />
			<resource name="sodium carbonate" amount="1.0" />
			<resource name="calcium sulfate" amount="0.5" />
			<!--Epsom Salt is Magnesium Sulfate-->			
			<resource name="epsom salt" amount="0.5" />
			<resource name="perchlorate" amount="1.5" />
		</outputs>
	</process>

	<process name="Make pulp from cane fiber and crop waste"
			tech="2" skill="0"
			work-time="50"
			process-time="300"
			power-required=".1">
		<inputs>
			<resource name="Cane fiber" amount="2.5" />
			<resource name="crop waste" amount="2.5" />
			<resource name="water" amount="1" />
		</inputs>
		<outputs>
			<resource name="pulp" amount="5.5" />
			<resource name="grey water" amount=".4" />
			<resource name="solid waste" amount=".1" />
		</outputs>
	</process>

	<process name="Make pulp from cane fiber and crop waste (large batch)"
			tech="2" skill="2"
			work-time="200"
			process-time="800"
			power-required=".5">
		<inputs>
			<resource name="Cane Fiber" amount="25" />
			<resource name="crop waste" amount="25" />
			<resource name="water" amount="10" />
		</inputs>
		<outputs>
			<resource name="pulp" amount="55" />
			<resource name="grey water" amount="4" />
			<resource name="solid waste" amount="1" />
		</outputs>
	</process>

	<process name="Make paper, napkin and toilet tissue from pulp"
			tech="1" skill="1"
			work-time="50"
			process-time="100"
			power-required=".1">
		<inputs>
			<resource name="pulp" amount="5" />
			<resource name="bleaching chemical" amount=".05" />
			<resource name="calcium sulfate" amount=".05" />
		</inputs>
		<outputs>
			<resource name="paper" amount="1" />
			<resource name="napkin" amount="2" />
			<resource name="toilet tissue" amount="2" />
		</outputs>
	</process>

	<process name="Make paper, napkin and toilet tissue from pulp (large batch)"
			tech="1" skill="1"
			work-time="150"
			process-time="500"
			power-required=".5">
		<inputs>
			<resource name="pulp" amount="50" />
			<resource name="bleaching chemical" amount=".5" />
			<resource name="calcium sulfate" amount=".5" />
		</inputs>
		<outputs>
			<resource name="paper" amount="10" />
			<resource name="napkin" amount="20" />
			<resource name="toilet tissue" amount="20" />
		</outputs>
	</process>

	<!-- http://www.paperonweb.com/chemical.htm
		CHEMICALS USED IN PULP &PAPER MANUFACTURING AND COATING
		Over 3000 different types of chemicals "can be used" in papermaking, in practice only about 200 individual chemicals
		 are typically used, each satisfying a specific need.
		 -->

	<process name="Make bleaching chemical for paper making"
			tech="2" skill="1"
			work-time="50"
			process-time="200" tooling="chemical"
			power-required=".3">
		<inputs>
			<resource name="oxygen" amount="2" />
			<resource name="sulfur" amount=".5" />
			<resource name="ammonia" amount=".5" />
			<resource name="sodium hypochlorite" amount=".5" />
			<resource name="calcium carbonate" amount="1" />
			<resource name="magnesium" amount=".5" />
		</inputs>
		<outputs>
			<resource name="bleaching chemical" amount="5" />
		</outputs>
	</process>
	
	<process name="Make bleaching chemical for paper making (large batch)"
			tech="2" skill="1"
			work-time="50"
			process-time="200" tooling="chemical"
			power-required=".3">
		<inputs>
			<resource name="oxygen" amount="20" />
			<resource name="sulfur" amount="5" />
			<resource name="ammonia" amount="5" />
			<resource name="sodium hypochlorite" amount="5" />
			<resource name="calcium carbonate" amount="10" />
			<resource name="magnesium" amount="5" />
		</inputs>
		<outputs>
			<resource name="bleaching chemical" amount="50" />
		</outputs>
	</process>

<!-- https://en.wiki2.org/wiki/Electrochlorination
		NaCl + H2O + ENERGY → NaOCl + H2 energy is added to sodium chloride (table salt) in water, resulting in sodium hypochlorite and hydrogen gas.
Note: 1 kg of H2 is 14.13 liter
-->
	<process name="Make sodium hypochlorite for bleaching and sanitation"
			tech="2" skill="1"
			work-time="10"
			process-time="100" tooling="chemical"
			power-required=".1">
		<inputs>
			<resource name="table salt" amount="5.85" />
			<resource name="water" amount="1.8" />

		</inputs>
		<outputs>
			<resource name="sodium hypochlorite" amount="7.45" />
			<resource name="hydrogen" amount=".2" />
		</outputs>
	</process>

	<process name="Make sodium hypochlorite for bleaching and sanitation (large batch)"
			tech="2" skill="1"
			work-time="50"
			process-time="400" tooling="chemical"
			power-required=".5">
		<inputs>
			<resource name="table salt" amount="58.5" />
			<resource name="water" amount="18" />

		</inputs>
		<outputs>
			<resource name="sodium hypochlorite" amount="74.5" />
			<resource name="hydrogen" amount="2" />
		</outputs>
	</process>

	<process name="Make cleaning agent"
			tech="2" skill="1"
			work-time="10"
			process-time="50" tooling="chemical"
			power-required=".1">
		<inputs>
			<resource name="Acetic acid" amount="4.5" >
				<alternative name="Baking soda" amount="4.5" />
				<alternative name="Perchlorate" amount="4.5" />
				<alternative name="Potash lye" amount="4.5" />
				<alternative name="Ammonia" amount="4.5" />
				<alternative name="Chlorine" amount="4.5" />	
				<alternative name="Sodium carbonate" amount="4.5" />	
				<alternative name="Rice vinegar" amount="4.5" />			
			</resource>	
			<resource name="Bleaching chemical" amount="0.5" >
				<alternative name="Sodium hypochlorite" amount="0.5" />			
			</resource>	
		</inputs>
		<outputs>
			<resource name="Cleaning agent" amount="5.0" />
		</outputs>
	</process>
	
	<process name="Make hydrogen peroxide"
			tech="1" skill="2"
			work-time="5"
			process-time="68" tooling="chemical"
			power-required=".1">
			<!-- May use palladium-gold catalysts, minimizing waste 
			and avoiding the complex, energy-intensive anthraquinone process -->
		<inputs>
			<resource name="oxygen" amount="32.0" />
			<resource name="hydrogen" amount="2.0" />
		</inputs>
		<outputs>
			<resource name="hydrogen peroxide" amount="34" />
		</outputs>
	</process>

	<process name="Make triglyceride"
			tech="1" skill="2"
			work-time="5"
			process-time="30" tooling="chemical"
			power-required=".1">
		<description> 
			May use palladium-gold catalysts, minimizing waste 
			and avoiding the complex, energy-intensive anthraquinone process.
			
			Assume 50% conversion rate
		</description>
		<inputs>
			<resource name="Soybean oil" amount="10.0"  >
				<alternative name="Sesame oil" amount="10.0" />
				<alternative name="Peanut oil" amount="10.0" />
				<alternative name="Rice bran oil" amount="10.0" />
				<alternative name="Garlic oil" amount="10.0" />
				<alternative name="Olive oil" amount="10.0" />
				<alternative name="Fish oil" amount="10.0" />
			</resource>	
		</inputs>
		<outputs>
			<resource name="Triglyceride" amount="5.0" />
			<resource name="Food waste" amount="5.0" />
		</outputs>
	</process>
		
	<process name="Break down meteorite"
			tech="1" skill="2"
			work-time="30"
			process-time="30" tooling="chemical"
			power-required=".1">
		<description> 
			Gold has been detected in trace amounts in Martian meteorites 
			known as SNCs, which are samples of the planet analyzed on Earth.
 
 			These meteorites contain various elements, including gold, 
 			alongside magnesium, aluminum, titanium, iron, and chromium.

		</description>
		<inputs>
			<resource name="Meteorite" amount="18.0" />	
		</inputs>
		<outputs>
			<resource name="Aluminum" amount="1.0" />		
			<resource name="Chromium" amount="1.0" />	
			<resource name="Copper" amount="1.0" />	
			<resource name="Gold" amount="1.0" />	
			<resource name="Iron oxide" amount="1.0" />	
			
			<resource name="Lithium" amount="1.0" />	
			<resource name="Magnesium" amount="1.0" />	
			<resource name="Manganese" amount="1.0" />	
			<resource name="Nickel" amount="1.0" />	
			<resource name="Phosphorus" amount="1.0" />	
			
			<resource name="Platinum" amount="1.0" />	
			<resource name="Potassium" amount="1.0" />	
			<resource name="Scandium" amount="1.0" />	
			<resource name="Silver" amount="1.0" />	
			<resource name="Tin" amount="1.0" />	
			
			<resource name="Titanium" amount="1.0" />	
			<resource name="Vanadium" amount="1.0" />	
			<resource name="Zinc" amount="1.0" />
		</outputs>
	</process>
				
				
	<process name="Make crop fertilizers"
			tech="2" skill="1"
			work-time="10"
			process-time="10" tooling="chemical"
			power-required="0.1">
		<description> 
			An arbitrary N-P-K-ratio (the percentage the product contains by volume of nitrogen (N), phosphorus (P), and potassium (K)) is used.		
			A. 3 main macronutrients (NPK):
				a. Nitrogen (N): leaf growth; 
				b. Phosphorus (P): development of roots, flowers, seeds, fruit;
				c. Potassium (K): strong stem growth, movement of water in plants, promotion of flowering and fruiting;
			B. 3 secondary macronutrients: 
				a. calcium (Ca), magnesium (Mg), and sulfur (S);
			C. Micronutrients: 
				a. copper (Cu), iron (Fe), manganese (Mn), molybdenum (Mo), zinc (Zn), boron (B). 
			D. Of occasional significance are silicon (Si), cobalt (Co), and vanadium (V).
		</description> 	
		<inputs>
			<resource name="Compost" amount="0.5" >
				<alternative name="Crop Waste" amount="0.5" />
			</resource>	
			<resource name="Nitrate" amount="0.5" >
				<alternative name="Nitrite" amount="0.5" />
				<alternative name="Ammonia" amount="0.5" />
			</resource>
			<resource name="Potassium" amount="0.5" >
				<alternative name="potash lye" amount="0.5" />
			</resource>
			<resource name="Phosphorus" amount="0.5" />
			<resource name="Nitrosomonas SPP" amount=".05">
				<alternative name="Nitrospira SPP" amount=".05" />
				<alternative name="Rhizobia" amount=".05" />
			</resource>
			<resource name="calcium" amount="0.02" />
			<resource name="magnesium" amount="0.02" />
			<resource name="sulfur" amount="0.02" />
			
			<resource name="zinc" amount="0.02">
				<alternative name="iron powder" amount="0.02" />
				<alternative name="copper" amount="0.02" />
			</resource>
			<resource name="methane" amount="1">
				<alternative name="hydrogen" amount="1" />
			</resource>
		</inputs>
		<outputs>
			<resource name="Fertilizer" amount="3" />
		</outputs>
	</process>

	<process name="Make Nitrites"
			tech="1" skill="1"
			work-time="5"
			process-time="5" tooling="chemical"
			power-required="0.01">
		<description> 
			1 mole of N2 : 14 g
			1 mole of O2 : 16 g
			For Nitrite NO2(-1) 
			14 g/mole N + 32 g/mole O = 46 g/mole NO2(-1) 
			
		</description>

		<inputs>
			<resource name="oxygen" amount="3.2" />
			<resource name="nitrogen" amount="1.4" />
		</inputs>
		<outputs>
			<resource name="nitrite" amount="4.6" />
		</outputs>
	</process>

	<process name="Make Nitrates"
			tech="1" skill="1"
			work-time="5"
			process-time="5" tooling="chemical"
			power-required="0.01">
		<description> 
			1 mole of N2 : 14 g
			1 mole of O2 : 16 g
			For Nitrate NO3(-2) 
			14 g/mole N + 48 g/mole O = 62 g/mole NO3(-2) 
			
		</description>

		<inputs>
			<resource name="oxygen" amount="4.8" />
			<resource name="nitrogen" amount="1.4" />
		</inputs>
		<outputs>
			<resource name="nitrite" amount="6.2" />
		</outputs>
	</process>
	
	<process name="Do carbon monoxide iron reduction"
			tech="1" skill="1"
			work-time="5"
			process-time="50" tooling="chemical"
			power-required=".2">
		<description>Fe&lt;sub&gt;2&lt;/sub&gt;O&lt;sub&gt;3&lt;/sub&gt; + 3CO -> 2Fe + 3CO&lt;sub&gt;2&lt;/sub&gt;</description>
		<inputs>
			<resource name="iron oxide" amount="50.0" />
			<resource name="carbon monoxide" amount="26.4" />
		</inputs>
		<outputs>
			<resource name="iron powder" amount="34.9" />
			<resource name="carbon dioxide" amount="41.3" />
		</outputs>
	</process>

	<process name="Do hydrogen iron reduction"
			tech="1" skill="1"
			work-time="5"
			process-time="50" tooling="chemical"
			power-required=".2">
		<description>Fe&lt;sub&gt;2&lt;/sub&gt;O&lt;sub&gt;3&lt;/sub&gt; + 3H&lt;sub&gt;2&lt;/sub&gt;
		-> 2Fe + 3H&lt;sub&gt;2&lt;/sub&gt;O</description>
		<inputs>
			<resource name="iron oxide" amount="50.0" />
			<resource name="hydrogen" amount="2.5" />
		</inputs>
		<outputs>
			<resource name="iron powder" amount="34.9" />
			<resource name="grey water" amount="16.9" />
		</outputs>
	</process>

	<!-- Produces 5x 5kg iron ingots. -->
	<process name="Cast iron ingot" tech="1" skill="2" work-time="25" process-time="75" tooling="furnace"
			power-required=".2">
		<inputs>
			<resource name="iron powder" amount="35.0" />
		</inputs>
		<outputs>
			<part name="iron ingot" number="5" />
		</outputs>
	</process>


	<!-- Produces 1m x 1m x 1mm (7.85kg) sheet of iron. -->
	<process name="Make iron sheet" tech="1" skill="2" work-time="50" process-time="200" tooling="metalwork"
			power-required=".5">
		<inputs>
			<resource name="iron powder" amount="15.7" />
		</inputs>
		<outputs>
			<part name="iron sheet" number="2" />
		</outputs>
	</process>

	<!-- Produces 1m x 1m x 1mm (7.85kg) sheet of iron. -->
	<process name="Roll iron sheet" tech="1" skill="2" work-time="50" process-time="200" tooling="metalwork"
			power-required=".5">
		<inputs>
			<part name="iron ingot" number="8" />
		</inputs>
		<outputs>
			<resource name="iron powder" amount="1.05" />		
			<part name="iron sheet" number="7" />	
		</outputs>
	</process>

	<!-- Produces one 5kg aluminum ingots. -->
	<process name="Cast aluminum ingot"
			tech="1" skill="1"
			work-time="50"
			process-time="50" tooling="furnace"
			power-required=".2">
		<description>Al&lt;sub&gt;2&lt;/sub&gt;O&lt;sub&gt;3&lt;/sub&gt; + 3C -> 2Al + 3CO; 
		1 mole - Al2CO3: 101.96g; 3C: 36g; 2Al: 54g; 3CO: 64g</description>
		<inputs>
			<resource name="aluminum oxide" amount="9.44" />
			<resource name="Carbon" amount="3.33" />
		</inputs>
		<outputs>
			<resource name="carbon monoxide" amount="7.78" />
			<part name="aluminum ingot" number="1" />
		</outputs>
	</process>

	<!-- Produces 50x 1kg aluminum ingots. -->
	<process name="Cast aluminum ingot (large batch)" tech="1" skill="1" work-time="250" process-time="250"
			tooling="furnace"
			power-required="1">
		<description>Al&lt;sub&gt;2&lt;/sub&gt;O&lt;sub&gt;3&lt;/sub&gt; + 3C -> 2Al + 3CO</description>
		<inputs>
			<resource name="aluminum oxide" amount="94.4" />
			<resource name="Carbon" amount="33.3" />
		</inputs>
		<outputs>
			<resource name="carbon monoxide" amount="77.8" />
			<part name="aluminum ingot" number="10" />
		</outputs>
	</process>

	<!-- Produces 1m x 2m x 1mm (5kg) sheet of aluminum. -->
	<process name="Make aluminum sheet" tech="1" skill="1" work-time="50" process-time="20" tooling="metalwork"
			power-required=".7">
		<description>Al&lt;sub&gt;2&lt;/sub&gt;O&lt;sub&gt;3&lt;/sub&gt; + 3C -> 2Al + 3CO</description>
		<inputs>
			<resource name="aluminum oxide" amount="9.5" />
			<resource name="Carbon" amount="3.0" />
		</inputs>
		<outputs>
			<resource name="carbon monoxide" amount="7.5" />
			<part name="aluminum sheet" number="1" />
		</outputs>
	</process>

	<!-- Produces 1m x 1m x 1mm (2.72kg) sheet of aluminum. Each Al ingot is 5kg-->
	<process name="Roll aluminum sheet" tech="1" skill="1" work-time="50" process-time="20" tooling="metalwork"
			power-required=".4">
		<inputs>
			<part name="aluminum ingot" number="2" />
		</inputs>
		<outputs>
			<resource name="aluminum oxide" amount="1.84" />
			<part name="aluminum sheet" number="3" />
		</outputs>
	</process>

	<!-- Produces 5 5kg steel ingots. -->
	<process name="Do steel ingot alloying" tech="1" skill="1" work-time="10" process-time="20" tooling="furnace"
			power-required=".1">
		<inputs>
			<resource name="iron powder" amount="25.0" />
			<resource name="Carbon" amount=".5" />
		</inputs>
		<outputs>
			<part name="steel ingot" number="5" />
		</outputs>
	</process>

	<!-- Produces 1m x `m x 1mm (7.8kg) sheet of steel. -->
	<process name="Make steel sheet" tech="0" skill="0" work-time="50" process-time="10" tooling="metalwork"
			power-required=".3">
		<inputs>
			<resource name="iron powder" amount="7.7" />
			<resource name="manganese" amount=".1" />			
			<resource name="Carbon" amount=".1" />
		</inputs>
		<outputs>
			<part name="steel sheet" number="1" />
		</outputs>
	</process>

	<!-- Produces 1m x 1m x 1mm (7.8kg) sheet of steel. -->
	<process name="Roll steel sheet" tech="0" skill="0" work-time="50" process-time="10" tooling="metalwork"
			power-required=".3">
		<inputs>
			<resource name="manganese" amount=".1" />		
			<part name="steel ingot" number="8" />
		</inputs>
		<outputs>
			<resource name="iron powder" amount="1.0" />
			<part name="steel sheet" number="5" />
		</outputs>
	</process>

	<!-- Produces 0.05 kg spool of thick steel wire from 5 kg steel ingot. -->
	<process name="Draw steel wire" tech="0" skill="0" work-time="50" process-time="20" tooling="metalwork"
			power-required=".2">
		<inputs>
			<part name="steel ingot" number="1" />
		</inputs>
		<outputs>
			<part name="steel wire" number="100" />
		</outputs>
	</process>

	<!-- Produces 1kg of steel cable from 5kg steel ingot. -->
	<process name="Do steel cable winding" tech="0" skill="0" work-time="50" process-time="20" tooling="metalwork"
			power-required="0.1">
		<inputs>
			<part name="steel ingot" number="1" />
		</inputs>
		<outputs>
			<part name="steel cable" number="5" />
		</outputs>
	</process>

	<!-- Produces 8x 1m x 2mm x 20cm steel pipe. -->
	<process name="Make steel pipe" tech="0" skill="0" work-time="50" process-time="20" tooling="metalwork"
			power-required=".1">
		<inputs>
			<part name="steel sheet" number="1" />
		</inputs>
		<outputs>
			<resource name="iron powder" amount="0.8" />
			<part name="steel pipe" number="8" />
		</outputs>
	</process>

	<!-- Produces 8x 1m x 2mm x 20cm iron pipe. -->
	<process name="Make iron pipe" tech="0" skill="0" work-time="50" process-time="20" tooling="metalwork"
			power-required=".1">
		<inputs>
			<part name="iron sheet" number="1" />
		</inputs>
		<outputs>
			<resource name="iron powder" amount="0.8" />
			<part name="iron pipe" number="8" />
		</outputs>
	</process>

	<process name="Make fire extinguisher" tech="2" skill="1" work-time="50" process-time="10"
			power-required="0.1">
		<inputs>
			<resource name="carbon dioxide" amount="3.0" />
			<part name="steel canister" number="1" />
			<part name="valve" number="1" />
			<part name="gasket" number="1" />
			<part name="plastic tubing" number="1" />
		</inputs>
		<outputs>
			<part name="fire extinguisher" number="1" />
		</outputs>
	</process>

	<process name="Make steel valve" tech="2" skill="1" work-time="200" process-time="200"
			power-required="0.1">
		<inputs>
			<part name="steel ingot" number="1" />
		</inputs>
		<outputs>
			<part name="valve" number="25" />
		</outputs>
	</process>

	<!-- Using reinforced fiberglass wrapped in aluminum sheeting to make satellite dish. -->
	<process name="Make satellite dish" tech="2" skill="3" work-time="200" process-time="200"
			tooling="Soldering" power-required="0.4">
		<inputs>
			<resource name="Polyester resin" amount=".5">
				<alternative name="Polycarbonate resin" amount=".5" />
			</resource>
			<resource name="styrene" amount=".5" />
			<part name="fiberglass" number="1" />		
			<part name="aluminum sheet" number="1" />
			<part name="electrical wire" number="3" />
			<part name="wire connector" number="4" />
			<part name="optical cable" number="2" />
		</inputs>
		<outputs>
			<part name="satellite dish" number="1" />
		</outputs>
	</process>

	<process name="Make plastic barrel" tech="1" skill="1" work-time="10" process-time="10"
			tooling="3d printer" power-required="0.1">
		<inputs>
			<resource name="Polyethylene" amount="7.8">
				<alternative name="Polypropylene" amount="7.8" />
			</resource>
		</inputs>
		<outputs>
			<equipment name="barrel" number="6" />
		</outputs>
	</process>
	
	<process name="Make Polypropylene rope" tech="1" skill="1" work-time="10" process-time="10" tooling="3D Printer"
			power-required="0.1">
		<inputs>
			<resource name="Polypropylene" amount="2" />
		</inputs>
		<outputs>
			<part name="rope" number="1" />
		</outputs>
	</process>

	<process name="Make pot" tech="1" skill="1" work-time="10" process-time="10" tooling="3d printer"
			power-required=".1">
		<inputs>
			<resource name="Polyethylene" amount="7.8">
				<alternative name="Polypropylene" amount="7.8" />
			</resource>
		</inputs>
		<outputs>
			<bin name="pot" number="8" />
		</outputs>
	</process>
	
	<process name="Make basket" tech="1" skill="1" work-time="10" process-time="10" tooling="3d printer"
			power-required=".1">
		<inputs>
			<resource name="Polyethylene" amount="7.8"> 
				<alternative name="Polypropylene" amount="7.8" />
			</resource>
		</inputs>
		<outputs>
			<bin name="basket" number="12" />
		</outputs>
	</process>
	
	<process name="Make crate" tech="1" skill="1" work-time="10" process-time="10" tooling="3d printer"
			power-required=".1">
		<inputs>
			<resource name="Polyethylene" amount="7.8">
				<alternative name="Polypropylene" amount="7.8" />
			</resource>
		</inputs>
		<outputs>
			<bin name="crate" number="6" />
		</outputs>
	</process>
	
	<process name="Make plastic specimen box" tech="1" skill="1" work-time="10" process-time="10" tooling="3d printer"
			power-required=".1">
		<inputs>
			<resource name="Polyethylene" amount="7.8">
				<alternative name="Polypropylene" amount="7.8" />
			</resource>
		</inputs>
		<outputs>
			<equipment name="specimen box" number="12" />
		</outputs>
	</process>
	
	<!-- Produces 10kg steel canister. -->
	<process name="Make steel canister" tech="1" skill="1" work-time="10" process-time="10" tooling="metalwork"
			 power-required=".1">
		<inputs>
			<!-- one steel sheet weighs 7.8 kg -->
			<part name="steel sheet" number="1" />
		</inputs>
		<outputs>
			<resource name="iron powder" amount="0.4" />
			<!-- one steel canister weighs 3.9 kg -->
			<part name="steel canister" number="2" />
		</outputs>
	</process>

	<process name="Make gas canister" tech="1" skill="1" work-time="5" process-time="5" tooling="metalwork"
			power-required="0.1">
		<inputs>
			<part name="steel canister" number="1" />
			<part name="valve" number="2" />
			<part name="gasket" number="1" />
		</inputs>
		<outputs>
			<!-- one gas canister weighs 4 kg -->
			<equipment name="gas canister" number="1" />
		</outputs>
	</process>

	<!-- Using reinforced fiberglass wrapped in aluminum sheeting to make antenna. -->
	<process name="Make radio antenna" tech="2" skill="2" work-time="100" process-time="100"
			tooling="3d printer" power-required=".3">
		<inputs>
			<resource name="Polyester resin" amount=".5">
				<alternative name="Polycarbonate resin" amount=".5" />
			</resource>
			<resource name="styrene" amount=".5" />
			<part name="fiberglass" number="1" />
			<part name="aluminum sheet" number="1" />
			<part name="electrical wire" number="1" />
			<part name="wire connector" number="3" />
			<part name="optical cable" number="1" />
		</inputs>
		<outputs>
			<part name="radio antenna" number="5" />
		</outputs>
	</process>

	<process name="Make suit heating unit" tech="2" skill="2" work-time="100" process-time="100"
			tooling="Soldering" power-required="0.3">
		<inputs>
			<part name="aluminum sheet" number="1" />
			<part name="heating element" number="1" />
			<part name="heat pipe" number="1" />
			<part name="electrical wire" number="1" />
			<part name="wire connector" number="4" />
		</inputs>
		<outputs>
			<part name="suit heating unit" number="5" />
		</outputs>
	</process>

	<!-- Produces 1kg plastic pipe. -->
	<process name="Make plastic pipe" tech="1" skill="1" work-time="100" process-time="400" tooling="3d printer"
			power-required=".1">
		<inputs>
			<resource name="Polyethylene" amount="10.0">
				<alternative name="Polypropylene" amount="10.0" />
			</resource>
		</inputs>
		<outputs>
			<part name="plastic pipe" number="10" />
		</outputs>
	</process>

	<process name="Produce petri dish" tech="2" skill="2" work-time="50" process-time="40" tooling="3d printer"
			power-required=".1">
		<inputs>
			<resource name="polystyrene" amount="1" />
		</inputs>
		<outputs>
			<part name="petri dish" number="50" />
		</outputs>
	</process>
	
	<process name="Make gasket" tech="4" skill="2" work-time="100" process-time="200" 
			tooling="3d printer" power-required=".1">
		<inputs>
			<resource name="styrene" amount="2.0" />
		</inputs>
		<outputs>
			<part name="gasket" number="20" />
		</outputs>
	</process>

	<!-- Use fiberglass & styrene to make belt. -->
	<process name="Make timing belt" tech="4" skill="2" work-time="100" process-time="75"
			power-required=".2">
		<inputs>
			<resource name="styrene" amount="1.0" />
			<part name="fiberglass cloth" number="1" />
		</inputs>
		<outputs>
			<part name="timing belt" number="5" />
		</outputs>
	</process>

	<process name="Make plastic tubing" tech="4" skill="2" work-time="100" process-time="75"
			tooling="chemical" power-required=".05">
		<inputs>
			<resource name="styrene" amount="1.0" />
		</inputs>
		<outputs>
			<part name="plastic tubing" number="10" />
		</outputs>
	</process>
	
	<process name="Produce polyester fiber" tech="2" skill="1" work-time="10" process-time="40"
			tooling="chemical" power-required="0.05">
		<description>
			This is to produce polyester fiber.
			https://www.britannica.com/science/Polyethylene-terephthalate
			
			Ethylene glycol + C10H10O4 -> Polyester fiber (PET) + 2H2O
			     62 g          194 g              220 g          36 g
		</description>
		<inputs>
			<resource name="Ethylene glycol" amount="6.2" />
			<resource name="Dimethyl terephthalate" amount="19.4" />
		</inputs>
		<outputs>
			<resource name="Polyester fiber" amount="22.0" />
			<resource name="Water" amount="3.6" />
		</outputs>
	</process>
