<?xml version = "1.0" encoding = "UTF-8" standalone = "yes" ?>
<!DOCTYPE robot-configuration [
	<!ELEMENT robot-configuration (global-config, robot-list)>
	<!ELEMENT global-config EMPTY>
	<!ATTLIST global-config min-air-pressure CDATA #REQUIRED>
	<!ATTLIST global-config min-temperature CDATA #REQUIRED>
	<!ATTLIST global-config max-temperature CDATA #REQUIRED>
	<!ATTLIST global-config freezing-time CDATA #REQUIRED>
	<!ELEMENT robot-list (robot*)>
	<!ELEMENT robot (description, robotic-attribute-list?, skill-list?)>
	<!ATTLIST robot type CDATA #REQUIRED>
	<!ATTLIST robot make CDATA #REQUIRED>
	<!ATTLIST robot standby-power-consumption  CDATA #IMPLIED>
	<!ATTLIST robot consumption-rate CDATA #IMPLIED>
	<!ATTLIST robot low-power-mode CDATA #IMPLIED>
	<!ATTLIST robot max-capacity CDATA #IMPLIED>
	<!ATTLIST robot mass CDATA #IMPLIED>
	<!ATTLIST robot height CDATA #IMPLIED>
	
	<!ELEMENT description (#PCDATA)>
	<!ELEMENT robotic-attribute-list (robotic-attribute*)>
	<!ELEMENT robotic-attribute EMPTY>
	<!ATTLIST robotic-attribute name CDATA #REQUIRED>
	<!ATTLIST robotic-attribute value CDATA #REQUIRED>
	<!ELEMENT skill-list (skill*)>
	<!ELEMENT skill EMPTY>
	<!ATTLIST skill name CDATA #REQUIRED>
	<!ATTLIST skill level CDATA #REQUIRED>
]>

<robot-configuration>
	
	<global-config
		min-air-pressure="500"
		min-temperature="-30.0"
		max-temperature="78.0"
		freezing-time="500.0"/>

	<!-- List of robot type -->
	<robot-list>

		<robot type="GardenBot" make="Standard" mass="60" height="100"
				standby-power-consumption="0.1" consumption-rate="0.4" low-power-mode="20">
			<description>A gardening robot that tends greenhouses, algae ponds, and fish farms.</description>
			<robotic-attribute-list>
				<robotic-attribute name="Strength" value="35"/>
				<robotic-attribute name="Endurance" value="95"/>
				<robotic-attribute name="Agility" value="40"/>
				<robotic-attribute name="Teaching" value="10"/>
				<robotic-attribute name="Experience Aptitude" value="95"/>
				<robotic-attribute name="Conversation" value="10"/>
			</robotic-attribute-list>
			<skill-list>
				<skill name="Botany" level="1"/>
				<skill name="Astrobiology" level="1"/>
			</skill-list>
		</robot>

		<robot type="GardenBot" make="Advanced" mass="60" height="100"
				standby-power-consumption="0.1" consumption-rate="0.35" low-power-mode="15"
				max-capacity="15">
			<description>A more advanced gardening robot with higher battery capacity.</description>
			<robotic-attribute-list>
				<robotic-attribute name="Strength" value="55"/>
				<robotic-attribute name="Endurance" value="95"/>
				<robotic-attribute name="Agility" value="60"/>
				<robotic-attribute name="Teaching" value="30"/>
				<robotic-attribute name="Experience Aptitude" value="95"/>
				<robotic-attribute name="Conversation" value="80"/>
			</robotic-attribute-list>
			<skill-list>
				<skill name="Botany" level="2"/>
				<skill name="Astrobiology" level="2"/>
			</skill-list>
		</robot>
		
		<robot type="MakerBot" make="Standard"
					standby-power-consumption="0.1" consumption-rate="0.45" low-power-mode="20">
			<description>A manufacturing robot that aids resource production.</description>
			<robotic-attribute-list>
				<robotic-attribute name="Strength" value="95"/>
				<robotic-attribute name="Endurance" value="95"/>
				<robotic-attribute name="Agility" value="40"/>
				<robotic-attribute name="Teaching" value="30"/>
				<robotic-attribute name="Experience Aptitude" value="95"/>
				<robotic-attribute name="Conversation" value="10"/>
			</robotic-attribute-list>
			<skill-list>
				<skill name="Materials Science" level="1"/>
				<skill name="Physics" level="1"/>				
			</skill-list>
		</robot>				
		
		<robot type="MakerBot" make="Advanced"
					standby-power-consumption="0.1" consumption-rate="0.4" low-power-mode="15">
			<description>A manufacturing robot that aids resource production.</description>
			<robotic-attribute-list>
				<robotic-attribute name="Strength" value="95"/>
				<robotic-attribute name="Endurance" value="95"/>
				<robotic-attribute name="Agility" value="60"/>
				<robotic-attribute name="Teaching" value="30"/>
				<robotic-attribute name="Experience Aptitude" value="95"/>
				<robotic-attribute name="Conversation" value="80"/>
			</robotic-attribute-list>
			<skill-list>
				<skill name="Materials Science" level="2"/>
				<skill name="Physics" level="2"/>				
			</skill-list>
		</robot>
		
		<robot type="RepairBot" make="Standard"
					standby-power-consumption="0.1" consumption-rate="0.45" low-power-mode="20">
			<description>A robot that fixes and repaire parts and equipment.</description>
			<robotic-attribute-list>
				<robotic-attribute name="Strength" value="95"/>
				<robotic-attribute name="Endurance" value="95"/>
				<robotic-attribute name="Agility" value="40"/>
				<robotic-attribute name="Teaching" value="30"/>
				<robotic-attribute name="Experience Aptitude" value="95"/>
				<robotic-attribute name="Conversation" value="10"/>
			</robotic-attribute-list>
			<skill-list>
				<skill name="Mechanics" level="1"/>
				<skill name="Materials Science" level="1"/>
			</skill-list>
		</robot>			
		
		<robot type="RepairBot" make="Advanced"
					standby-power-consumption="0.1" consumption-rate="0.4" low-power-mode="15">
			<description>A robot that fixes and repaire parts and equipment.</description>
			<robotic-attribute-list>
				<robotic-attribute name="Strength" value="95"/>
				<robotic-attribute name="Endurance" value="95"/>
				<robotic-attribute name="Agility" value="60"/>
				<robotic-attribute name="Teaching" value="50"/>
				<robotic-attribute name="Experience Aptitude" value="95"/>
				<robotic-attribute name="Conversation" value="80"/>
			</robotic-attribute-list>
			<skill-list>
				<skill name="Mechanics" level="2"/>
				<skill name="Materials Science" level="2"/>
			</skill-list>
		</robot>			
		
		<robot type="ChefBot" make="Standard"
					standby-power-consumption="0.1" consumption-rate="0.4" low-power-mode="20">
			<description>A kitchen robot that prepares food, meals and dessert.</description>
			<robotic-attribute-list>
				<robotic-attribute name="Strength" value="95"/>
				<robotic-attribute name="Endurance" value="95"/>
				<robotic-attribute name="Agility" value="40"/>
				<robotic-attribute name="Teaching" value="10"/>
				<robotic-attribute name="Experience Aptitude" value="95"/>
				<robotic-attribute name="Conversation" value="10"/>
			</robotic-attribute-list>
			<skill-list>
				<skill name="Chemistry" level="1"/>
				<skill name="Cooking" level="1"/>
			</skill-list>
		</robot>

		<robot type="ChefBot" make="Advanced"
					standby-power-consumption="0.1" consumption-rate="0.35" low-power-mode="15">
			<description>A kitchen robot that prepares food, meals and dessert.</description>
			<robotic-attribute-list>
				<robotic-attribute name="Strength" value="95"/>
				<robotic-attribute name="Endurance" value="95"/>
				<robotic-attribute name="Agility" value="60"/>
				<robotic-attribute name="Teaching" value="30"/>
				<robotic-attribute name="Experience Aptitude" value="95"/>
				<robotic-attribute name="Conversation" value="80"/>
			</robotic-attribute-list>
			<skill-list>
				<skill name="Chemistry" level="2"/>
				<skill name="Cooking" level="2"/>
			</skill-list>
		</robot>
	
		<robot type="MedicBot" make="Standard" mass="90"
					standby-power-consumption="0.1" consumption-rate="0.3" low-power-mode="20">
			<description>A robot that provides medical treatment and aid.</description>
			<robotic-attribute-list>
				<robotic-attribute name="Strength" value="95"/>
				<robotic-attribute name="Endurance" value="95"/>
				<robotic-attribute name="Agility" value="40"/>
				<robotic-attribute name="Teaching" value="10"/>
				<robotic-attribute name="Experience Aptitude" value="95"/>
				<robotic-attribute name="Conversation" value="10"/>
			</robotic-attribute-list>
			<skill-list>
				<skill name="PSYCHOLOGY" level="1"/>
				<skill name="Medicine" level="1"/>
				<skill name="CHEMISTRY" level="1"/>
			</skill-list>
		</robot>				
		
		<robot type="MedicBot" make="Advanced" mass="90"
					standby-power-consumption="0.1" consumption-rate="0.25" low-power-mode="15">
			<description>A robot that provides medical treatment and aid.</description>
			<robotic-attribute-list>
				<robotic-attribute name="Strength" value="95"/>
				<robotic-attribute name="Endurance" value="95"/>
				<robotic-attribute name="Agility" value="60"/>
				<robotic-attribute name="Teaching" value="30"/>
				<robotic-attribute name="Experience Aptitude" value="95"/>
				<robotic-attribute name="Conversation" value="80"/>
			</robotic-attribute-list>
			<skill-list>
				<skill name="PSYCHOLOGY" level="2"/>
				<skill name="Medicine" level="2"/>
				<skill name="CHEMISTRY" level="2"/>
			</skill-list>
		</robot>				
		
		
		<robot type="ConstructionBot" make="Standard" mass="120" height="160"
				standby-power-consumption="0.15" consumption-rate="0.55" low-power-mode="20">
			<description>A robot that provides construction missions.</description>
			<robotic-attribute-list>
				<robotic-attribute name="Strength" value="95"/>
				<robotic-attribute name="Endurance" value="95"/>
				<robotic-attribute name="Agility" value="40"/>
				<robotic-attribute name="Teaching" value="10"/>
				<robotic-attribute name="Experience Aptitude" value="95"/>
				<robotic-attribute name="Conversation" value="10"/>
			</robotic-attribute-list>
			<skill-list>
				<skill name="Construction" level="1"/>
				<skill name="AREOLOGY" level="1"/>
				<skill name="Mechanics" level="1"/>		
			</skill-list>
		</robot>
		
		<robot type="DeliveryBot" make="Standard" mass="50" height="80" max-capacity="15"
					standby-power-consumption="0.1" consumption-rate=".3" low-power-mode="20">
			<description>A robot that functions as a pilot and loads and unloads cargoes.</description>
			<robotic-attribute-list>
				<robotic-attribute name="Strength" value="95"/>
				<robotic-attribute name="Endurance" value="95"/>
				<robotic-attribute name="Agility" value="40"/>
				<robotic-attribute name="Teaching" value="10"/>
				<robotic-attribute name="Experience Aptitude" value="95"/>
				<robotic-attribute name="Conversation" value="10"/>
			</robotic-attribute-list>
			<skill-list>
				<skill name="Trading" level="1"/>
				<skill name="Piloting" level="1"/>
				<skill name="Mechanics" level="1"/>		
			</skill-list>
		</robot>

		<robot type="DeliveryBot" make="Advanced" mass="50" height="80" max-capacity="15"
					standby-power-consumption="0.1" consumption-rate="0.25" low-power-mode="15">
			<description>A robot that functions as a pilot and loads and unloads cargoes.</description>
			<robotic-attribute-list>
				<robotic-attribute name="Strength" value="95"/>
				<robotic-attribute name="Endurance" value="95"/>
				<robotic-attribute name="Agility" value="60"/>
				<robotic-attribute name="Teaching" value="30"/>
				<robotic-attribute name="Experience Aptitude" value="95"/>
				<robotic-attribute name="Conversation" value="80"/>
			</robotic-attribute-list>
			<skill-list>
				<skill name="Trading" level="2"/>
				<skill name="Piloting" level="2"/>
				<skill name="Mechanics" level="2"/>		
			</skill-list>
		</robot>
		
	</robot-list>

</robot-configuration>
