=== mars-sim/mars-sim/mars-sim-core/src/main/resources/xml/settlement/settlement.xsd
<?xml version="1.0" encoding="UTF-8" ?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">

    <xs:element name="connection-list">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="connection" maxOccurs="unbounded">
                    <xs:complexType>
                        <xs:attribute name="xloc" type="xs:decimal"/>
                        <xs:attribute name="yloc" type="xs:decimal"/>
                        <xs:attribute name="hatch-facing" type="xs:string"/>
                        <xs:attribute name="id" type="xs:string"/>                   
                    </xs:complexType>
                </xs:element>
            </xs:sequence>
        </xs:complexType>
    </xs:element>

    <xs:element name="building">
        <xs:complexType>
            <xs:sequence>
                <xs:element ref="connection-list" minOccurs="0"/>
            </xs:sequence>
            <xs:attribute name="type" type="xs:string"/>
            <xs:attribute name="width" type="xs:decimal"/>
            <xs:attribute name="length" type="xs:decimal"/>
            <xs:attribute name="xloc" type="xs:decimal"/>
            <xs:attribute name="yloc" type="xs:decimal"/>
            <xs:attribute name="facing" type="xs:decimal"/>
            <xs:attribute name="id" type="xs:string"/>
            <xs:attribute name="zone" type="xs:integer"/>            
        </xs:complexType>
    </xs:element>
    
   <xs:element name="connector">
        <xs:complexType>
            <xs:sequence>
                <xs:element ref="connection-list" minOccurs="0"/>
            </xs:sequence>
            <xs:attribute name="type" type="xs:string"/>
            <xs:attribute name="width" type="xs:decimal"/>
            <xs:attribute name="length" type="xs:decimal"/>
            <xs:attribute name="xloc" type="xs:decimal"/>
            <xs:attribute name="yloc" type="xs:decimal"/>
            <xs:attribute name="facing" type="xs:decimal"/>
            <xs:attribute name="id" type="xs:string"/>
            <xs:attribute name="zone" type="xs:integer"/>            
        </xs:complexType>
    </xs:element>
    
    <xs:element name="standalone">
        <xs:complexType>
            <xs:attribute name="type" type="xs:string"/>
            <xs:attribute name="xloc" type="xs:decimal"/>
            <xs:attribute name="yloc" type="xs:decimal"/>
            <xs:attribute name="facing" type="xs:decimal"/>
        </xs:complexType>
    </xs:element>
 
    <xs:element name="building-package">
        <xs:complexType>
            <xs:attribute name="name" type="xs:string"/>
        </xs:complexType>
    </xs:element>
       
    <xs:element name="vehicle">
        <xs:complexType>
            <xs:attribute name="type" type="xs:string"/>
            <xs:attribute name="number" type="xs:decimal"/>
        </xs:complexType>
    </xs:element>
    
    <xs:element name="robot-new">
        <xs:complexType>
            <xs:attribute name="type" type="xs:string"/>
            <xs:attribute name="number" type="xs:decimal"/>
        </xs:complexType>
    </xs:element>

    <!-- This is deprecated-->
    <xs:element name="robot">
        <xs:complexType>
            <xs:attribute name="type" type="xs:string"/>
            <xs:attribute name="name" type="xs:string"  use="optional"/>
            <xs:attribute name="model" type="xs:string"  use="optional"/>
        </xs:complexType>
    </xs:element>

    <xs:element name="building-plan">
        <xs:complexType>
            <xs:attribute name="building-type" type="xs:string" use="required"/>
            <xs:attribute name="delay-sols" type="xs:nonNegativeInteger" use="required"/>
        </xs:complexType>
    </xs:element>

    <xs:element name="equipment">
        <xs:complexType>
            <xs:attribute name="type" type="xs:string"/>
            <xs:attribute name="number" type="xs:decimal"/>
        </xs:complexType>
    </xs:element>
    
    <xs:element name="bin">
        <xs:complexType>
            <xs:attribute name="type" type="xs:string"/>
            <xs:attribute name="number" type="xs:decimal"/>
        </xs:complexType>
    </xs:element>
    
    <xs:element name="resource">
        <xs:complexType>
            <xs:attribute name="type" type="xs:string"/>
            <xs:attribute name="amount" type="xs:decimal"/>
        </xs:complexType>
    </xs:element>

    <xs:element name="part">
        <xs:complexType>
            <xs:attribute name="type" type="xs:string"/>
            <xs:attribute name="number" type="xs:decimal"/>
        </xs:complexType>
    </xs:element>

    <xs:element name="part-package">
        <xs:complexType>
            <xs:attribute name="name" type="xs:string"/>
            <xs:attribute name="number" type="xs:decimal"/>
        </xs:complexType>
    </xs:element>

    <!-- This should be a common xsd -->
    <xs:element name="schedule">
        <xs:complexType>
            <xs:attribute name="firstSol" type="xs:string" use="optional"/>
            <xs:attribute name="eventTime" type="xs:string"/>
            <xs:attribute name="frequency" type="xs:decimal" use="optional"/>
        </xs:complexType>
    </xs:element>

    <xs:element name="resupply-mission">
        <xs:complexType>
            <xs:sequence>
                <xs:element ref="schedule"/>
            </xs:sequence>
            <xs:attribute name="name" type="xs:string"/>
            <xs:attribute name="manifest-name" type="xs:string"/>
        </xs:complexType>
    </xs:element>

    <xs:element name="resupply">
        <xs:complexType>
            <xs:sequence>
                <xs:element ref="resupply-mission" maxOccurs="unbounded"/>
            </xs:sequence>
        </xs:complexType>
    </xs:element>

    <xs:element name="template">
        <xs:complexType>
            <xs:sequence>
                <xs:element ref="building"  maxOccurs="unbounded"/>
                <xs:element ref="connector" minOccurs="0" maxOccurs="unbounded"/>
                <xs:element ref="standalone" minOccurs="0" maxOccurs="unbounded"/>
                <xs:element ref="building-package" minOccurs="0" maxOccurs="unbounded"/> 
                <xs:element ref="vehicle"  minOccurs="0" maxOccurs="unbounded"/>
                <xs:element ref="robot-new"  minOccurs="0" maxOccurs="unbounded"/>
                <xs:element ref="robot"  minOccurs="0" maxOccurs="unbounded"/>
                <xs:element ref="building-plan"  minOccurs="0" maxOccurs="unbounded"/>
                <xs:element ref="equipment"  minOccurs="0" maxOccurs="unbounded"/>
				<xs:element ref="bin"  minOccurs="0" maxOccurs="unbounded"/>
                <xs:element ref="resource"  minOccurs="0" maxOccurs="unbounded"/>
                <xs:element ref="part"  minOccurs="0" maxOccurs="unbounded"/>
                <xs:element ref="part-package" minOccurs="0" maxOccurs="unbounded"/>              
                <xs:element ref="resupply" minOccurs="0" maxOccurs="1"/>
            </xs:sequence>
            <xs:attribute name="name" type="xs:string"/>
            <xs:attribute name="description" type="xs:string"/>
            <xs:attribute name="sponsor" type="xs:string"/>
            <xs:attribute name="shift-pattern" type="xs:string"  use="optional"/>
            <xs:attribute name="objective" type="xs:string"  use="optional"/>
            <xs:attribute name="default-population" type="xs:integer"/>
            <xs:attribute name="number-of-robots" type="xs:integer"  use="optional"/>
        </xs:complexType>
    </xs:element>
</xs:schema>

=== mars-sim/mars-sim/mars-sim-core/src/main/resources/xml/settlement/settlement_mining_outpost.xml
<?xml version = "1.0" encoding = "UTF-8" standalone = "yes" ?>
<template xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="settlement.xsd"
    name="Mining Outpost" default-population="4" description="Base for Mining Outpost for Mars Society"
    sponsor="MS" objective="MANUFACTURING_DEPOT">
    <building id="00" type="Outpost Hub" xloc="0.0" yloc="0.0"
        facing="0.0">
        <connection-list>
            <connection id="1" xloc="-5.0" yloc="2.5" />
            <connection id="3" xloc="-5.0" yloc="-2.5" />
            <connection id="5" xloc="5.0" yloc="2.5" />
            <connection id="9" xloc="5.0" yloc="-2.5" />
            <connection id="02" xloc="0.0" yloc="-5.0" />
        </connection-list>
    </building>
    <building id="1" type="Tunnel" length="3.0" xloc="-6.5"
        yloc="2.5" facing="270.0">
        <connection-list>
            <connection id="00" xloc="0.0" yloc="1.5" />
            <connection id="2" xloc="0.0" yloc="-1.5" />
        </connection-list>
    </building>
    <building id="2" type="Bunkhouse" xloc="-10.5" yloc="2.5"
        facing="270.0">
        <connection-list>
            <connection id="1" xloc="0.0" yloc="2.5" />
        </connection-list>
    </building>
    <building id="3" type="Tunnel" length="3.0" xloc="-6.5"
        yloc="-2.5" facing="270.0">
        <connection-list>
            <connection id="00" xloc="0.0" yloc="1.5" />
            <connection id="4" xloc="0.0" yloc="-1.5" />
        </connection-list>
    </building>
    <building id="4" type="Bunkhouse" xloc="-10.5" yloc="-2.5"
        facing="270.0">
        <connection-list>
            <connection id="3" xloc="0.0" yloc="2.5" />
        </connection-list>
    </building>
    <building id="5" type="Tunnel" length="2.0" xloc="6.0"
        yloc="2.5" facing="90.0">
        <connection-list>
            <connection id="00" xloc="0.0" yloc="1.0" />
            <connection id="6" xloc="0.0" yloc="-1.0" />
        </connection-list>
    </building>
    <building id="6" type="Mining Lab" xloc="9.5" yloc="2.5"
        facing="90.0">
        <connection-list>
            <connection id="5" xloc="0.0" yloc="2.5" />
            <connection id="7" xloc="0.0" yloc="-2.5" />
            <connection id="10" xloc="-2.5" yloc="0.0" />
        </connection-list>
    </building>
    <building id="7" type="Tunnel" length="2.0" xloc="13.0"
        yloc="2.5" facing="90.0">
        <connection-list>
            <connection id="6" xloc="0.0" yloc="1.0" />
            <connection id="8" xloc="0.0" yloc="-1.0" />
        </connection-list>
    </building>
    <building id="8" type="Manufacturing Shed" xloc="16.5"
        yloc="2.5" facing="90.0">
        <connection-list>
            <connection id="7" xloc="0.0" yloc="2.5" />
            <connection id="12" xloc="-2.5" yloc="0.0" />
        </connection-list>
    </building>
    <building id="9" type="Tunnel" length="2.0" xloc="6.0"
        yloc="-2.5" facing="90.0">
        <connection-list>
            <connection id="00" xloc="0.0" yloc="1.0" />
            <connection id="10" xloc="0.0" yloc="-1.0" />
        </connection-list>
    </building>
    <building id="10" type="Storage Shed" xloc="9.5" yloc="-2.5"
        facing="90.0">
        <connection-list>
            <connection id="9" xloc="0.0" yloc="2.5" />
            <connection id="11" xloc="0.0" yloc="-2.5" />
            <connection id="6" xloc="2.5" yloc="0.0" />
            <connection id="17" hatch-facing="south" />
        </connection-list>
    </building>
    <building id="11" type="Tunnel" length="2.0" xloc="13.0"
        yloc="-2.5" facing="90.0">
        <connection-list>
            <connection id="10" xloc="0.0" yloc="1.0" />
            <connection id="12" xloc="0.0" yloc="-1.0" />
        </connection-list>
    </building>
    <building id="12" type="Storage Shed" xloc="16.5"
        yloc="-2.5" facing="90.0">
        <connection-list>
            <connection id="11" xloc="0.0" yloc="2.5" />
            <connection id="13" xloc="0.0" yloc="-2.5" />
            <connection id="8" xloc="2.5" yloc="0.0" />
        </connection-list>
    </building>
    <building id="13" type="Tunnel" length="2.0" xloc="20.0"
        yloc="-2.5" facing="90.0">
        <connection-list>
            <connection id="12" xloc="0.0" yloc="1.0" />
            <connection id="14" xloc="0.0" yloc="-1.0" />
        </connection-list>
    </building>
    <building id="14" type="Storage Shed" xloc="23.5"
        yloc="-2.5" facing="90.0">
        <connection-list>
            <connection id="13" xloc="0.0" yloc="2.5" />
        </connection-list>
    </building>
    <building id="02" type="Tunnel" length="4.0" xloc="0.0"
        yloc="-7.0" facing="0.0">
        <connection-list>
            <connection id="00" xloc="0.0" yloc="2.0" />
            <connection id="16" xloc="0.0" yloc="-2.0" />
        </connection-list>
    </building>
    <building id="16" type="Loading Dock Garage" xloc="0.0"
        yloc="-18.0" facing="180.0">
        <connection-list>
            <connection id="02" xloc="0.0" yloc="-9.0" />
        </connection-list>
    </building>
    
    <!-- EVA Airlock is attached to the Storage Shed 1 -->
    <building id="17" type="EVA Airlock" xloc="9.5" yloc="-8.0" facing="270.0">
        <connection-list>
            <connection id="10" hatch-facing="north" />
        </connection-list>
    </building>


    <!-- Building Packages -->
    <building-package name="Storage Set 1"/>   
   	<building-package name="ERV Set 1"/>
 	<building-package name="Air Set 1 - 1x2"/>
    <building-package name="Sabatier Set 1 - 1x2"/>
	<building-package name="Syngas Set 1 - 1x1"/>
 	<building-package name="Wind Set 1 - 1x9"/>   
	<building-package name="Solar Thermal Set 1 - 1x9"/>
	<building-package name="Methane Set 1 - 1x2"/> 

 	
    <initial-supplies>

 	
    <vehicle type="Explorer Rover" number="2" />
    <vehicle type="Light Utility Vehicle" number="2" />
    <vehicle type="Delivery Drone" number="2" />

    <robot type="MakerBot-Standard" number="1"/>
    <robot type="MedicBot-Standard" number="1"/>
    <robot type="RepairBot-Standard" number="1"/>
    <robot type="DeliveryBot-Standard" number="1"/>

    <equipment type="EVA Suit" number="8" />
    
    <!-- Containers-->
	<equipment type="barrel" number="40" />
	<equipment type="bag" number="40" />
	<equipment type="gas canister" number="40" />		
	<equipment type="large bag" number="40" />
	<equipment type="specimen box" number="40" />
    <equipment type="thermal bottle" number="8" />	
 	<equipment type="wheelbarrow" number="12" />
    
    <!-- Life Support Resources -->
	<resource type="food" amount="2880" />
	<resource type="water" amount="7200" />
	<resource type="oxygen" amount="7200" />
	<resource type="hydrogen" amount="7200" />
	<resource type="methane" amount="7200" />
	<resource type="methanol" amount="7200" />
	
    <part-package name="Standard Part Package 1" number="1" />

 	
    </initial-supplies>

  
    <resupply>
       	<resupply-mission name="Quarterly Delivery" manifest-name="Standard Resupply 1">
            <schedule eventTime="400" frequency="150" /> 
        </resupply-mission>
    </resupply> 
</template>

=== mars-sim/mars-sim/mars-sim-core/src/main/resources/xml/settlement/settlement_phase_2-sx.xml
<?xml version = "1.0" encoding = "UTF-8" standalone = "yes" ?>
<template xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="settlement.xsd"
    name="Phase 2-SX" default-population="8" description="Phase 2 circular base for SpaceX"
	sponsor="RKA">
    
    <building id="0" type="Lander Hab" xloc="0.0" yloc="0.0"
        facing="0.0">
        <connection-list>
            <connection id="1" xloc="4.5" yloc="0.0" />
            <connection id="3" xloc="0.0" yloc="4.5" />
            <connection id="2" xloc="-4.5" yloc="0.0" />
        </connection-list>
    </building>
    
    <!-- EVA Airlock is attached to the lander hab -->
    <building id="1" type="EVA Airlock" xloc="7.5" yloc="0.0"
        facing="0.0">
        <connection-list>
            <connection id="0" xloc="-3.0" yloc="0.0" />
        </connection-list>
    </building>

    <!-- This tunnel connects the lander hab horizontally to the east -->
    <building id="2" type="Tunnel" length="15" xloc="-12" 
    	yloc="0.0" facing="90.0">
        <connection-list>
            <connection id="0" xloc="0" yloc="-7.5" />
            <connection id="15" xloc="0" yloc="7.5" />
        </connection-list>
    </building>
    
    <!-- This hallway connects the lander hab on the first row 
    	and lab on the second row -->
    <building id="3" type="Hallway" length="4.0" xloc="0.0" 
    	yloc="6.5" facing="0.0">
        <connection-list>
            <connection id="0" xloc="0.0" yloc="-2.0" />
            <connection id="4" xloc="0.0" yloc="2.0" />
        </connection-list>
    </building>

    <building id="4" type="Laboratory" xloc="0.0" yloc="12.0"
        facing="90.0">
        <connection-list>
            <connection id="3" xloc="-3.5" yloc="0" />
            <connection id="5" xloc="3.5" yloc="0" />
        </connection-list>
    </building>

    <building id="5" type="Hallway" length="5.0" xloc="0" 
    	yloc="18" facing="0.0">
        <connection-list>
            <connection id="4" xloc="0.0" yloc="-2.5" />
            <connection id="6" xloc="0.0" yloc="2.5" />
        </connection-list>
    </building>

    <building id="6" type="Workshop" xloc="0.0" yloc="24.0"
        facing="90.0">
        <connection-list>
            <connection id="5" xloc="-3.5" yloc="0" />
            <connection id="7" xloc="0" yloc="4.5" />
        </connection-list>
    </building>

    <building id="7" type="Hallway" length="1.5" xloc="-5.25" 
    	yloc="24.0" facing="90.0">
        <connection-list>
            <connection id="6" xloc="0" yloc="-0.75"  />
            <connection id="8" xloc="0" yloc="0.75"  />
        </connection-list>
    </building>

   <building id="8" type="Garage" xloc="-12.0" yloc="24"
        facing="0.0">
        <connection-list>
            <connection id="7" xloc="6.0" yloc="0" />
            <connection id="9" xloc="-6.0" yloc="0" />
        </connection-list>
    </building>

    <building id="9" type="Hallway" length="1.5" xloc="-18.75" 
    	yloc="24.0" facing="90.0">
        <connection-list>
            <connection id="8" xloc="0" yloc="-0.75"  />
            <connection id="10" xloc="0" yloc="0.75"  />
        </connection-list>
    </building>
    
    <building id="10" type="Lander Hab" xloc="-24.0" yloc="24.0"
        facing="180.0">
        <connection-list>
            <connection id="9" xloc="-4.5" yloc="0.0" />
            <connection id="11" xloc="0.0" yloc="4.5" />
            <connection id="12" xloc="4.5" yloc="0.0" />
        </connection-list>
    </building>
    
    <building id="11" type="Hallway" length="4.5" xloc="-24.0" 
    	yloc="17.5" facing="0.0">
        <connection-list>
            <connection id="10" xloc="0.0" yloc="2.25" />
            <connection id="13" xloc="0.0" yloc="-2.25" />
        </connection-list>
    </building>
    
    <!-- EVA Airlock is attached to the lander hab -->
    <building id="12" type="EVA Airlock" xloc="-31.5" yloc="24.0"
        facing="180.0">
        <connection-list>
            <connection id="10" xloc="-3.0" yloc="0.0" />
        </connection-list>
    </building>
    
    <building id="13" type="Fish Farm" xloc="-24.0" yloc="12"
        facing="90.0">
        <connection-list>
            <connection id="11" xloc="3.0" yloc="0" />
            <connection id="14" xloc="-3.0" yloc="0" />
        </connection-list>
    </building>
    
    <building id="14" type="Hallway" length="6.0" xloc="-24.0" 
    	yloc="6" facing="0.0">
        <connection-list>
            <connection id="13" xloc="0.0" yloc="3.0" />
            <connection id="15" xloc="0.0" yloc="-3.0" />
        </connection-list>
    </building>
    
    <building id="15" type="Inflatable Greenhouse" xloc="-24.0" yloc="0.0"
        facing="90.0">
        <connection-list>    
            <connection id="2" xloc="0" yloc="-4.5" /> 
            <connection id="14" xloc="3" yloc="0" />  
        </connection-list>
    </building>        
        

    <!-- Building Packages -->
    <building-package name="Storage Set 1"/>
   	<building-package name="ERV Set 1"/>
   	<building-package name="Air Set 1 - 1x2"/>
    <building-package name="Sabatier Set 1 - 1x3"/> 
	<building-package name="Syngas Set 1 - 1x1"/>
	<building-package name="Solar Set 1 - 1x9"/>
	<building-package name="Solar Thermal Set 1 - 1x3"/>
	<building-package name="Kilo Set 1 - 1x1"/>
 	<building-package name="Brine Water Well Set 1 - 1x1"/>
 	 
    <supplies>
 	 
    <vehicle type="Explorer Rover" number="2" />
    <vehicle type="Long Range Explorer" number="1" />
    <vehicle type="Light Utility Vehicle" number="1" />
    <vehicle type="Delivery Drone" number="1" />

    <!-- Standard Phase 2 allocation-->
    <robot type="GardenBot-Advanced" number="2"/>
    <robot type="MakerBot-Standard" number="2"/>
    <robot type="MedicBot-Advanced" number="1"/>
    <robot type="RepairBot-Standard" number="2"/> 
      
    <equipment type="EVA Suit" number="16" />

    <!-- Containers-->
	<equipment type="barrel" number="40" />
	<equipment type="bag" number="40" />
	<equipment type="gas canister" number="40" />		
	<equipment type="large bag" number="40" />
	<equipment type="specimen box" number="40" />
    <equipment type="thermal bottle" number="12" />	
 	<equipment type="wheelbarrow" number="12" />
 	
	<!-- Life Support Resources -->
	<resource type="food" amount="1440" />
	<resource type="water" amount="4800" />
	<resource type="oxygen" amount="2880" />
 
    <part-package name="Standard Part Package 1" number="2" />
 	 
    </supplies>


    <resupply>
       	<resupply-mission name="BiMonthly Delivery" manifest-name="Standard Resupply 1">
            <schedule firstSol="4" frequency="60" />
        </resupply-mission>
        <resupply-mission name="Annual Delivery" manifest-name="Resupply for Phase 2">
                    <schedule firstSol="668" />
        </resupply-mission>
    </resupply>
</template>

=== mars-sim/mars-sim/mars-sim-core/src/main/resources/xml/settlement/settlement_phase_0-ms.xml
<?xml version = "1.0" encoding = "UTF-8" standalone = "yes" ?>
<template xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="settlement.xsd"
        name="Phase 0-MS" default-population="2" description="Phase 0 base for Mars Society"
		 sponsor="MS">

    <!-- Lander habitat building is the main habitation in the Mars Direct
        mission plan. -->
    <building id="0" type="Lander Hab" xloc="0.0" yloc="0.0"
        facing="0.0">
        <!-- List of all connections to other buildings (optional). -->
        <connection-list>
            <!-- Connection to another building. "id" is other building's ID. -->
            <!-- X & Y locations are relative to this building, not in the settlement
                locale. -->
            <connection id="1" xloc="4.5" yloc="0.0" />
            <connection id="2" xloc="-4.5" yloc="0.0" />
        </connection-list>
    </building>

    <!-- Suit Port is attached to the lander hab -->
    <building id="1" type="Suit Port" xloc="6.0" yloc="0.0" facing="-90.0">
        <connection-list>
            <connection id="0" hatch-facing="east"  />
        </connection-list>
    </building>

    <!-- Hallway connecting lander hab and inflatable greenhouse. -->
    <!-- Note: A hallway has fixed width but variable length. Therefore,
        the length argument must be provided below. -->
    <building id="2" type="Hallway" length="3.0" xloc="-6.0" yloc="0.0" facing="270.0">
        <connection-list>
            <connection id="0" xloc="0.0" yloc="1.5" />
            <connection id="3" xloc="0.0" yloc="-1.5" />
        </connection-list>
    </building>

    <!-- Inflatable greenhouse can be used to grow crops. -->
    <building id="3" type="Inflatable Greenhouse" xloc="-12.0" yloc="0.0" facing="270.0">
        <connection-list>
            <connection id="2" xloc="0.0" yloc="4.5" />
        </connection-list>
    </building>


    <!-- Building Packages -->
    <building-package name="Storage Set 1"/>
   	<building-package name="ERV Set 1"/>
    <building-package name="Sabatier Set 1 - 1x1"/>
   	<building-package name="Nuclear Set 1 - Combo 0"/>
    <building-package name="Solar Set 1 - 1x6"/>
   		
    <!-- A rover for collecting rock samples from remote sites and ice prospecting. -->
    <initial-supplies>
    <vehicle type="Explorer Rover" number="2" />
    <vehicle type="Light Utility Vehicle" number="1" />
    <vehicle type="Delivery Drone" number="1" />

    <!-- Standard Phase 0 allocation-->
    <robot type="MakerBot-Standard" number="1"/>
    <robot type="MedicBot-Standard" number="1"/>
    <robot type="RepairBot-Standard" number="1"/>
    <robot type="GardenBot-Standard" number="1"/>
    
    <!-- Equipment -->
    <equipment type="EVA Suit" number="8" />
    
    <!-- Containers-->
	<equipment type="barrel" number="40" />
	<equipment type="bag" number="40" />
	<equipment type="gas canister" number="40" />		
	<equipment type="large bag" number="40" />
	<equipment type="specimen box" number="40" />
    <equipment type="thermal bottle" number="8" />	
 	<equipment type="wheelbarrow" number="12" />

    <!-- Bins -->
	<bin type="pot" number="20" />
	<bin type="crate" number="20" />
	<bin type="basket" number="20" />

    <!-- Resources -->
    <!-- type: the type of resource (see resources.txt) -->
    <!-- amount: the amount of the resource (kg) -->

    <!-- Mars Direct Mission Plan : 
    (1). ERV - 
    	(a). Payload imported from Earth - 
    		 Consumables - Hydrogen : 3400 kg  
    		 Feedstock - Hydrogen : 6300 kg 
        (b). Produced on Mars : 
        	 Water : 18900 kg 
        	 Oxygen : 16080 kg 
        	 Methane : 8400 kg 
    (2). Hab -
        (a). Payload imported from Earth - 
             Consumables - Hydrogen : 7000 kg 
    -->

    <!-- Life Support Resources -->
	<resource type="food" amount="720" />
	<resource type="water" amount="3600" />
	<resource type="oxygen" amount="1440" />
	

    <!-- Crop -->
    <!-- No starting crops for this template -->

    <!-- Part packages (see part_packages.xml) -->
    <!-- name: the part package name. -->
    <!-- number: the number of packages. -->
    <part-package name="Standard Part Package 1" number="1" />

    <!-- The resupply missions from Earth scheduled for this type of settlement. -->
    </initial-supplies>

    <resupply>
        <resupply-mission name="Food Delivery" manifest-name="Food Resupply 1">
            <schedule firstSol="2" frequency="80" /> 
        </resupply-mission>
        <resupply-mission name="Phase 1 Delivery" manifest-name="Resupply for Phase 1">
            <schedule firstSol="668"/>
        </resupply-mission>
    </resupply>
</template>
