=== mars-sim/mars-sim/mars-sim-core/src/main/resources/xml/settlement/settlement.xsd
<?xml version="1.0" encoding="UTF-8" ?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">

    <xs:element name="connection-list">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="connection" maxOccurs="unbounded">
                    <xs:complexType>
                        <xs:attribute name="xloc" type="xs:decimal"/>
                        <xs:attribute name="yloc" type="xs:decimal"/>
                        <xs:attribute name="hatch-facing" type="xs:string"/>
                        <xs:attribute name="id" type="xs:string"/>                   
                    </xs:complexType>
                </xs:element>
            </xs:sequence>
        </xs:complexType>
    </xs:element>

    <xs:element name="building">
        <xs:complexType>
            <xs:sequence>
                <xs:element ref="connection-list" minOccurs="0"/>
            </xs:sequence>
            <xs:attribute name="type" type="xs:string"/>
            <xs:attribute name="width" type="xs:decimal"/>
            <xs:attribute name="length" type="xs:decimal"/>
            <xs:attribute name="xloc" type="xs:decimal"/>
            <xs:attribute name="yloc" type="xs:decimal"/>
            <xs:attribute name="facing" type="xs:decimal"/>
            <xs:attribute name="id" type="xs:string"/>
            <xs:attribute name="zone" type="xs:integer"/>            
        </xs:complexType>
    </xs:element>
    
   <xs:element name="connector">
        <xs:complexType>
            <xs:sequence>
                <xs:element ref="connection-list" minOccurs="0"/>
            </xs:sequence>
            <xs:attribute name="type" type="xs:string"/>
            <xs:attribute name="width" type="xs:decimal"/>
            <xs:attribute name="length" type="xs:decimal"/>
            <xs:attribute name="xloc" type="xs:decimal"/>
            <xs:attribute name="yloc" type="xs:decimal"/>
            <xs:attribute name="facing" type="xs:decimal"/>
            <xs:attribute name="id" type="xs:string"/>
            <xs:attribute name="zone" type="xs:integer"/>            
        </xs:complexType>
    </xs:element>
    
    <xs:element name="standalone">
        <xs:complexType>
            <xs:attribute name="type" type="xs:string"/>
            <xs:attribute name="xloc" type="xs:decimal"/>
            <xs:attribute name="yloc" type="xs:decimal"/>
            <xs:attribute name="facing" type="xs:decimal"/>
        </xs:complexType>
    </xs:element>
 
    <xs:element name="building-package">
        <xs:complexType>
            <xs:attribute name="name" type="xs:string"/>
        </xs:complexType>
    </xs:element>
       
    <xs:element name="vehicle">
        <xs:complexType>
            <xs:attribute name="type" type="xs:string"/>
            <xs:attribute name="number" type="xs:decimal"/>
        </xs:complexType>
    </xs:element>
    
    <xs:element name="robot-new">
        <xs:complexType>
            <xs:attribute name="type" type="xs:string"/>
            <xs:attribute name="number" type="xs:decimal"/>
        </xs:complexType>
    </xs:element>

    <!-- This is deprecated-->
    <xs:element name="robot">
        <xs:complexType>
            <xs:attribute name="type" type="xs:string"/>
            <xs:attribute name="name" type="xs:string"  use="optional"/>
            <xs:attribute name="model" type="xs:string"  use="optional"/>
        </xs:complexType>
    </xs:element>

    <xs:element name="building-plan">
        <xs:complexType>
            <xs:attribute name="building-type" type="xs:string" use="required"/>
            <xs:attribute name="delay-sols" type="xs:nonNegativeInteger" use="required"/>
        </xs:complexType>
    </xs:element>

    <xs:element name="equipment">
        <xs:complexType>
            <xs:attribute name="type" type="xs:string"/>
            <xs:attribute name="number" type="xs:decimal"/>
        </xs:complexType>
    </xs:element>
    
    <xs:element name="bin">
        <xs:complexType>
            <xs:attribute name="type" type="xs:string"/>
            <xs:attribute name="number" type="xs:decimal"/>
        </xs:complexType>
    </xs:element>
    
    <xs:element name="resource">
        <xs:complexType>
            <xs:attribute name="type" type="xs:string"/>
            <xs:attribute name="amount" type="xs:decimal"/>
        </xs:complexType>
    </xs:element>

    <xs:element name="part">
        <xs:complexType>
            <xs:attribute name="type" type="xs:string"/>
            <xs:attribute name="number" type="xs:decimal"/>
        </xs:complexType>
    </xs:element>

    <xs:element name="part-package">
        <xs:complexType>
            <xs:attribute name="name" type="xs:string"/>
            <xs:attribute name="number" type="xs:decimal"/>
        </xs:complexType>
    </xs:element>

    <!-- This should be a common xsd -->
    <xs:element name="schedule">
        <xs:complexType>
            <xs:attribute name="firstSol" type="xs:string" use="optional"/>
            <xs:attribute name="eventTime" type="xs:string"/>
            <xs:attribute name="frequency" type="xs:decimal" use="optional"/>
        </xs:complexType>
    </xs:element>

    <xs:element name="resupply-mission">
        <xs:complexType>
            <xs:sequence>
                <xs:element ref="schedule"/>
            </xs:sequence>
            <xs:attribute name="name" type="xs:string"/>
            <xs:attribute name="manifest-name" type="xs:string"/>
        </xs:complexType>
    </xs:element>

    <xs:element name="resupply">
        <xs:complexType>
            <xs:sequence>
                <xs:element ref="resupply-mission" maxOccurs="unbounded"/>
            </xs:sequence>
        </xs:complexType>
    </xs:element>

    <xs:element name="template">
        <xs:complexType>
            <xs:sequence>
                <xs:element ref="building"  maxOccurs="unbounded"/>
                <xs:element ref="connector" minOccurs="0" maxOccurs="unbounded"/>
                <xs:element ref="standalone" minOccurs="0" maxOccurs="unbounded"/>
                <xs:element ref="building-package" minOccurs="0" maxOccurs="unbounded"/> 
                <xs:element ref="vehicle"  minOccurs="0" maxOccurs="unbounded"/>
                <xs:element ref="robot-new"  minOccurs="0" maxOccurs="unbounded"/>
                <xs:element ref="robot"  minOccurs="0" maxOccurs="unbounded"/>
                <xs:element ref="building-plan"  minOccurs="0" maxOccurs="unbounded"/>
                <xs:element ref="equipment"  minOccurs="0" maxOccurs="unbounded"/>
				<xs:element ref="bin"  minOccurs="0" maxOccurs="unbounded"/>
                <xs:element ref="resource"  minOccurs="0" maxOccurs="unbounded"/>
                <xs:element ref="part"  minOccurs="0" maxOccurs="unbounded"/>
                <xs:element ref="part-package" minOccurs="0" maxOccurs="unbounded"/>              
                <xs:element ref="resupply" minOccurs="0" maxOccurs="1"/>
            </xs:sequence>
            <xs:attribute name="name" type="xs:string"/>
            <xs:attribute name="description" type="xs:string"/>
            <xs:attribute name="sponsor" type="xs:string"/>
            <xs:attribute name="shift-pattern" type="xs:string"  use="optional"/>
            <xs:attribute name="objective" type="xs:string"  use="optional"/>
            <xs:attribute name="default-population" type="xs:integer"/>
            <xs:attribute name="number-of-robots" type="xs:integer"  use="optional"/>
        </xs:complexType>
    </xs:element>
</xs:schema>

=== mars-sim/mars-sim/mars-sim-core/src/main/resources/xml/settlement/settlement_phase_1-MS.xml
<?xml version = "1.0" encoding = "UTF-8" standalone = "yes" ?>
<template xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="settlement.xsd"
        name="Phase 1-MS" default-population="4" description="Phase 1 base for Mars Society"
		number-of-robots="4" sponsor="MS">

    <!-- Lander habitat building is the main habitation in the Mars Direct
        mission plan. -->
    <building id="0" type="Lander Hab" xloc="0.0" yloc="0.0"
        facing="0.0">
        <!-- List of all connections to other buildings (optional). -->
        <connection-list>
            <!-- Connection to another building. "id" is other building's ID. -->
            <!-- X & Y locations are relative to this building, not in the settlement
                locale. -->
            <connection id="1" xloc="4.5" yloc="0.0" />
            <connection id="2" xloc="-4.5" yloc="0.0" />
        </connection-list>
    </building>

    <!-- EVA Airlock is attached to the lander hab -->
    <building id="1" type="EVA Airlock" xloc="7.5" yloc="0.0" facing="0.0">
        <connection-list>
            <connection id="0" xloc="-3.0" yloc="0.0" />
        </connection-list>
    </building>

    <!-- Hallway connecting lander hab and inflatable greenhouse. -->
    <!-- Note: Aa hallway has fixed width but variable length. Therefore,
        the length argument must be provided below. -->
    <building id="2" type="Hallway" length="3.0" xloc="-6.0" yloc="0.0" facing="270.0">
        <connection-list>
            <connection id="0" xloc="0.0" yloc="1.5" />
            <connection id="3" xloc="0.0" yloc="-1.5" />
        </connection-list>
    </building>

    <!-- Inflatable greenhouse can be used to grow crops. -->
    <building id="3" type="Inflatable Greenhouse" xloc="-12.0" yloc="0.0" facing="270.0">
        <connection-list>
            <connection id="2" xloc="0.0" yloc="4.5" />
        </connection-list>
    </building>

    <!-- Small nuclear reactor power generator. -->
    <building type="MD1 Nuclear Reactor" xloc="40.0"
        yloc="-60.0" facing="0.0" />
    <building type="MD1 Nuclear Reactor" xloc="40.0"
        yloc="-80.0" facing="0.0" />
    <building type="MD1 Nuclear Reactor" xloc="60.0"
        yloc="-60.0" facing="0.0" />

    <!-- Earth Return Vehicle Type A building has a Sabatier reactor for converting
        hydrogen and carbon dioxide into methane, water and oxygen. It has a full
        load of hydrogen and has not reacted yet. -->
    <building type="ERV-A" xloc="80.0" yloc="45.0" facing="0.0" />

    <!-- Earth Return Vehicle Type B building has numerous regolith processing
            capabilities for making cement and concrete for construction purposes. -->
    <building type="ERV-B" xloc="80.0" yloc="-15.0" facing="0.0" />

    <building type="Large Sabatier Processor" xloc="0.0"
        yloc="-70.0" facing="90.0" />
    <building type="Large Sabatier Processor" xloc="0.0"
        yloc="-80.0" facing="90.0" />

    <building type="Regolith Storage Bin" xloc="35.0" yloc="0.0"
        facing="90.0" />
    <building type="Sand Storage Bin" xloc="35.0" yloc="5.0"
        facing="90.0" />
    <building type="Concrete Storage Bin" xloc="35.0"
        yloc="10.0" facing="90.0" />
    <building type="Cement Storage Bin" xloc="35.0" yloc="15.0"
        facing="90.0" />
    <building type="Mortar Storage Bin" xloc="35.0" yloc="20.0"
        facing="90.0" />
    <building type="Lime Storage Bin" xloc="35.0" yloc="25.0"
        facing="90.0" />
    <building type="Ice Storage Bin" xloc="35.0" yloc="-5.0"
        facing="90.0" />
    <building type="Carbon Storage Bin" xloc="35.0" yloc="-10.0"
        facing="90.0" />

    <!-- A rover for collecting rock samples from remote sites and ice prospecting. -->
    <vehicle type="Explorer Rover" number="2" />
    <vehicle type="Light Utility Vehicle" number="1" />
    <vehicle type="Delivery Drone" number="1" />

    <!-- Equipment -->
    <equipment type="EVA Suit" number="8" />
    
    <!-- Containers-->
	<equipment type="barrel" number="40" />
	<equipment type="bag" number="40" />
	<equipment type="gas canister" number="40" />		
	<equipment type="large bag" number="40" />
	<equipment type="specimen box" number="40" />
    <equipment type="thermal bottle" number="8" />	
 	<equipment type="wheelbarrow" number="12" />

    <!-- Resources -->
    <!-- type: the type of resource (see resources.txt) -->
    <!-- amount: the amount of the resource (kg) -->

    <!-- Mars Direct Mission Plan : 
    (1). ERV - 
    	(a). Payload imported from Earth - 
    		 Consumables - Hydrogen : 3400 kg  
    		 Feedstock - Hydrogen : 6300 kg 
        (b). Produced on Mars : 
        	 Water : 18900 kg 
        	 Oxygen : 16080 kg 
        	 Methane : 8400 kg 
    (2). Hab -
        (a). Payload imported from Earth - 
             Consumables - Hydrogen : 7000 kg 
    -->

    <!-- Life Support Resources -->
	<resource type="food" amount="720" />
	<resource type="water" amount="3600" />
	<resource type="oxygen" amount="1440" />
	

    <!-- Crop -->
    <!-- No starting crops for this template -->

    <!-- Part packages (see part_packages.xml) -->
    <!-- name: the part package name. -->
    <!-- number: the number of packages. -->
    <part-package name="package 1" number="1" />

    <!-- The resupply missions from Earth scheduled for this type of settlement. -->
    <resupply>
        <!-- Resupply mission from Earth. -->
        <!-- name: the resupply mission's name -->
        <!-- arrival-time: arrival time (in Sols) since the settlement is founded. -->
        <!-- (668 Sols = 1 Martian orbit) -->
     	<resupply-mission name="Standard Resupply 1"
            arrival-time="0.1" />       
        <resupply-mission name="Resupply for Phase 1"
            arrival-time="668.0" />
        <resupply-mission name="Resupply for Phase 2"
            arrival-time="1336.0" />
        <resupply-mission name="Resupply for Phase 3"
            arrival-time="2004.0" />
    </resupply>
</template>

=== mars-sim/mars-sim/mars-sim-core/src/main/resources/xml/settlement/settlement_phase_1-de.xml
<?xml version = "1.0" encoding = "UTF-8" standalone = "yes" ?>
<template xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="settlement.xsd"
        name="Phase 1-DE" default-population="8" description="Phase 1 base for German Aerospace Center"
		sponsor="DLR">

    <building id="LH0" type="Lander Hab" xloc="0.0" yloc="0.0"
        facing="180.0">
        <connection-list>
            <connection id="C0" hatch-facing="east" />
        </connection-list>
    </building>

   <building id="C0" type="Brickcore3x9" xloc="-6.0" yloc="0.0"
        facing="0.0">
        <connection-list>
            <connection id="LH0" hatch-facing="west" />
            <connection id="EVA" hatch-facing="south" />
            <connection id="C1" hatch-facing="north" />
        </connection-list>
    </building>
    
    <building id="EVA" type="EVA Airlock" xloc="-6.0" yloc="-7.5"
        facing="270.0">
        <connection-list>
            <connection id="C0" hatch-facing="north" />
        </connection-list>
    </building>

    <building id="C1" type="Brickcore3x3" xloc="-6.0" yloc="6.0"
        facing="0.0">
        <connection-list>
            <connection id="C0" hatch-facing="south" />
            <connection id="C2" hatch-facing="east" />
        </connection-list>
    </building>
    
    <building id="C2" type="Brickcore3x9" xloc="-12.0" yloc="6.0"
        facing="90.0">
        <connection-list>
            <connection id="C1" hatch-facing="west" />
            <connection id="C3" hatch-facing="east" />
            <connection id="IG0" hatch-facing="south" />
        </connection-list>
    </building>
    
    <building id="IG0" type="Inflatable Greenhouse" xloc="-12.0" yloc="1.5"
        facing="270.0">
        <connection-list>
            <connection id="C2" hatch-facing="north" />
        </connection-list>
    </building>

    <building id="C3" type="Brickcore3x9" xloc="-21.0" yloc="6.0"
        facing="90.0">
        <connection-list>
            <connection id="C2" hatch-facing="west" />
            <connection id="W0" hatch-facing="south" />
        </connection-list>
    </building>
    
    <building id="W0" type="Workshop" xloc="-21.0" yloc="1.0" 
    	facing="90.0">
        <connection-list>
            <connection id="C3" hatch-facing="north" />
        </connection-list>
    </building>
    

    <!-- Building Packages -->
    <building-package name="Storage Set 1"/>
   	<building-package name="ERV Set 1"/>
   	<building-package name="Air Set 1 - 1x1"/>
   	<building-package name="Sabatier Set 1 - 1x1"/>
   	<building-package name="Nuclear Set 1 - Combo 1"/>
   	<building-package name="Solar Set 1 - 1x9"/>
 	<building-package name="Brine Water Well Set 1 - 1x1"/>
 	    	    
    <!-- A rover for collecting rock samples from remote sites and ice prospecting. -->
    <initial-supplies>
    <vehicle type="Explorer Rover" number="2" />
    <vehicle type="Light Utility Vehicle" number="1" />
    <vehicle type="Delivery Drone" number="1" />

    <!-- Advanced Phase 1 allocation-->
    <robot type="GardenBot-Advanced" number="1"/>
    <robot type="MakerBot-Standard" number="2"/>
    <robot type="MedicBot-Advanced" number="1"/>
    <robot type="RepairBot-Standard" number="2"/>

    <!-- Equipment -->
    <equipment type="EVA Suit" number="8" />
     
    <!-- Containers-->
	<equipment type="barrel" number="40" />
	<equipment type="bag" number="40" />
	<equipment type="gas canister" number="40" />		
	<equipment type="large bag" number="40" />
	<equipment type="specimen box" number="40" />
    <equipment type="thermal bottle" number="8" />	
 	<equipment type="wheelbarrow" number="12" />

    <!-- Bins -->
	<bin type="pot" number="20" />
	<bin type="crate" number="20" />
	<bin type="basket" number="20" />

    <!-- Resources -->
    <!-- type: the type of resource (see resources.txt) -->
    <!-- amount: the amount of the resource (kg) -->

    <!-- Mars Direct Mission Plan : 
    (1). ERV - 
    	(a). Payload imported from Earth - 
    		 Consumables - Hydrogen : 3400 kg  
    		 Feedstock - Hydrogen : 6300 kg 
        (b). Produced on Mars : 
        	 Water : 18900 kg 
        	 Oxygen : 16080 kg 
        	 Methane : 8400 kg 
    (2). Hab -
        (a). Payload imported from Earth - 
             Consumables - Hydrogen : 7000 kg 
    -->

    <!-- Life Support Resources -->
	<resource type="food" amount="720" />
	<resource type="water" amount="3600" />
	<resource type="oxygen" amount="1440" />
	

    <!-- Crop -->
    <!-- No starting crops for this template -->

    <!-- Part packages (see part_packages.xml) -->
    <!-- name: the part package name. -->
    <!-- number: the number of packages. -->
    <part-package name="Standard Part Package 1" number="1" />

    <!-- The resupply missions from Earth scheduled for this type of settlement. -->
    </initial-supplies>

    <resupply>
        <resupply-mission name="Food Delivery" manifest-name="Food Resupply 1">
            <schedule firstSol="2" frequency="80" />
        </resupply-mission>
        <resupply-mission name="Phase 1 Delivery" manifest-name="Resupply for Phase 1">
            <schedule firstSol="668" />
        </resupply-mission>
    </resupply>
</template>

=== mars-sim/mars-sim/mars-sim-core/src/main/resources/xml/settlement/settlement_phase_3-IN.xml
<?xml version = "1.0" encoding = "UTF-8" standalone = "yes" ?>
<template xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="settlement.xsd"
    name="Phase 3-IN" default-population="12" description="Phase 3 for ISRO"
    number-of-robots="7" sponsor="ISRO">
    
    <building id="0" type="Lander Hab" xloc="0.0" yloc="0.0"
        facing="0.0">
        <connection-list>
            <connection id="1" xloc="0.0" yloc="4.5" />
            <connection id="5" xloc="-4.5" yloc="0.0" />
            <connection id="21" xloc="4.5" yloc="0.0" />
        </connection-list>
    </building>
    <building id="1" type="Hallway" length="4.0" xloc="0.0"
        yloc="6.5" facing="0.0">
        <connection-list>
            <connection id="0" xloc="0.0" yloc="-2.0" />
            <connection id="2" xloc="0.0" yloc="2.0" />
        </connection-list>
    </building>
    <building id="2" type="Research Hab" xloc="0.0" yloc="13.0"
        facing="0.0">
        <connection-list>
            <connection id="1" xloc="0.0" yloc="-4.5" />
            <connection id="3" xloc="0.0" yloc="4.5" />
            <connection id="9" xloc="-4.5" yloc="0.0" />
        </connection-list>
    </building>
    <building id="3" type="Hallway" length="4.0" xloc="0.0"
        yloc="19.5" facing="0.0">
        <connection-list>
            <connection id="2" xloc="0.0" yloc="-2.0" />
            <connection id="4" xloc="0.0" yloc="2.0" />
        </connection-list>
    </building>
    <building id="4" type="Storage Hab" xloc="0.0" yloc="26.0"
        facing="0.0">
        <connection-list>
            <connection id="3" xloc="0.0" yloc="-4.5" />
            <connection id="13" xloc="-4.5" yloc="0.0" />
        </connection-list>
    </building>

    <!-- The first row -->
    <building id="5" type="Hallway" length="3.0" xloc="-6.0"
        yloc="0.0" facing="270.0">
        <connection-list>
            <connection id="0" xloc="0.0" yloc="1.5" />
            <connection id="6" xloc="0.0" yloc="-1.5" />
        </connection-list>
    </building>
    <building id="6" type="Laboratory" xloc="-12.0" yloc="0.0"
        facing="270.0">
        <connection-list>
            <connection id="5" xloc="0.0" yloc="4.5" />
            <connection id="7" xloc="0.0" yloc="-4.5" />
        </connection-list>
    </building>
    <building id="7" type="Hallway" length="3.0" xloc="-18.0"
        yloc="0.0" facing="270.0">
        <connection-list>
            <connection id="6" xloc="0.0" yloc="1.5" />
            <connection id="8" xloc="0.0" yloc="-1.5" />
        </connection-list>
    </building>
    <building id="8" type="Inflatable Greenhouse" xloc="-24.0"
        yloc="0.0" facing="270.0">
        <connection-list>
            <connection id="7" xloc="0.0" yloc="4.5" />
            <connection id="17" xloc="-3.0" yloc="0.0" />
            <connection id="19" xloc="3.0" yloc="0.0" />
        </connection-list>
    </building>

    <!-- The second row -->
    <building id="9" type="Hallway" length="3.0" xloc="-6.0"
        yloc="13.0" facing="270.0">
        <connection-list>
            <connection id="2" xloc="0.0" yloc="1.5" />
            <connection id="10" xloc="0.0" yloc="-1.5" />
        </connection-list>
    </building>
    <building id="10" type="Residential Quarters" xloc="-12.0"
        yloc="13.0" facing="270.0">
        <connection-list>
            <connection id="9" xloc="0.0" yloc="4.5" />
            <connection id="11" xloc="0.0" yloc="-4.5" />
        </connection-list>
    </building>

    <building id="11" type="Hallway" length="3.0" xloc="-18.0"
        yloc="13.0" facing="270.0">
        <connection-list>
            <connection id="10" xloc="0.0" yloc="1.5" />
            <connection id="12" xloc="0.0" yloc="-1.5" />
        </connection-list>
    </building>
    <building id="12" type="Inflatable Greenhouse" xloc="-24.0"
        yloc="13.0" facing="270.0">
        <connection-list>
            <connection id="11" xloc="0.0" yloc="4.5" />
            <connection id="17" xloc="3.0" yloc="0.0" />
            <connection id="18" xloc="-3.0" yloc="0.0" />
        </connection-list>
    </building>

    <!-- The third row -->
    <building id="13" type="Hallway" length="3.0" xloc="-6.0"
        yloc="26.0" facing="270.0">
        <connection-list>
            <connection id="4" xloc="0.0" yloc="1.5" />
            <connection id="14" xloc="0.0" yloc="-1.5" />
        </connection-list>
    </building>
    <building id="14" type="Lounge" xloc="-12.0" yloc="26.0"
        facing="270.0">
        <connection-list>
            <connection id="13" xloc="0.0" yloc="4.5" />
            <connection id="15" xloc="0.0" yloc="-4.5" />
        </connection-list>
    </building>

    <building id="15" type="Hallway" length="3.0" xloc="-18.0"
        yloc="26.0" facing="270.0">
        <connection-list>
            <connection id="14" xloc="0.0" yloc="1.5" />
            <connection id="16" xloc="0.0" yloc="-1.5" />
        </connection-list>
    </building>
    <building id="16" type="Inflatable Greenhouse" xloc="-24.0"
        yloc="26.0" facing="270.0">
        <connection-list>
            <connection id="15" xloc="0.0" yloc="4.5" />
            <connection id="18" xloc="3.0" yloc="0.0" />
        </connection-list>
    </building>

    <!-- This hallway connects the inflatable greenhouse on the first row
        to that of second row -->
    <building id="17" type="Hallway" length="7.0" xloc="-24.0"
        yloc="6.5" facing="0.0">
        <connection-list>
            <connection id="8" xloc="0.0" yloc="-3.5" />
            <connection id="12" xloc="0.0" yloc="3.5" />
        </connection-list>
    </building>

    <!-- This hallway connects the inflatable greenhouse on the second row
        to that of the third row -->
    <building id="18" type="Hallway" length="7.0" xloc="-24.0"
        yloc="19.5" facing="0.0">
        <connection-list>
            <connection id="12" xloc="0.0" yloc="-3.5" />
            <connection id="16" xloc="0.0" yloc="3.5" />
        </connection-list>
    </building>

    <!-- This hallway connects the inflatable greenhouse in the first row
        to the garage -->
    <building id="19" type="Hallway" length="4.0" xloc="-24.0"
        yloc="-5.0" facing="0.0">
        <connection-list>
            <connection id="8" xloc="0.0" yloc="2.0" />
            <connection id="20" xloc="0.0" yloc="-2.0" />
        </connection-list>
    </building>

    <building id="20" type="Garage" xloc="-24.0" yloc="-15"
        facing="180.0">
        <connection-list>
            <connection id="19" xloc="0.0" yloc="-8.0" />
        </connection-list>
    </building>

    <!-- EVA Airlock is attached to the lander hab -->
    <building id="21" type="EVA Airlock" xloc="7.5" yloc="0.0"
        facing="0.0">
        <connection-list>
            <connection id="0" xloc="-3.0" yloc="0.0" />
        </connection-list>
    </building>

    <building type="MD1 Nuclear Reactor" xloc="40.0"
        yloc="-60.0" facing="0.0" />
    <building type="MD1 Nuclear Reactor" xloc="40.0"
        yloc="-80.0" facing="0.0" />

    <building type="Solar Thermal Array" xloc="60.0"
        yloc="-60.0" facing="0.0" />
    <building type="Solar Thermal Array" xloc="60.0"
        yloc="-80.0" facing="0.0" />

    <building type="Large Areothermal Well" xloc="100.0"
        yloc="-100" facing="0.0" />

    <building type="ERV-A" xloc="80.0" yloc="45.0"
        facing="0.0" />
    <building type="ERV-A" xloc="120.0" yloc="45.0"
        facing="0.0" />
    <building type="ERV-A" xloc="160.0" yloc="45.0"
        facing="0.0" />
                        
    <building type="ERV-B" xloc="80.0" yloc="-15.0"
        facing="0.0" />
    <building type="ERV-B" xloc="120.0" yloc="-15.0"
        facing="0.0" />
    <building type="ERV-B" xloc="160.0" yloc="-15.0"
        facing="0.0" />

    <building type="Atmospheric Processor" xloc="20"
        yloc="-50.0" facing="90.0" />
        
    <building type="Large Sabatier Processor" xloc="0.0"
        yloc="-70.0" facing="90.0" />
    <building type="Large Sabatier Processor" xloc="0.0"
        yloc="-80.0" facing="90.0" />
    <building type="Large Sabatier Processor" xloc="0.0"
        yloc="-90.0" facing="90.0" />

    <building type="Regolith Storage Bin" xloc="35.0" yloc="0.0"
        facing="90.0" />
    <building type="Sand Storage Bin" xloc="35.0" yloc="5.0"
        facing="90.0" />
    <building type="Concrete Storage Bin" xloc="35.0"
        yloc="10.0" facing="90.0" />
    <building type="Cement Storage Bin" xloc="35.0" yloc="15.0"
        facing="90.0" />
    <building type="Mortar Storage Bin" xloc="35.0" yloc="20.0"
        facing="90.0" />
    <building type="Lime Storage Bin" xloc="35.0" yloc="25.0"
        facing="90.0" />
    <building type="Ice Storage Bin" xloc="35.0" yloc="-5.0"
        facing="90.0" />
    <building type="Carbon Storage Bin" xloc="35.0" yloc="-10.0"
        facing="90.0" />

    <vehicle type="Explorer Rover" number="2" />
    <vehicle type="Transport Rover" number="1" />
    <vehicle type="Cargo Rover" number="1" />
    <vehicle type="Light Utility Vehicle" number="2" />
    <vehicle type="Delivery Drone" number="2" />

    <equipment type="EVA Suit" number="24" />
    <equipment type="Gas Canister" number="120" />
    <equipment type="Barrel" number="120" />
    <equipment type="Bag" number="120" />
    <equipment type="Large Bag" number="70" />
    <equipment type="Specimen Box" number="70" />

	<!-- Life Support Resources -->
	<resource type="food" amount="6000.0" />
	<resource type="water" amount="12000.0" />
	<resource type="oxygen" amount="6000.0" />
	
    <part-package name="package 3" number="1" />
    
    <resupply>
       	<resupply-mission name="Standard Resupply 1"
            arrival-time="0.1" />   
        <resupply-mission name="Resupply for Phase 3"
            arrival-time="670.0" />
    </resupply>
</template>
