=== mars-sim/mars-sim/mars-sim-core/src/main/resources/xml/settlement/settlement.xsd
<?xml version="1.0" encoding="UTF-8" ?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">

    <xs:element name="connection-list">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="connection" maxOccurs="unbounded">
                    <xs:complexType>
                        <xs:attribute name="xloc" type="xs:decimal"/>
                        <xs:attribute name="yloc" type="xs:decimal"/>
                        <xs:attribute name="hatch-facing" type="xs:string"/>
                        <xs:attribute name="id" type="xs:string"/>                   
                    </xs:complexType>
                </xs:element>
            </xs:sequence>
        </xs:complexType>
    </xs:element>

    <xs:element name="building">
        <xs:complexType>
            <xs:sequence>
                <xs:element ref="connection-list" minOccurs="0"/>
            </xs:sequence>
            <xs:attribute name="type" type="xs:string"/>
            <xs:attribute name="width" type="xs:decimal"/>
            <xs:attribute name="length" type="xs:decimal"/>
            <xs:attribute name="xloc" type="xs:decimal"/>
            <xs:attribute name="yloc" type="xs:decimal"/>
            <xs:attribute name="facing" type="xs:decimal"/>
            <xs:attribute name="id" type="xs:string"/>
            <xs:attribute name="zone" type="xs:integer"/>            
        </xs:complexType>
    </xs:element>
    
   <xs:element name="connector">
        <xs:complexType>
            <xs:sequence>
                <xs:element ref="connection-list" minOccurs="0"/>
            </xs:sequence>
            <xs:attribute name="type" type="xs:string"/>
            <xs:attribute name="width" type="xs:decimal"/>
            <xs:attribute name="length" type="xs:decimal"/>
            <xs:attribute name="xloc" type="xs:decimal"/>
            <xs:attribute name="yloc" type="xs:decimal"/>
            <xs:attribute name="facing" type="xs:decimal"/>
            <xs:attribute name="id" type="xs:string"/>
            <xs:attribute name="zone" type="xs:integer"/>            
        </xs:complexType>
    </xs:element>
    
    <xs:element name="standalone">
        <xs:complexType>
            <xs:attribute name="type" type="xs:string"/>
            <xs:attribute name="xloc" type="xs:decimal"/>
            <xs:attribute name="yloc" type="xs:decimal"/>
            <xs:attribute name="facing" type="xs:decimal"/>
        </xs:complexType>
    </xs:element>
 
    <xs:element name="building-package">
        <xs:complexType>
            <xs:attribute name="name" type="xs:string"/>
        </xs:complexType>
    </xs:element>
       
    <xs:element name="vehicle">
        <xs:complexType>
            <xs:attribute name="type" type="xs:string"/>
            <xs:attribute name="number" type="xs:decimal"/>
        </xs:complexType>
    </xs:element>
    
    <xs:element name="robot-new">
        <xs:complexType>
            <xs:attribute name="type" type="xs:string"/>
            <xs:attribute name="number" type="xs:decimal"/>
        </xs:complexType>
    </xs:element>

    <!-- This is deprecated-->
    <xs:element name="robot">
        <xs:complexType>
            <xs:attribute name="type" type="xs:string"/>
            <xs:attribute name="name" type="xs:string"  use="optional"/>
            <xs:attribute name="model" type="xs:string"  use="optional"/>
        </xs:complexType>
    </xs:element>

    <xs:element name="building-plan">
        <xs:complexType>
            <xs:attribute name="building-type" type="xs:string" use="required"/>
            <xs:attribute name="delay-sols" type="xs:nonNegativeInteger" use="required"/>
        </xs:complexType>
    </xs:element>

    <xs:element name="equipment">
        <xs:complexType>
            <xs:attribute name="type" type="xs:string"/>
            <xs:attribute name="number" type="xs:decimal"/>
        </xs:complexType>
    </xs:element>
    
    <xs:element name="bin">
        <xs:complexType>
            <xs:attribute name="type" type="xs:string"/>
            <xs:attribute name="number" type="xs:decimal"/>
        </xs:complexType>
    </xs:element>
    
    <xs:element name="resource">
        <xs:complexType>
            <xs:attribute name="type" type="xs:string"/>
            <xs:attribute name="amount" type="xs:decimal"/>
        </xs:complexType>
    </xs:element>

    <xs:element name="part">
        <xs:complexType>
            <xs:attribute name="type" type="xs:string"/>
            <xs:attribute name="number" type="xs:decimal"/>
        </xs:complexType>
    </xs:element>

    <xs:element name="part-package">
        <xs:complexType>
            <xs:attribute name="name" type="xs:string"/>
            <xs:attribute name="number" type="xs:decimal"/>
        </xs:complexType>
    </xs:element>

    <!-- This should be a common xsd -->
    <xs:element name="schedule">
        <xs:complexType>
            <xs:attribute name="firstSol" type="xs:string" use="optional"/>
            <xs:attribute name="eventTime" type="xs:string"/>
            <xs:attribute name="frequency" type="xs:decimal" use="optional"/>
        </xs:complexType>
    </xs:element>

    <xs:element name="resupply-mission">
        <xs:complexType>
            <xs:sequence>
                <xs:element ref="schedule"/>
            </xs:sequence>
            <xs:attribute name="name" type="xs:string"/>
            <xs:attribute name="manifest-name" type="xs:string"/>
        </xs:complexType>
    </xs:element>

    <xs:element name="resupply">
        <xs:complexType>
            <xs:sequence>
                <xs:element ref="resupply-mission" maxOccurs="unbounded"/>
            </xs:sequence>
        </xs:complexType>
    </xs:element>

    <xs:element name="template">
        <xs:complexType>
            <xs:sequence>
                <xs:element ref="building"  maxOccurs="unbounded"/>
                <xs:element ref="connector" minOccurs="0" maxOccurs="unbounded"/>
                <xs:element ref="standalone" minOccurs="0" maxOccurs="unbounded"/>
                <xs:element ref="building-package" minOccurs="0" maxOccurs="unbounded"/> 
                <xs:element ref="vehicle"  minOccurs="0" maxOccurs="unbounded"/>
                <xs:element ref="robot-new"  minOccurs="0" maxOccurs="unbounded"/>
                <xs:element ref="robot"  minOccurs="0" maxOccurs="unbounded"/>
                <xs:element ref="building-plan"  minOccurs="0" maxOccurs="unbounded"/>
                <xs:element ref="equipment"  minOccurs="0" maxOccurs="unbounded"/>
				<xs:element ref="bin"  minOccurs="0" maxOccurs="unbounded"/>
                <xs:element ref="resource"  minOccurs="0" maxOccurs="unbounded"/>
                <xs:element ref="part"  minOccurs="0" maxOccurs="unbounded"/>
                <xs:element ref="part-package" minOccurs="0" maxOccurs="unbounded"/>              
                <xs:element ref="resupply" minOccurs="0" maxOccurs="1"/>
            </xs:sequence>
            <xs:attribute name="name" type="xs:string"/>
            <xs:attribute name="description" type="xs:string"/>
            <xs:attribute name="sponsor" type="xs:string"/>
            <xs:attribute name="shift-pattern" type="xs:string"  use="optional"/>
            <xs:attribute name="objective" type="xs:string"  use="optional"/>
            <xs:attribute name="default-population" type="xs:integer"/>
            <xs:attribute name="number-of-robots" type="xs:integer"  use="optional"/>
        </xs:complexType>
    </xs:element>
</xs:schema>

=== mars-sim/mars-sim/mars-sim-core/src/main/resources/xml/settlement/settlement_phase_1-sa.xml
<?xml version = "1.0" encoding = "UTF-8" standalone = "yes" ?>
<template xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="settlement.xsd"
    name="Phase 1-SA" default-population="4" description="Phase 1 base for Saudi Arabia"
	sponsor="SSA">

    <building id="0" type="Lander Hab" xloc="0.0" yloc="0.0"
        facing="0.0">
        <connection-list>
            <connection id="1" xloc="4.5" yloc="0.0" />
            <connection id="2" xloc="-4.5" yloc="0.0" />
        </connection-list>
    </building>

    <!-- EVA Airlock is attached to the lander hab -->
    <building id="1" type="EVA Airlock" xloc="7.5" yloc="0.0"
        facing="0.0">
        <connection-list>
            <connection id="0" xloc="-3.0" yloc="0.0" />
        </connection-list>
    </building>

    <building id="2" type="Hallway" length="3.0" xloc="-6.0"
        yloc="0.0" facing="270.0">
        <connection-list>
            <connection id="0" xloc="0.0" yloc="1.5" />
            <connection id="3" xloc="0.0" yloc="-1.5" />
        </connection-list>
    </building>

    <building id="3" type="Lounge" xloc="-12.0" yloc="0.0"
        facing="270.0">
        <connection-list>
            <connection id="2" xloc="0.0" yloc="4.5" />
            <connection id="4" xloc="0.0" yloc="-4.5" />
        </connection-list>
    </building>

    <building id="4" type="Hallway" length="3.0" xloc="-18.0"
        yloc="0.0" facing="270.0">
        <connection-list>
            <connection id="3" xloc="0.0" yloc="1.5" />
            <connection id="5" xloc="0.0" yloc="-1.5" />
        </connection-list>
    </building>

    <building id="5" type="Inflatable Greenhouse" xloc="-24.0"
        yloc="0.0" facing="270.0">
        <connection-list>
            <connection id="4" xloc="0.0" yloc="4.5" />
        </connection-list>
    </building>


    <!-- Building Packages -->
    <building-package name="Storage Set 1"/>
   	<building-package name="ERV Set 1"/>
   	<building-package name="Air Set 1 - 1x1"/>
   	<building-package name="Solar Set 1 - 1x9"/>
	<building-package name="Kilo Set 1 - 1x2"/>
 	<building-package name="Brine Water Well Set 1 - 1x1"/>
 	 		   		
    <initial-supplies>
 	 		   		
    <vehicle type="Explorer Rover" number="2" />
    <vehicle type="Light Utility Vehicle" number="1" />
    <vehicle type="Delivery Drone" number="1" />

    <!-- Standard Phase 1 allocation-->
    <robot type="GardenBot-Advanced" number="1"/>
    <robot type="MakerBot-Standard" number="1"/>
    <robot type="MedicBot-Advanced" number="1"/>
    <robot type="RepairBot-Standard" number="1"/>

    <equipment type="EVA Suit" number="8" />

    <!-- Containers-->
	<equipment type="barrel" number="40" />
	<equipment type="bag" number="40" />
	<equipment type="gas canister" number="40" />		
	<equipment type="large bag" number="40" />
	<equipment type="specimen box" number="40" />
    <equipment type="thermal bottle" number="8" />	
 	<equipment type="wheelbarrow" number="12" />

    <!-- Life Support Resources -->
	<resource type="food" amount="720" />
	<resource type="water" amount="3600" />
	<resource type="oxygen" amount="1440" />
	
    <part-package name="Standard Part Package 1" number="1" />
 	 		   		
    </initial-supplies>


    <resupply>
        <resupply-mission name="Food Delivery" manifest-name="Food Resupply 1">
            <schedule firstSol="1" frequency="80" />
        </resupply-mission>
        <resupply-mission name="Phase 1 Delivery" manifest-name="Resupply for Phase 1">
                <schedule frequency="120" />
        </resupply-mission>
    </resupply>
</template>

=== mars-sim/mars-sim/mars-sim-core/src/main/resources/xml/settlement/settlement_phase_3-sx.xml
<?xml version = "1.0" encoding = "UTF-8" standalone = "yes" ?>
<template xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="settlement.xsd"
    name="Phase 3-SX" default-population="12" description="Phase 3 for SpaceX"
    sponsor="SPACEX">
    
    <building id="0" type="Lander Hab" xloc="0.0" yloc="0.0"
        facing="0.0">
        <connection-list>
            <connection id="1" xloc="0.0" yloc="4.5" />
            <connection id="5" xloc="-4.5" yloc="0.0" />
            <connection id="21" xloc="4.5" yloc="0.0" />
        </connection-list>
    </building>
    <building id="1" type="Hallway" length="4.0" xloc="0.0"
        yloc="6.5" facing="0.0">
        <connection-list>
            <connection id="0" xloc="0.0" yloc="-2.0" />
            <connection id="2" xloc="0.0" yloc="2.0" />
        </connection-list>
    </building>
    <building id="2" type="Research Hab" xloc="0.0" yloc="13.0"
        facing="0.0">
        <connection-list>
            <connection id="1" xloc="0.0" yloc="-4.5" />
            <connection id="3" xloc="0.0" yloc="4.5" />
            <connection id="9" xloc="-4.5" yloc="0.0" />
        </connection-list>
    </building>
    <building id="3" type="Hallway" length="4.0" xloc="0.0"
        yloc="19.5" facing="0.0">
        <connection-list>
            <connection id="2" xloc="0.0" yloc="-2.0" />
            <connection id="4" xloc="0.0" yloc="2.0" />
        </connection-list>
    </building>
    <building id="4" type="Storage Hab" xloc="0.0" yloc="26.0"
        facing="0.0">
        <connection-list>
            <connection id="3" xloc="0.0" yloc="-4.5" />
            <connection id="13" xloc="-4.5" yloc="0.0" />
        </connection-list>
    </building>

    <!-- The first row -->
    <building id="5" type="Hallway" length="3.0" xloc="-6.0"
        yloc="0.0" facing="270.0">
        <connection-list>
            <connection id="0" xloc="0.0" yloc="1.5" />
            <connection id="6" xloc="0.0" yloc="-1.5" />
        </connection-list>
    </building>
    <building id="6" type="Lounge" xloc="-12.0" yloc="0.0"
        facing="270.0">
        <connection-list>
            <connection id="5" xloc="0.0" yloc="4.5" />
            <connection id="7" xloc="0.0" yloc="-4.5" />
        </connection-list>
    </building>

    <building id="7" type="Hallway" length="3.0" xloc="-18.0"
        yloc="0.0" facing="270.0">
        <connection-list>
            <connection id="6" xloc="0.0" yloc="1.5" />
            <connection id="8" xloc="0.0" yloc="-1.5" />
        </connection-list>
    </building>
    <building id="8" type="Residential Quarters" xloc="-24.0"
        yloc="0.0" facing="270.0">
        <connection-list>
            <connection id="7" xloc="0.0" yloc="4.5" />
            <connection id="17" xloc="-3.0" yloc="0.0" />
            <connection id="19" xloc="3.0" yloc="0.0" />
        </connection-list>
    </building>

    <!-- The second row -->
    <building id="9" type="Hallway" length="3.0" xloc="-6.0"
        yloc="13.0" facing="270.0">
        <connection-list>
            <connection id="2" xloc="0.0" yloc="1.5" />
            <connection id="10" xloc="0.0" yloc="-1.5" />
        </connection-list>
    </building>
    <building id="10" type="Inflatable Greenhouse" xloc="-12.0"
        yloc="13.0" facing="270.0">
        <connection-list>
            <connection id="9" xloc="0.0" yloc="4.5" />
            <connection id="11" xloc="0.0" yloc="-4.5" />
        </connection-list>
    </building>

    <building id="11" type="Hallway" length="3.0" xloc="-18.0"
        yloc="13.0" facing="270.0">
        <connection-list>
            <connection id="10" xloc="0.0" yloc="1.5" />
            <connection id="12" xloc="0.0" yloc="-1.5" />
        </connection-list>
    </building>
    <building id="12" type="Fish Farm" xloc="-24.0"
        yloc="13.0" facing="270.0">
        <connection-list>
            <connection id="11" xloc="0.0" yloc="4.5" />
            <connection id="17" xloc="3.0" yloc="0.0" />
            <connection id="18" xloc="-3.0" yloc="0.0" />
        </connection-list>
    </building>

    <!-- The third row -->
    <building id="13" type="Hallway" length="3.0" xloc="-6.0"
        yloc="26.0" facing="270.0">
        <connection-list>
            <connection id="4" xloc="0.0" yloc="1.5" />
            <connection id="14" xloc="0.0" yloc="-1.5" />
        </connection-list>
    </building>
    <building id="14" type="Laboratory" xloc="-12.0" yloc="26.0"
        facing="270.0">
        <connection-list>
            <connection id="13" xloc="0.0" yloc="4.5" />
            <connection id="15" xloc="0.0" yloc="-4.5" />
        </connection-list>
    </building>

    <building id="15" type="Hallway" length="3.0" xloc="-18.0"
        yloc="26.0" facing="270.0">
        <connection-list>
            <connection id="14" xloc="0.0" yloc="1.5" />
            <connection id="16" xloc="0.0" yloc="-1.5" />
        </connection-list>
    </building>
    <building id="16" type="Workshop" xloc="-24.0"
        yloc="26.0" facing="270.0">
        <connection-list>
            <connection id="15" xloc="0.0" yloc="4.5" />
            <connection id="18" xloc="3.0" yloc="0.0" />
        </connection-list>
    </building>

    <!-- This hallway connects the inflatable greenhouse on the first row
        to that of second row -->
    <building id="17" type="Hallway" length="7.0" xloc="-24.0"
        yloc="6.5" facing="0.0">
        <connection-list>
            <connection id="8" xloc="0.0" yloc="-3.5" />
            <connection id="12" xloc="0.0" yloc="3.5" />
        </connection-list>
    </building>

    <!-- This hallway connects the inflatable greenhouse on the second row
        to that of the third row -->
    <building id="18" type="Hallway" length="7.0" xloc="-24.0"
        yloc="19.5" facing="0.0">
        <connection-list>
            <connection id="12" xloc="0.0" yloc="-3.5" />
            <connection id="16" xloc="0.0" yloc="3.5" />
        </connection-list>
    </building>

    <!-- This hallway connects the inflatable greenhouse in the first row
        to the garage -->
    <building id="19" type="Hallway" length="4.0" xloc="-24.0"
        yloc="-5.0" facing="0.0">
        <connection-list>
            <connection id="8" xloc="0.0" yloc="2.0" />
            <connection id="20" xloc="0.0" yloc="-2.0" />
        </connection-list>
    </building>

    <building id="20" type="Garage" xloc="-24.0" yloc="-15"
        facing="180.0">
        <connection-list>
            <connection id="19" xloc="0.0" yloc="-8.0" />
        </connection-list>
    </building>

    <!-- EVA Airlock is attached to the lander hab -->
    <building id="21" type="EVA Airlock" xloc="7.5" yloc="0.0"
        facing="0.0">
        <connection-list>
            <connection id="0" xloc="-3.0" yloc="0.0" />
        </connection-list>
    </building>


    <!-- Building Packages -->
    <building-package name="Storage Set 1"/>   
   	<building-package name="ERV Set 1"/>
   	<building-package name="ERV Set 2"/>
   	<building-package name="Air Set 1 - 1x3"/>
    <building-package name="Sabatier Set 1 - 1x4"/> 
	<building-package name="Solar Set 1 - 1x9"/>
	<building-package name="Solar Thermal Set 1 - 1x9"/>
	<building-package name="Kilo Set 1 - 1x4"/>
	<building-package name="MD1 Set 1 - 1x3"/>
	<building-package name="Small Areothermal Well Set 1 - 1x1"/> 	
 	<building-package name="Brine Water Well Set 1 - 1x2"/>	 	
	
    <initial-supplies>
	
    <vehicle type="Explorer Rover" number="3" />
    <vehicle type="Transport Rover" number="2" />
    <vehicle type="Cargo Rover" number="2" />
    <vehicle type="Light Utility Vehicle" number="3" />
    <vehicle type="Delivery Drone" number="3" />

    <!-- Standard Phase 3 allocation-->
    <robot type="GardenBot-Advanced" number="2"/>
    <robot type="MakerBot-Standard" number="2"/>
    <robot type="MedicBot-Advanced" number="1"/>
    <robot type="RepairBot-Standard" number="2"/>
    <robot type="DeliveryBot-Advanced" number="1"/>
    <robot type="ChefBot-Standard" number="1"/>
    
    <equipment type="EVA Suit" number="24" />

    <!-- Containers-->
	<equipment type="barrel" number="80" />
	<equipment type="bag" number="80" />
	<equipment type="gas canister" number="80" />		
	<equipment type="large bag" number="80" />
	<equipment type="specimen box" number="80" />
    <equipment type="thermal bottle" number="18" />	
 	<equipment type="wheelbarrow" number="18" />
 	
	<!-- Life Support Resources -->
	<resource type="food" amount="2160" />
	<resource type="water" amount="6000" />
	<resource type="oxygen" amount="4320" />
	
    <part-package name="Standard Part Package 1" number="3" />
	
    </initial-supplies>

 
    <resupply>
       	<resupply-mission name="BiMonthly Delivery" manifest-name="Standard Resupply 1">
            <schedule firstSol="30" frequency="60" />
        </resupply-mission>
        <resupply-mission name="Phase 3 Delivery" manifest-name="Resupply for Phase 3">
            <schedule firstSol="668" />
        </resupply-mission> 
    </resupply>
</template>

=== mars-sim/mars-sim/mars-sim-core/src/main/resources/xml/settlement/settlement_phase_2-hu.xml
<?xml version = "1.0" encoding = "UTF-8" standalone = "yes" ?>
<template xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="settlement.xsd"
    name="Phase 2-HU" default-population="8" description="Phase 2 base for HSO/Hungary"
	sponsor="HSO">
    
    <building id="0" type="Lander Hab" xloc="0.0" yloc="0.0"
        facing="0.0">
        <connection-list>
            <connection id="2" xloc="-4.5" yloc="0.0" />
            <connection id="1" xloc="0.0" yloc="4.5" />
            <connection id="12" xloc="4.5" yloc="0.0" />
        </connection-list>
    </building>

    <!-- This hallway connects the lander hab on the first row and the research
        hab on the second row -->
    <building id="1" type="Hallway" length="4.0" xloc="0.0"
        yloc="6.5" facing="0.0">
        <connection-list>
            <connection id="0" xloc="0.0" yloc="-2.0" />
            <connection id="6" xloc="0.0" yloc="2.0" />
        </connection-list>
    </building>

    <building id="2" type="Hallway" length="3.0" xloc="-6.0"
        yloc="0.0" facing="270.0">
        <connection-list>
            <connection id="0" xloc="0.0" yloc="1.5" />
            <connection id="3" xloc="0.0" yloc="-1.5" />
        </connection-list>
    </building>

    <building id="3" type="Workshop" xloc="-12.0" yloc="0.0"
        facing="270.0">
        <connection-list>
            <connection id="2" xloc="0.0" yloc="4.5" />
            <connection id="4" xloc="0.0" yloc="-4.5" />
        </connection-list>
    </building>

    <building id="4" type="Hallway" length="3.0" xloc="-18.0"
        yloc="0.0" facing="270.0">
        <connection-list>
            <connection id="3" xloc="0.0" yloc="1.5" />
            <connection id="5" xloc="0.0" yloc="-1.5" />
        </connection-list>
    </building>

    <building id="5" type="Algae Pond" xloc="-24.0"
        yloc="0.0" facing="270.0">
        <connection-list>
            <connection id="4" xloc="0.0" yloc="4.5" />
            <connection id="11" xloc="-3.0" yloc="0.0" />
        </connection-list>
    </building>

    <building id="6" type="Lander Hab" xloc="0.0" yloc="13.0"
        facing="0.0">
        <connection-list>
            <connection id="1" xloc="0.0" yloc="-4.5" />
            <connection id="7" xloc="-4.5" yloc="0.0" />
        </connection-list>
    </building>

    <building id="7" type="Hallway" length="3.0" xloc="-6.0"
        yloc="13.0" facing="270.0">
        <connection-list>
            <connection id="6" xloc="0.0" yloc="1.5" />
            <connection id="8" xloc="0.0" yloc="-1.5" />
        </connection-list>
    </building>

    <building id="8" type="Laboratory" xloc="-12.0" yloc="13.0"
        facing="270.0">
        <connection-list>
            <connection id="7" xloc="0.0" yloc="4.5" />
            <connection id="9" xloc="0.0" yloc="-4.5" />
        </connection-list>
    </building>

    <building id="9" type="Hallway" length="3.0" xloc="-18.0"
        yloc="13.0" facing="270.0">
        <connection-list>
            <connection id="8" xloc="0.0" yloc="1.5" />
            <connection id="10" xloc="0.0" yloc="-1.5" />
        </connection-list>
    </building>

    <building id="10" type="Inflatable Greenhouse" xloc="-24.0"
        yloc="13.0" facing="270.0">
        <connection-list>
            <connection id="9" xloc="0.0" yloc="4.5" />
            <connection id="11" xloc="3.0" yloc="0.0" />
        </connection-list>
    </building>

    <!-- This hallway connects the inflatable greenhouse on the first row
        and the inflatable greenhouse on the second row -->
    <building id="11" type="Hallway" length="7.0" xloc="-24.0"
        yloc="6.5" facing="0.0">
        <connection-list>
            <connection id="5" xloc="0.0" yloc="-3.5" />
            <connection id="10" xloc="0.0" yloc="3.5" />
        </connection-list>
    </building>

    <!-- EVA Airlock is attached to the lander hab -->
    <building id="12" type="EVA Airlock" xloc="7.5" yloc="0.0"
        facing="0.0">
        <connection-list>
            <connection id="0" xloc="-3.0" yloc="0.0" />
        </connection-list>
    </building>

    <!-- Building Packages -->
    <building-package name="Storage Set 1"/>
   	<building-package name="ERV Set 1"/>
   	<building-package name="Air Set 1 - 1x2"/>
    <building-package name="Sabatier Set 1 - 1x3"/>
	<building-package name="Syngas Set 1 - 1x1"/>
	<building-package name="Solar Set 1 - 1x9"/>
   	<building-package name="Wind Set 1 - 1x6"/>	
   	<building-package name="TOPAZ-2A Set 1 - 1x3"/>
	<building-package name="TOPAZ-3 Set 1 - 1x2"/>
	<building-package name="Methane Set 1 - 1x1" />	
 	<building-package name="Brine Water Well Set 1 - 1x1"/>
 	 
    <initial-supplies>
 	 
    <vehicle type="Explorer Rover" number="2" />
    <vehicle type="Light Utility Vehicle" number="1" />
    <vehicle type="Delivery Drone" number="1" />


    <!-- Standard Phase 2 allocation-->
    <robot type="GardenBot-Advanced" number="2"/>
    <robot type="MakerBot-Standard" number="2"/>
    <robot type="MedicBot-Advanced" number="1"/>
    <robot type="RepairBot-Standard" number="2"/>

    <equipment type="EVA Suit" number="16" />

    <!-- Containers-->
	<equipment type="barrel" number="40" />
	<equipment type="bag" number="40" />
	<equipment type="gas canister" number="40" />		
	<equipment type="large bag" number="40" />
	<equipment type="specimen box" number="40" />
    <equipment type="thermal bottle" number="12" />	
 	<equipment type="wheelbarrow" number="12" />
 	
	<!-- Life Support Resources -->
	<resource type="food" amount="1440" />
	<resource type="water" amount="4800" />
	<resource type="oxygen" amount="2880" />

    <part-package name="Standard Part Package 1" number="2" />
 	 
    </initial-supplies>

   	
    <resupply>
       	<resupply-mission name="Quarterly Delivery" manifest-name="Standard Resupply 1">
            <schedule firstSol="1" frequency="150" />
        </resupply-mission>
        <resupply-mission name="Annual Delivery" manifest-name="Resupply for Phase 2">
                <schedule firstSol="668" />
        </resupply-mission>
    </resupply>
</template>
